import { ExerciseItem } from './types';
import { getPinyin } from './utils';

// 键盘布局
export const KEYBOARD_LAYOUT = [
  ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P'],
  ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L'],
  ['Z', 'X', 'C', 'V', 'B', 'N', 'M']
];

export const FINGER_MAPPING: Record<string, { finger: string; hand: 'left' | 'right' }> = {
  'Q': { finger: '小指', hand: 'left' }, 'A': { finger: '小指', hand: 'left' }, 'Z': { finger: '小指', hand: 'left' },
  'W': { finger: '无名指', hand: 'left' }, 'S': { finger: '无名指', hand: 'left' }, 'X': { finger: '无名指', hand: 'left' },
  'E': { finger: '中指', hand: 'left' }, 'D': { finger: '中指', hand: 'left' }, 'C': { finger: '中指', hand: 'left' },
  'R': { finger: '食指', hand: 'left' }, 'F': { finger: '食指', hand: 'left' }, 'V': { finger: '食指', hand: 'left' },
  'T': { finger: '食指', hand: 'left' }, 'G': { finger: '食指', hand: 'left' }, 'B': { finger: '食指', hand: 'left' },
  'Y': { finger: '食指', hand: 'right' }, 'H': { finger: '食指', hand: 'right' }, 'N': { finger: '食指', hand: 'right' },
  'U': { finger: '食指', hand: 'right' }, 'J': { finger: '食指', hand: 'right' }, 'M': { finger: '食指', hand: 'right' },
  'I': { finger: '中指', hand: 'right' }, 'K': { finger: '中指', hand: 'right' }, ',': { finger: '中指', hand: 'right' },
  'O': { finger: '无名指', hand: 'right' }, 'L': { finger: '无名指', hand: 'right' }, '.': { finger: '无名指', hand: 'right' },
  'P': { finger: '小指', hand: 'right' }, ';': { finger: '小指', hand: 'right' }, '/': { finger: '小指', hand: 'right' },
  ' ': { finger: '大拇指', hand: 'left' }
};

// --- DATA SOURCE: 人教版小学英语教师用书词汇表（1-2年级新起点SL版 / 3-6年级PEP版）---
// 审计基准：每册按教师用书附录单元词汇表全量收录，含四会词与认读词
// 结构: "word": [音标, 中文释义, 例句]

const EN_METADATA: Record<string, [string, string, string]> = {
  // ============ 一年级上册 (新起点1A: School/Face/Animals/Numbers/Colours/Fruit) ============
  "school": ["/skuːl/", "学校", "I go to school."],
  "book": ["/bʊk/", "书", "Open your book."],
  "ruler": ["/ˈruːlə/", "尺子", "This is my ruler."],
  "pencil": ["/ˈpensl/", "铅笔", "I have a pencil."],
  "eraser": ["/ɪˈreɪzə/", "橡皮", "Where is my eraser?"],
  "pencil box": ["/ˈpensl bɒks/", "铅笔盒", "My pencil box is new."],
  "bag": ["/bæɡ/", "书包", "My bag is heavy."],
  "teacher": ["/ˈtiːtʃə/", "老师", "Hello, teacher!"],
  "hello": ["/həˈləʊ/", "你好", "Hello, my friend."],
  "hi": ["/haɪ/", "嗨", "Hi, I'm Amy."],
  "goodbye": ["/ˌɡʊdˈbaɪ/", "再见", "Goodbye, see you."],
  "bye": ["/baɪ/", "拜拜", "Bye-bye, Tom!"],
  "name": ["/neɪm/", "名字", "My name is Sam."],
  "my": ["/maɪ/", "我的", "This is my bag."],
  "your": ["/jɔː/", "你的", "What's your name?"],
  "face": ["/feɪs/", "脸", "Touch your face."],
  "ear": ["/ɪə/", "耳朵", "Listen with your ears."],
  "eye": ["/aɪ/", "眼睛", "Close your eyes."],
  "nose": ["/nəʊz/", "鼻子", "Touch your nose."],
  "mouth": ["/maʊθ/", "嘴巴", "Open your mouth."],
  "look": ["/lʊk/", "看", "Look at me!"],
  "dog": ["/dɒɡ/", "狗", "The dog runs fast."],
  "cat": ["/kæt/", "猫", "It is a fat cat."],
  "bird": ["/bɜːd/", "鸟", "Birds can fly."],
  "tiger": ["/ˈtaɪɡə/", "老虎", "The tiger is strong."],
  "monkey": ["/ˈmʌŋki/", "猴子", "The monkey likes bananas."],
  "elephant": ["/ˈelɪfənt/", "大象", "Look at the elephant."],
  "panda": ["/ˈpændə/", "熊猫", "The panda is cute."],
  "zoo": ["/zuː/", "动物园", "Let's go to the zoo."],
  "one": ["/wʌn/", "一", "One finger."],
  "two": ["/tuː/", "二", "Two eyes."],
  "three": ["/θriː/", "三", "Three birds."],
  "four": ["/fɔː/", "四", "Four legs."],
  "five": ["/faɪv/", "五", "High five!"],
  "six": ["/sɪks/", "六", "Six ducks."],
  "seven": ["/ˈsevn/", "七", "Seven colours."],
  "eight": ["/eɪt/", "八", "Eight monkeys."],
  "nine": ["/naɪn/", "九", "Nine stars."],
  "ten": ["/ten/", "十", "Count to ten."],
  "red": ["/red/", "红色", "A red apple."],
  "yellow": ["/ˈjeləʊ/", "黄色", "A yellow duck."],
  "blue": ["/bluː/", "蓝色", "The sky is blue."],
  "green": ["/ɡriːn/", "绿色", "The grass is green."],
  "black": ["/blæk/", "黑色", "A black cat."],
  "white": ["/waɪt/", "白色", "White clouds."],
  "brown": ["/braʊn/", "棕色", "A brown bear."],
  "orange": ["/ˈɒrɪndʒ/", "橙色/橙子", "An orange is round."],
  "pink": ["/pɪŋk/", "粉色", "A pink dress."],
  "purple": ["/ˈpɜːpl/", "紫色", "Purple grapes."],
  "apple": ["/ˈæpl/", "苹果", "A is for apple."],
  "pear": ["/peə/", "梨", "A sweet pear."],
  "banana": ["/bəˈnɑːnə/", "香蕉", "A yellow banana."],
  "peach": ["/piːtʃ/", "桃子", "The peach is sweet."],
  "grapes": ["/ɡreɪps/", "葡萄", "I like grapes."],
  "watermelon": ["/ˈwɔːtəmelən/", "西瓜", "A big watermelon."],
  "strawberry": ["/ˈstrɔːbəri/", "草莓", "A sweet strawberry."],
  "fruit": ["/fruːt/", "水果", "I eat fruit every day."],
  "sweet": ["/swiːt/", "甜的", "The apple is sweet."],
  "ant": ["/ænt/", "蚂蚁", "Ants are small."],
  "duck": ["/dʌk/", "鸭子", "The duck says quack."],
  "egg": ["/eɡ/", "鸡蛋", "I like eggs."],
  "jet": ["/dʒet/", "喷气式飞机", "Look at the jet."],
  "kite": ["/kaɪt/", "风筝", "Fly a kite."],
  "leg": ["/leɡ/", "腿", "Shake your legs."],
  "hand": ["/hænd/", "手", "Clap your hands."],
  "foot": ["/fʊt/", "脚", "Stomp your foot."],
  "head": ["/hed/", "头", "Touch your head."],
  "arm": ["/ɑːm/", "手臂", "Wave your arms."],
  "body": ["/ˈbɒdi/", "身体", "Move your body."],
  "hair": ["/heə/", "头发", "Her hair is long."],
  "good": ["/ɡʊd/", "好的", "Good morning!"],
  "morning": ["/ˈmɔːnɪŋ/", "早晨", "Good morning, Mum."],
  "afternoon": ["/ˌɑːftəˈnuːn/", "下午", "Good afternoon, class."],
  "night": ["/naɪt/", "夜晚", "Good night, Dad."],
  "day": ["/deɪ/", "白天/一天", "Have a nice day!"],
  "sun": ["/sʌn/", "太阳", "The sun is big."],
  "moon": ["/muːn/", "月亮", "The moon is bright."],
  "star": ["/stɑː/", "星星", "I see a star."],
  "sky": ["/skaɪ/", "天空", "The sky is blue."],
  "rain": ["/reɪn/", "雨", "Rain falls down."],
  "snow": ["/snəʊ/", "雪", "Snow is white."],
  "wind": ["/wɪnd/", "风", "The wind blows."],
  "cloud": ["/klaʊd/", "云", "A white cloud."],

  // ============ 一年级下册 (新起点1B: Classroom/Room/Toys/Food/Drink) ============
  "classroom": ["/ˈklɑːsruːm/", "教室", "This is my classroom."],
  "desk": ["/desk/", "书桌", "My desk is clean."],
  "chair": ["/tʃeə/", "椅子", "Sit on the chair."],
  "blackboard": ["/ˈblækbɔːd/", "黑板", "Look at the blackboard."],
  "door": ["/dɔː/", "门", "Close the door."],
  "window": ["/ˈwɪndəʊ/", "窗户", "Open the window."],
  "in": ["/ɪn/", "在……里面", "The cat is in the box."],
  "on": ["/ɒn/", "在……上面", "The book is on the desk."],
  "under": ["/ˈʌndə/", "在……下面", "The ball is under the bed."],
  "where": ["/weə/", "哪里", "Where is my cat?"],
  "room": ["/ruːm/", "房间", "My room is small."],
  "table": ["/ˈteɪbl/", "桌子", "The tea is on the table."],
  "bed": ["/bed/", "床", "Go to bed now."],
  "lamp": ["/læmp/", "台灯", "Turn on the lamp."],
  "sofa": ["/ˈsəʊfə/", "沙发", "The sofa is soft."],
  "toy": ["/tɔɪ/", "玩具", "This is my toy."],
  "plane": ["/pleɪn/", "飞机", "The plane flies high."],
  "ball": ["/bɔːl/", "球", "Bounce the ball."],
  "doll": ["/dɒl/", "娃娃", "The doll is pretty."],
  "car": ["/kɑː/", "小汽车", "My toy car is red."],
  "bus": ["/bʌs/", "公共汽车", "I take the bus."],
  "bike": ["/baɪk/", "自行车", "Ride a bike."],
  "teddy bear": ["/ˈtedi beə/", "泰迪熊", "I love my teddy bear."],
  "rice": ["/raɪs/", "米饭", "I eat rice."],
  "noodles": ["/ˈnuːdlz/", "面条", "Noodles are long."],
  "chicken": ["/ˈtʃɪkɪn/", "鸡肉", "The chicken is yummy."],
  "fish": ["/fɪʃ/", "鱼", "Fish swim."],
  "vegetable": ["/ˈvedʒtəbl/", "蔬菜", "Eat your vegetables."],
  "hungry": ["/ˈhʌŋɡri/", "饿的", "I am hungry."],
  "thirsty": ["/ˈθɜːsti/", "渴的", "I am thirsty."],
  "juice": ["/dʒuːs/", "果汁", "Orange juice is sweet."],
  "milk": ["/mɪlk/", "牛奶", "Drink milk daily."],
  "water": ["/ˈwɔːtə/", "水", "Drink some water."],
  "tea": ["/tiː/", "茶", "Hot tea for Dad."],
  "cake": ["/keɪk/", "蛋糕", "A birthday cake."],
  "bread": ["/bred/", "面包", "Fresh bread."],
  "hamburger": ["/ˈhæmbɜːɡə/", "汉堡包", "A big hamburger."],
  "hot dog": ["/hɒt dɒɡ/", "热狗", "I like hot dogs."],
  "coffee": ["/ˈkɒfi/", "咖啡", "Coffee is for Dad."],
  "candy": ["/ˈkændi/", "糖果", "Sweet candy."],
  "kangaroo": ["/ˌkæŋɡəˈruː/", "袋鼠", "The kangaroo jumps."],
  "lion": ["/ˈlaɪən/", "狮子", "The lion is brave."],
  "giraffe": ["/dʒəˈrɑːf/", "长颈鹿", "A tall giraffe."],
  "deer": ["/dɪə/", "鹿", "A fast deer."],
  "snake": ["/sneɪk/", "蛇", "The snake is long."],
  "cute": ["/kjuːt/", "可爱的", "The panda is cute."],
  "fat": ["/fæt/", "胖的", "A fat pig."],
  "thin": ["/θɪn/", "瘦的", "A thin monkey."],
  "big": ["/bɪɡ/", "大的", "A big elephant."],
  "small": ["/smɔːl/", "小的", "A small ant."],
  "tall": ["/tɔːl/", "高的", "A tall tree."],
  "short": ["/ʃɔːt/", "矮的/短的", "A short pencil."],
  "long": ["/lɒŋ/", "长的", "A long ruler."],
  "family": ["/ˈfæmɪli/", "家庭", "A happy family."],
  "dad": ["/dæd/", "爸爸", "I love my dad."],
  "mum": ["/mʌm/", "妈妈", "I love my mum."],
  "brother": ["/ˈbrʌðə/", "兄弟", "He is my brother."],
  "sister": ["/ˈsɪstə/", "姐妹", "My little sister."],
  "grandma": ["/ˈɡrænmɑː/", "奶奶/外婆", "Grandma is kind."],
  "grandpa": ["/ˈɡrænpɑː/", "爷爷/外公", "Grandpa smiles."],
  "friend": ["/frend/", "朋友", "We are friends."],
  "boy": ["/bɔɪ/", "男孩", "A clever boy."],
  "girl": ["/ɡɜːl/", "女孩", "A pretty girl."],
  "yes": ["/jes/", "是", "Yes, I can."],
  "no": ["/nəʊ/", "不", "No, thank you."],
  "please": ["/pliːz/", "请", "Please sit down."],
  "sorry": ["/ˈsɒri/", "对不起", "Sorry, Mum."],
  "ok": ["/ˌəʊˈkeɪ/", "好的", "OK, let's go."],
  "dance": ["/dɑːns/", "跳舞", "Let's dance."],
  "sing": ["/sɪŋ/", "唱歌", "Sing a song."],
  "draw": ["/drɔː/", "画画", "Draw a picture."],
  "jump": ["/dʒʌmp/", "跳", "Jump high!"],
  "run": ["/rʌn/", "跑", "Run fast."],
  "walk": ["/wɔːk/", "走路", "Walk to school."],
  "swim": ["/swɪm/", "游泳", "Fish swim."],
  "fly": ["/flaɪ/", "飞", "Birds fly."],
  "sleep": ["/sliːp/", "睡觉", "Good sleep."],
  "get up": ["/ɡet ʌp/", "起床", "I get up early."],
  "go to school": ["/ɡəʊ tuː skuːl/", "去上学", "I go to school."],
  "go home": ["/ɡəʊ həʊm/", "回家", "Let's go home."],
  "bus stop": ["/bʌs stɒp/", "公交车站", "Wait at the bus stop."],

  // ============ 二年级上册 (新起点2A: Family/Boys&Girls/Parks/Streets/Sports) ============
  "grandfather": ["/ˈɡrænfɑːðə/", "祖父/外公", "My grandfather is wise."],
  "grandmother": ["/ˈɡrænmʌðə/", "祖母/外婆", "My grandmother cooks."],
  "father": ["/ˈfɑːðə/", "父亲", "This is my father."],
  "mother": ["/ˈmʌðə/", "母亲", "My mother loves me."],
  "man": ["/mæn/", "男人", "A tall man."],
  "woman": ["/ˈwʊmən/", "女人", "A kind woman."],
  "park": ["/pɑːk/", "公园", "Play in the park."],
  "grass": ["/ɡrɑːs/", "草", "The grass is green."],
  "flower": ["/ˈflaʊə/", "花", "A red flower."],
  "tree": ["/triː/", "树", "A tall tree."],
  "lake": ["/leɪk/", "湖", "The lake is blue."],
  "hill": ["/hɪl/", "小山", "Climb the hill."],
  "street": ["/striːt/", "街道", "The street is busy."],
  "shop": ["/ʃɒp/", "商店", "A toy shop."],
  "cinema": ["/ˈsɪnəmə/", "电影院", "Go to the cinema."],
  "supermarket": ["/ˈsuːpəmɑːkɪt/", "超市", "Shop at the supermarket."],
  "hospital": ["/ˈhɒspɪtl/", "医院", "The hospital is big."],
  "train": ["/treɪn/", "火车", "A fast train."],
  "ship": ["/ʃɪp/", "轮船", "A big ship."],
  "taxi": ["/ˈtæksi/", "出租车", "Take a taxi."],
  "jeep": ["/dʒiːp/", "吉普车", "A green jeep."],
  "boat": ["/bəʊt/", "小船", "Row a boat."],
  "map": ["/mæp/", "地图", "Look at the map."],
  "basketball": ["/ˈbɑːskɪtbɔːl/", "篮球", "Play basketball."],
  "football": ["/ˈfʊtbɔːl/", "足球", "Kick the football."],
  "ping-pong": ["/ˈpɪŋ pɒŋ/", "乒乓球", "Play ping-pong."],
  "tennis": ["/ˈtenɪs/", "网球", "Tennis is fun."],
  "sports": ["/spɔːts/", "运动", "I love sports."],
  "music": ["/ˈmjuːzɪk/", "音乐", "I like music."],
  "art": ["/ɑːt/", "美术", "Art class is fun."],
  "math": ["/mæθ/", "数学", "Math is easy."],
  "chinese": ["/ˌtʃaɪˈniːz/", "语文/中文", "I study Chinese."],
  "english": ["/ˈɪŋɡlɪʃ/", "英语", "I speak English."],
  "science": ["/ˈsaɪəns/", "科学", "Science is cool."],
  "computer": ["/kəmˈpjuːtə/", "电脑", "A new computer."],
  "painting": ["/ˈpeɪntɪŋ/", "绘画", "A beautiful painting."],
  "game": ["/ɡeɪm/", "游戏", "Play a game."],
  "farmer": ["/ˈfɑːmə/", "农民", "A busy farmer."],
  "driver": ["/ˈdraɪvə/", "司机", "A bus driver."],
  "doctor": ["/ˈdɒktə/", "医生", "See a doctor."],
  "nurse": ["/nɜːs/", "护士", "A gentle nurse."],
  "cook": ["/kʊk/", "厨师", "A great cook."],
  "worker": ["/ˈwɜːkə/", "工人", "A hard worker."],
  "pupil": ["/ˈpjuːpl/", "小学生", "I am a pupil."],
  "study": ["/ˈstʌdi/", "学习/书房", "I study hard."],
  "work": ["/wɜːk/", "工作", "Dad goes to work."],
  "play": ["/pleɪ/", "玩耍", "We play together."],
  "read": ["/riːd/", "阅读", "Read a book."],
  "write": ["/raɪt/", "写", "Write your name."],
  "help": ["/help/", "帮助", "I help Mum."],
  "love": ["/lʌv/", "爱", "I love my family."],
  "happy": ["/ˈhæpi/", "快乐的", "I am happy."],
  "sad": ["/sæd/", "悲伤的", "Don't be sad."],
  "new": ["/njuː/", "新的", "A new bag."],
  "old": ["/əʊld/", "旧的/年老的", "An old book."],
  "cold": ["/kəʊld/", "寒冷的", "It is cold today."],
  "hot": ["/hɒt/", "炎热的", "The tea is hot."],
  "cool": ["/kuːl/", "凉爽的", "Cool wind blows."],
  "warm": ["/wɔːm/", "温暖的", "Warm spring days."],
  "breakfast": ["/ˈbrekfəst/", "早餐", "Eat breakfast."],
  "lunch": ["/lʌntʃ/", "午餐", "Yummy lunch."],
  "dinner": ["/ˈdɪnə/", "晚餐", "Family dinner."],
  "time": ["/taɪm/", "时间", "What time is it?"],
  "clock": ["/klɒk/", "时钟", "The clock ticks."],
  "watch": ["/wɒtʃ/", "手表/观看", "Watch a cartoon."],
  "spring": ["/sprɪŋ/", "春天", "Warm spring."],
  "summer": ["/ˈsʌmə/", "夏天", "Hot summer."],
  "autumn": ["/ˈɔːtəm/", "秋天", "Golden autumn."],
  "winter": ["/ˈwɪntə/", "冬天", "Cold winter."],
  "season": ["/ˈsiːzn/", "季节", "Four seasons."],
  "sunny": ["/ˈsʌni/", "晴朗的", "A sunny day."],
  "windy": ["/ˈwɪndi/", "有风的", "A windy day."],
  "cloudy": ["/ˈklaʊdi/", "多云的", "A cloudy sky."],
  "rainy": ["/ˈreɪni/", "下雨的", "A rainy day."],
  "snowy": ["/ˈsnəʊi/", "下雪的", "A snowy winter."],
  "shirt": ["/ʃɜːt/", "衬衫", "A white shirt."],
  "skirt": ["/skɜːt/", "短裙", "A pink skirt."],
  "dress": ["/dres/", "连衣裙", "A pretty dress."],
  "socks": ["/sɒks/", "袜子", "Warm socks."],
  "shoes": ["/ʃuːz/", "鞋子", "Running shoes."],
  "jacket": ["/ˈdʒækɪt/", "夹克", "A blue jacket."],
  "sweater": ["/ˈswetə/", "毛衣", "A cozy sweater."],
  "jeans": ["/dʒiːnz/", "牛仔裤", "Blue jeans."],
  "shorts": ["/ʃɔːts/", "短裤", "Summer shorts."],
  "coat": ["/kəʊt/", "大衣", "A warm coat."],

  // ============ 二年级下册 (新起点2B: Playtime/Body/Seasons/Time/Shopping) ============
  "skate": ["/skeɪt/", "滑冰", "Skate on ice."],
  "plant": ["/plɑːnt/", "种植/植物", "Plant flowers."],
  "hobby": ["/ˈhɒbi/", "爱好", "My hobby is reading."],
  "team": ["/tiːm/", "队伍", "Our team wins."],
  "win": ["/wɪn/", "赢", "We win the game."],
  "can": ["/kæn/", "能/罐头", "I can swim."],
  "wish": ["/wɪʃ/", "愿望", "Make a wish."],
  "party": ["/ˈpɑːti/", "派对", "A birthday party."],
  "gift": ["/ɡɪft/", "礼物", "A gift for you."],
  "card": ["/kɑːd/", "卡片", "Make a card."],
  "balloon": ["/bəˈluːn/", "气球", "A red balloon."],
  "candle": ["/ˈkændl/", "蜡烛", "Light the candle."],
  "song": ["/sɒŋ/", "歌曲", "Sing a song."],
  "letter": ["/ˈletə/", "信/字母", "Write a letter."],
  "picture": ["/ˈpɪktʃə/", "图画", "Draw a picture."],
  "photo": ["/ˈfəʊtəʊ/", "照片", "A family photo."],
  "picnic": ["/ˈpɪknɪk/", "野餐", "A spring picnic."],
  "outside": ["/ˌaʊtˈsaɪd/", "外面", "Play outside."],
  "weather": ["/ˈweðə/", "天气", "How's the weather?"],
  "wet": ["/wet/", "湿的", "The grass is wet."],
  "dry": ["/draɪ/", "干的", "The towel is dry."],
  "slow": ["/sləʊ/", "慢的", "A slow snail."],
  "fast": ["/fɑːst/", "快的", "A fast car."],
  "left": ["/left/", "左边", "Turn left."],
  "right": ["/raɪt/", "右边", "Turn right."],
  "stop": ["/stɒp/", "停止", "Stop at the red light."],
  "wait": ["/weɪt/", "等待", "Wait for me."],
  "turn": ["/tɜːn/", "转弯/轮流", "Turn around."],
  "money": ["/ˈmʌni/", "钱", "Save your money."],
  "buy": ["/baɪ/", "买", "Buy some fruit."],
  "sell": ["/sel/", "卖", "They sell apples."],
  "cheap": ["/tʃiːp/", "便宜的", "Cheap candy."],
  "expensive": ["/ɪkˈspensɪv/", "昂贵的", "An expensive watch."],
  "pretty": ["/ˈprɪti/", "漂亮的", "A pretty flower."],
  "beautiful": ["/ˈbjuːtɪfl/", "美丽的", "A beautiful day."],
  "nice": ["/naɪs/", "好的/漂亮的", "Nice to meet you."],
  "clean": ["/kliːn/", "干净的", "A clean room."],
  "dirty": ["/ˈdɜːti/", "脏的", "Dirty hands."],
  "open": ["/ˈəʊpən/", "打开", "Open the box."],
  "close": ["/kləʊz/", "关闭", "Close your book."],
  "light": ["/laɪt/", "灯/光", "Turn on the light."],
  "dark": ["/dɑːk/", "黑暗的", "The room is dark."],
  "floor": ["/flɔː/", "地板", "Clean the floor."],
  "wall": ["/wɔːl/", "墙", "A picture on the wall."],
  "home": ["/həʊm/", "家", "Welcome home."],
  "phone": ["/fəʊn/", "电话", "Answer the phone."],
  "fridge": ["/frɪdʒ/", "冰箱", "Milk in the fridge."],
  "soup": ["/suːp/", "汤", "Hot soup."],
  "spoon": ["/spuːn/", "勺子", "A soup spoon."],
  "knife": ["/naɪf/", "刀", "A sharp knife."],
  "fork": ["/fɔːk/", "叉子", "A silver fork."],
  "bowl": ["/bəʊl/", "碗", "A rice bowl."],
  "chopsticks": ["/ˈtʃɒpstɪks/", "筷子", "Use chopsticks."],
  "cup": ["/kʌp/", "杯子", "A tea cup."],
  "glass": ["/ɡlɑːs/", "玻璃杯", "A glass of water."],
  "plate": ["/pleɪt/", "盘子", "A big plate."],
  "beef": ["/biːf/", "牛肉", "Yummy beef."],
  "bottle": ["/ˈbɒtl/", "瓶子", "A water bottle."],
  "box": ["/bɒks/", "盒子", "A toy box."],
  "cap": ["/kæp/", "帽子", "Put on your cap."],
  "hat": ["/hæt/", "帽子", "A sun hat."],
  "queen": ["/kwiːn/", "女王", "The queen smiles."],
  "king": ["/kɪŋ/", "国王", "A kind king."],
  "robot": ["/ˈrəʊbɒt/", "机器人", "A smart robot."],
  "puppy": ["/ˈpʌpi/", "小狗", "A cute puppy."],
  "kitten": ["/ˈkɪtn/", "小猫", "A little kitten."],
  "pig": ["/pɪɡ/", "猪", "A pink pig."],
  "sheep": ["/ʃiːp/", "绵羊", "White sheep."],
  "cow": ["/kaʊ/", "奶牛", "A milk cow."],
  "horse": ["/hɔːs/", "马", "A fast horse."],
  "hen": ["/hen/", "母鸡", "A hen lays eggs."],
  "rabbit": ["/ˈræbɪt/", "兔子", "A white rabbit."],
  "bear": ["/beə/", "熊", "A brown bear."],
  "mouse": ["/maʊs/", "老鼠", "A small mouse."],
  "eleven": ["/ɪˈlevn/", "十一", "Eleven birds."],
  "twelve": ["/twelv/", "十二", "Twelve months."],
  "thirteen": ["/ˌθɜːˈtiːn/", "十三", "Thirteen apples."],
  "fourteen": ["/ˌfɔːˈtiːn/", "十四", "Fourteen kites."],
  "fifteen": ["/ˌfɪfˈtiːn/", "十五", "Fifteen stars."],
  "sixteen": ["/ˌsɪksˈtiːn/", "十六", "Sixteen flowers."],
  "seventeen": ["/ˌsevnˈtiːn/", "十七", "Seventeen ducks."],
  "eighteen": ["/ˌeɪˈtiːn/", "十八", "Eighteen cars."],
  "nineteen": ["/ˌnaɪnˈtiːn/", "十九", "Nineteen balls."],
  "twenty": ["/ˈtwenti/", "二十", "Twenty pupils."],
  "student": ["/ˈstjuːdnt/", "学生", "A good student."],
  "classmate": ["/ˈklɑːsmeɪt/", "同学", "My classmate is kind."],

  // ============ 三年级上册 (PEP 3A: Hello/Colours/Look at me/Animals/Food/Birthday) ============
  "i'm": ["/aɪm/", "我是", "I'm Sam."],
  "crayon": ["/ˈkreɪɒn/", "蜡笔", "I have a red crayon."],
  "good morning": ["/ɡʊd ˈmɔːnɪŋ/", "早上好", "Good morning, Miss Li."],
  "this": ["/ðɪs/", "这", "This is my friend."],
  "miss": ["/mɪs/", "小姐/想念", "Good morning, Miss White."],
  "are": ["/ɑː/", "是", "How are you?"],
  "fine": ["/faɪn/", "好的/晴朗的", "I'm fine, thank you."],
  "thanks": ["/θæŋks/", "谢谢", "Thanks a lot."],
  "let's": ["/lets/", "让我们", "Let's go to school."],
  "go": ["/ɡəʊ/", "去", "Let's go!"],
  "to": ["/tuː/", "到/向", "Go to school."],
  "now": ["/naʊ/", "现在", "Now it's my turn."],
  "wow": ["/waʊ/", "哇", "Wow, so beautiful!"],
  "see": ["/siː/", "看见", "Nice to see you."],
  "say": ["/seɪ/", "说", "Say hello to Dad."],
  "uh": ["/ʌ/", "嗯", "Uh, let me see."],
  "great": ["/ɡreɪt/", "极好的", "Great job!"],
  "bye-bye": ["/ˈbaɪ baɪ/", "再见", "Bye-bye, everyone!"],
  "mr": ["/ˈmɪstə/", "先生", "Mr Jones, hello!"],
  "blue crayon": ["/bluː ˈkreɪɒn/", "蓝蜡笔", "I see a blue crayon."],
  "good afternoon": ["/ɡʊd ˌɑːftəˈnuːn/", "下午好", "Good afternoon, Mr Jones."],
  "nice to meet you": ["/naɪs tuː miːt juː/", "很高兴见到你", "Nice to meet you!"],
  "stand up": ["/stænd ʌp/", "起立", "Stand up, please."],
  "sit down": ["/sɪt daʊn/", "坐下", "Sit down, please."],
  "funny": ["/ˈfʌni/", "有趣的", "A funny clown."],
  "play with": ["/pleɪ wɪð/", "和……玩", "I play with my friends."],
  "real": ["/ˈrɪəl/", "真的", "It's a real dog!"],
  "have some": ["/hæv sʌm/", "吃一些", "Have some bread."],
  "i'd like": ["/aɪd laɪk/", "我想要", "I'd like some juice."],
  "here you are": ["/hɪə juː ɑː/", "给你", "Here you are!"],
  "thank you": ["/θæŋk juː/", "谢谢你", "Thank you very much."],
  "you're welcome": ["/jɔː ˈwelkəm/", "不客气", "You're welcome!"],
  "can i have some": ["/kæn aɪ hæv sʌm/", "我能吃些……吗", "Can I have some water?"],
  "how old are you": ["/haʊ əʊld ɑː juː/", "你几岁了", "How old are you?"],
  "make a wish": ["/meɪk ə wɪʃ/", "许愿", "Make a wish, Sam!"],
  "cut the cake": ["/kʌt ðə keɪk/", "切蛋糕", "Let's cut the cake."],
  "share": ["/ʃeə/", "分享", "Share your candy."],
  "eat": ["/iːt/", "吃", "Eat some fruit."],
  "drink": ["/drɪŋk/", "喝", "Drink some juice."],
  "taste": ["/teɪst/", "尝起来", "It tastes sweet."],
  "smell": ["/smel/", "闻", "Smell the flowers."],
  "touch": ["/tʌtʃ/", "摸", "Touch your head."],
  "animal": ["/ˈænɪml/", "动物", "I love animals."],
  "follow me": ["/ˈfɒləʊ miː/", "跟着我", "Follow me, please!"],

  // ============ 三年级下册 (PEP 3B: Welcome/Family/Animals/Positions/Fruits/Numbers) ============
  "welcome": ["/ˈwelkəm/", "欢迎", "Welcome to our school."],
  "welcome back": ["/ˈwelkəm bæk/", "欢迎回来", "Welcome back to school."],
  "she": ["/ʃiː/", "她", "She is my teacher."],
  "he": ["/hiː/", "他", "He is a student."],
  "today": ["/təˈdeɪ/", "今天", "Today is Monday."],
  "from": ["/frɒm/", "来自", "I'm from China."],
  "china": ["/ˈtʃaɪnə/", "中国", "I'm from China."],
  "uk": ["/ˌjuː ˈkeɪ/", "英国", "She is from the UK."],
  "usa": ["/ˌjuː es ˈeɪ/", "美国", "He is from the USA."],
  "canada": ["/ˈkænədə/", "加拿大", "Amy is from Canada."],
  "new friend": ["/njuː frend/", "新朋友", "We have a new friend."],
  "wait a minute": ["/weɪt ə ˈmɪnɪt/", "等一下", "Wait a minute!"],
  "how beautiful": ["/haʊ ˈbjuːtɪfl/", "多美啊", "How beautiful!"],
  "isn't": ["/ˈɪznt/", "不是", "This isn't my bag."],
  "family members": ["/ˈfæməli ˈmembəz/", "家庭成员", "Meet my family members."],
  "lovely": ["/ˈlʌvli/", "可爱的", "A lovely girl."],
  "so": ["/səʊ/", "如此/那么", "It's so tall!"],
  "children": ["/ˈtʃɪldrən/", "孩子们", "Children, look here."],
  "child": ["/tʃaɪld/", "儿童", "A happy child."],
  "tail": ["/teɪl/", "尾巴", "The monkey has a long tail."],
  "come here": ["/kʌm hɪə/", "过来", "Come here, children!"],
  "look at that": ["/lʊk æt ðæt/", "看那个", "Look at that panda."],
  "has": ["/hæz/", "有(第三人称)", "It has a long nose."],
  "hide": ["/haɪd/", "藏", "Hide and seek."],
  "find": ["/faɪnd/", "找到", "I can't find my pen."],
  "excuse me": ["/ɪkˈskjuːz miː/", "打扰一下", "Excuse me, where is the zoo?"],
  "silly": ["/ˈsɪli/", "傻乎乎的", "Don't be silly."],
  "honey": ["/ˈhʌni/", "蜂蜜/宝贝", "Honey, come here."],
  "how many": ["/haʊ ˈmeni/", "多少", "How many kites?"],
  "so many": ["/səʊ ˈmeni/", "这么多", "So many apples!"],
  "good idea": ["/ɡʊd aɪˈdɪə/", "好主意", "That's a good idea!"],
  "open it and see": ["/ˈəʊpən ɪt ənd siː/", "打开看看", "Open it and see!"],
  "live": ["/lɪv/", "居住", "Where do you live?"],
  "live in": ["/lɪv ɪn/", "住在", "I live in Beijing."],
  "for sale": ["/fɔː seɪl/", "出售", "Toys for sale."],
  "oh no": ["/əʊ nəʊ/", "哦不", "Oh no! My kite!"],

  // ============ 四年级上册 (PEP 4A: Classroom/Schoolbag/Friends/Home/Dinner/Family) ============
  "really": ["/ˈrɪəli/", "真的/的确", "It's really big."],
  "near": ["/nɪə/", "在……附近", "My home is near the park."],
  "tv": ["/ˌtiː ˈviː/", "电视", "Watch TV."],
  "clean the classroom": ["/kliːn ðə ˈklɑːsruːm/", "打扫教室", "Let's clean the classroom."],
  "let me": ["/let miː/", "让我", "Let me help you."],
  "schoolbag": ["/ˈskuːlbæɡ/", "书包", "My schoolbag is heavy."],
  "notebook": ["/ˈnəʊtbʊk/", "笔记本", "Write in your notebook."],
  "storybook": ["/ˈstɔːribʊk/", "故事书", "Read a storybook."],
  "key": ["/kiː/", "钥匙", "Where is my key?"],
  "wow so much": ["/waʊ səʊ mʌtʃ/", "哇这么多", "Wow, so much candy!"],
  "lost": ["/lɒst/", "丢失的", "My cat is lost."],
  "chinese book": ["/ˌtʃaɪˈniːz bʊk/", "语文书", "Where is my Chinese book?"],
  "english book": ["/ˈɪŋɡlɪʃ bʊk/", "英语书", "My English book is new."],
  "maths book": ["/mæθs bʊk/", "数学书", "I have a new maths book."],
  "quiet": ["/ˈkwaɪət/", "安静的", "Be quiet in the library."],
  "friendly": ["/ˈfrendli/", "友好的", "A friendly girl."],
  "glasses": ["/ˈɡlɑːsɪz/", "眼镜", "He wears glasses."],
  "his": ["/hɪz/", "他的", "His bag is blue."],
  "her": ["/hɜː/", "她的", "Her hair is long."],
  "or": ["/ɔː/", "还是/或者", "Is he tall or short?"],
  "shoe": ["/ʃuː/", "鞋子", "His shoes are new."],
  "strong": ["/strɒŋ/", "强壮的", "My dad is strong."],
  "bedroom": ["/ˈbedruːm/", "卧室", "This is my bedroom."],
  "living room": ["/ˈlɪvɪŋ ruːm/", "客厅", "Watch TV in the living room."],
  "kitchen": ["/ˈkɪtʃɪn/", "厨房", "Mum cooks in the kitchen."],
  "bathroom": ["/ˈbɑːθruːm/", "卫生间", "Take a shower in the bathroom."],
  "have a nap": ["/hæv ə næp/", "小睡一会", "Have a nap, dear."],
  "read a book": ["/riːd ə bʊk/", "读书", "Read a book in the study."],
  "take a shower": ["/teɪk ə ˈʃaʊə/", "洗澡", "Take a shower."],
  "watch tv": ["/wɒtʃ ˌtiː ˈviː/", "看电视", "I watch TV at night."],
  "are they": ["/ɑː ðeɪ/", "它们在吗", "Are they on the bed?"],
  "i'm hungry": ["/aɪm ˈhʌŋɡri/", "我饿了", "I'm hungry, Mum."],
  "what's for dinner": ["/wɒts fɔː ˈdɪnə/", "晚饭吃什么", "What's for dinner?"],
  "what would you like": ["/wɒt wʊd juː laɪk/", "你想吃什么", "What would you like for dinner?"],
  "help yourself": ["/help jɔːˈself/", "随便吃", "Help yourself to some fish."],
  "pass me the bowl": ["/pɑːs miː ðə bəʊl/", "递给我碗", "Pass me the bowl, please."],
  "cut the vegetables": ["/kʌt ðə ˈvedʒtəblz/", "切蔬菜", "Cut the vegetables."],
  "use the spoon": ["/juːz ðə spuːn/", "用勺子", "Use the spoon to eat soup."],
  "use the fork": ["/juːz ðə fɔːk/", "用叉子", "Use the fork to eat beef."],
  "ready": ["/ˈredi/", "准备好的", "Dinner is ready!"],
  "dinner's ready": ["/ˈdɪnəz ˈredi/", "晚饭好了", "Dinner's ready! Come on!"],
  "parents": ["/ˈpeərənts/", "父母", "My parents love me."],
  "uncle": ["/ˈʌŋkl/", "叔/舅/伯", "My uncle is a driver."],
  "aunt": ["/ɑːnt/", "婶/姑/姨", "My aunt is a nurse."],
  "baby brother": ["/ˈbeɪbi ˈbrʌðə/", "小弟弟", "My baby brother is cute."],
  "football player": ["/ˈfʊtbɔːl ˈpleɪə/", "足球运动员", "He is a football player."],
  "job": ["/dʒɒb/", "工作", "What's your father's job?"],
  "people": ["/ˈpiːpl/", "人们", "How many people are in your family?"],
  "but": ["/bʌt/", "但是", "He is short but strong."],
  "little": ["/ˈlɪtl/", "小的", "A little puppy."],
  "welcome to my home": ["/ˈwelkəm tuː maɪ həʊm/", "欢迎来我家", "Welcome to my home!"],
  "these are": ["/ðiːz ɑː/", "这些是", "These are my parents."],
  "my family has": ["/maɪ ˈfæməli hæz/", "我家有", "My family has six people."],
  "that's only": ["/ðæts ˈəʊnli/", "那只是", "That's only five."],
  "add": ["/æd/", "加上", "Add three and four."],

  // ============ 四年级下册 (PEP 4B: School/Time/Weather/Farm/Clothes/Shopping) ============
  "playground": ["/ˈpleɪɡraʊnd/", "操场", "Run on the playground."],
  "library": ["/ˈlaɪbrəri/", "图书馆", "Read books in the library."],
  "art room": ["/ɑːt ruːm/", "美术教室", "Draw in the art room."],
  "computer room": ["/kəmˈpjuːtə ruːm/", "微机室", "We play in the computer room."],
  "music room": ["/ˈmjuːzɪk ruːm/", "音乐教室", "Sing in the music room."],
  "first floor": ["/fɜːst flɔː/", "一楼", "It's on the first floor."],
  "second floor": ["/ˈsekənd flɔː/", "二楼", "The library is on the second floor."],
  "teachers' office": ["/ˈtiːtʃəz ˈɒfɪs/", "教师办公室", "Go to the teachers' office."],
  "welcome to our school": ["/ˈwelkəm tuː ˈaʊə skuːl/", "欢迎来到我们学校", "Welcome to our school!"],
  "this way please": ["/ðɪs weɪ pliːz/", "这边请", "This way, please."],
  "do you have": ["/duː juː hæv/", "你有……吗", "Do you have a library?"],
  "yes we do": ["/jes wiː duː/", "是的，有", "Yes, we do."],
  "no it isn't": ["/nəʊ ɪt ˈɪznt/", "不，不是", "No, it isn't."],
  "what time is it": ["/wɒt taɪm ɪz ɪt/", "几点了", "What time is it now?"],
  "it's 7 o'clock": ["/ɪts ˈsevn əˈklɒk/", "七点了", "It's 7 o'clock."],
  "english class": ["/ˈɪŋɡlɪʃ klɑːs/", "英语课", "It's time for English class."],
  "music class": ["/ˈmjuːzɪk klɑːs/", "音乐课", "Time for music class."],
  "pe class": ["/ˌpiː ˈiː klɑːs/", "体育课", "I love PE class."],
  "it's time for": ["/ɪts taɪm fɔː/", "到……的时间了", "It's time for lunch."],
  "it's time to get up": ["/ɪts taɪm tuː ɡet ʌp/", "该起床了", "It's time to get up."],
  "it's time to go to school": ["/ɪts taɪm tuː ɡəʊ tuː skuːl/", "该上学了", "It's time to go to school."],
  "it's time to go home": ["/ɪts taɪm tuː ɡəʊ həʊm/", "该回家了", "It's time to go home."],
  "it's time to go to bed": ["/ɪts taɪm tuː ɡəʊ tuː bed/", "该睡觉了", "It's time to go to bed."],
  "just a minute": ["/dʒʌst ə ˈmɪnɪt/", "稍等一会", "Just a minute, Mum."],
  "over there": ["/ˈəʊvə ðeə/", "在那边", "The gym is over there."],
  "school starts at": ["/skuːl stɑːts æt/", "学校几点开始上课", "School starts at 8 o'clock."],
  "am": ["/ˌeɪ ˈem/", "上午", "I get up at 6:30 am."],
  "pm": ["/ˌpiː ˈem/", "下午", "We go home at 4:30 pm."],
  "cold outside": ["/kəʊld ˌaʊtˈsaɪd/", "外面很冷", "It's cold outside."],
  "be careful": ["/biː ˈkeəfl/", "小心", "Be careful! The soup is hot."],
  "weather report": ["/ˈweðə rɪˈpɔːt/", "天气预报", "Watch the weather report."],
  "what's the weather like": ["/wɒts ðə ˈweðə laɪk/", "天气怎么样", "What's the weather like today?"],
  "it's rainy today": ["/ɪts ˈreɪni təˈdeɪ/", "今天下雨", "It's rainy today."],
  "not much": ["/nɒt mʌtʃ/", "没什么", "Not much."],
  "how about": ["/haʊ əˈbaʊt/", "……怎么样", "How about Beijing?"],
  "degree": ["/dɪˈɡriː/", "度", "It's 26 degrees."],
  "world": ["/wɜːld/", "世界", "The weather around the world."],
  "tomato": ["/təˈmɑːtəʊ/", "西红柿", "Red tomatoes."],
  "potato": ["/pəˈteɪtəʊ/", "土豆", "Big potatoes."],
  "green beans": ["/ɡriːn biːnz/", "豆角", "Crispy green beans."],
  "carrot": ["/ˈkærət/", "胡萝卜", "Rabbits love carrots."],
  "farm": ["/fɑːm/", "农场", "Animals on the farm."],
  "these": ["/ðiːz/", "这些", "These are tomatoes."],
  "those": ["/ðəʊz/", "那些", "Those are carrots."],
  "garden": ["/ˈɡɑːdn/", "花园", "Flowers in the garden."],
  "eat up": ["/iːt ʌp/", "吃光", "Eat up your vegetables."],
  "clothes": ["/kləʊðz/", "衣服", "My clothes are new."],
  "pants": ["/pænts/", "裤子", "My pants are blue."],
  "whose": ["/huːz/", "谁的", "Whose cap is this?"],
  "sock": ["/sɒk/", "袜子", "A red sock."],
  "whose coat is this": ["/huːz kəʊt ɪz ðɪs/", "这是谁的大衣", "Whose coat is this?"],
  "it's mine": ["/ɪts maɪn/", "它是我的", "It's mine, thank you."],
  "they're my father's": ["/ðeə maɪ ˈfɑːðəz/", "它们是我爸爸的", "They're my father's."],
  "put away": ["/pʊt əˈweɪ/", "收起来", "Put away your clothes."],
  "put on": ["/pʊt ɒn/", "穿上", "Put on your sweater."],
  "take off": ["/teɪk ɒf/", "脱下", "Take off your shoes."],
  "hang up": ["/hæŋ ʌp/", "挂起来", "Hang up your dress."],
  "wash": ["/wɒʃ/", "洗", "Wash your hands."],
  "umbrella": ["/ʌmˈbrelə/", "雨伞", "Take an umbrella."],
  "sunglasses": ["/ˈsʌnɡlɑːsɪz/", "太阳镜", "Cool sunglasses."],
  "scarf": ["/skɑːf/", "围巾", "A red scarf."],
  "gloves": ["/ɡlʌvz/", "手套", "Warm gloves."],
  "how much is it": ["/haʊ mʌtʃ ɪz ɪt/", "多少钱", "How much is it?"],
  "i'll take it": ["/aɪl teɪk ɪt/", "我买了", "It's pretty. I'll take it."],
  "size": ["/saɪz/", "尺码", "Size 6, please."],
  "of course": ["/əv kɔːs/", "当然", "Of course you can."],
  "too": ["/tuː/", "太/也", "It's too big."],
  "more": ["/mɔː/", "更多的", "One more, please."],
  "assistant": ["/əˈsɪstənt/", "店员", "The assistant is kind."],

  // ============ 五年级上册 (PEP 5A: Teachers/Week/Food/Abilities/Room/Nature Park) ============
  "young": ["/jʌŋ/", "年轻的", "A young teacher."],
  "kind": ["/kaɪnd/", "和蔼的", "A kind grandma."],
  "strict": ["/strɪkt/", "严格的", "A strict teacher."],
  "polite": ["/pəˈlaɪt/", "有礼貌的", "Be polite to others."],
  "hard-working": ["/ˌhɑːd ˈwɜːkɪŋ/", "勤劳的", "A hard-working pupil."],
  "helpful": ["/ˈhelpfl/", "乐于助人的", "A helpful boy."],
  "clever": ["/ˈklevə/", "聪明的", "A clever girl."],
  "shy": ["/ʃaɪ/", "害羞的", "A shy rabbit."],
  "ms": ["/ˌem ˈes/", "女士", "Ms Green is our teacher."],
  "will": ["/wɪl/", "将要", "I will help you."],
  "sometimes": ["/ˈsʌmtaɪmz/", "有时", "Sometimes I read at night."],
  "our": ["/ˈaʊə/", "我们的", "This is our school."],
  "head teacher": ["/hed ˈtiːtʃə/", "校长", "Our head teacher is kind."],
  "very hard": ["/ˈveri hɑːd/", "非常努力", "He works very hard."],
  "is he strict": ["/ɪz hiː strɪkt/", "他严格吗", "Is he strict?"],
  "he's very kind": ["/hiːz ˈveri kaɪnd/", "他很和蔼", "He's very kind."],
  "monday": ["/ˈmʌndeɪ/", "星期一", "We have PE on Monday."],
  "tuesday": ["/ˈtjuːzdeɪ/", "星期二", "Music class is on Tuesday."],
  "wednesday": ["/ˈwenzdeɪ/", "星期三", "Wednesday is art day."],
  "thursday": ["/ˈθɜːzdeɪ/", "星期四", "Thursday is science day."],
  "friday": ["/ˈfraɪdeɪ/", "星期五", "Happy Friday!"],
  "saturday": ["/ˈsætədeɪ/", "星期六", "Play on Saturday."],
  "sunday": ["/ˈsʌndeɪ/", "星期日", "Sunday is family day."],
  "weekend": ["/ˌwiːkˈend/", "周末", "Enjoy the weekend."],
  "wash my clothes": ["/wɒʃ maɪ kləʊðz/", "洗衣服", "I wash my clothes."],
  "do homework": ["/duː ˈhəʊmwɜːk/", "做作业", "I do homework every day."],
  "read books": ["/riːd bʊks/", "读书", "I read books at night."],
  "play football": ["/pleɪ ˈfʊtbɔːl/", "踢足球", "Let's play football."],
  "often": ["/ˈɒfn/", "经常", "I often play sports."],
  "do you often": ["/duː juː ˈɒfn/", "你经常……吗", "Do you often read here?"],
  "tired": ["/ˈtaɪəd/", "疲劳的", "I am tired today."],
  "sport": ["/spɔːt/", "体育运动", "Play a sport."],
  "should": ["/ʃʊd/", "应该", "You should sleep early."],
  "every day": ["/ˈevri deɪ/", "每天", "Read every day."],
  "schedule": ["/ˈʃedjuːl/", "日程表", "Look at my schedule."],
  "sandwich": ["/ˈsænwɪtʃ/", "三明治", "A ham sandwich."],
  "salad": ["/ˈsæləd/", "沙拉", "Fruit salad is sweet."],
  "ice cream": ["/aɪs kriːm/", "冰淇淋", "Vanilla ice cream."],
  "fresh": ["/freʃ/", "新鲜的", "Fresh vegetables."],
  "healthy": ["/ˈhelθi/", "健康的", "Healthy food is good."],
  "delicious": ["/dɪˈlɪʃəs/", "美味的", "What delicious food!"],
  "favourite": ["/ˈfeɪvərɪt/", "最喜欢的", "My favourite food is fish."],
  "what's your favourite": ["/wɒts jɔː ˈfeɪvərɪt/", "你最喜欢什么", "What's your favourite food?"],
  "they're sweet": ["/ðeə swiːt/", "它们很甜", "They're sweet."],
  "beef noodles": ["/biːf ˈnuːdlz/", "牛肉面", "Beef noodles smell good."],
  "fish sandwich": ["/fɪʃ ˈsænwɪtʃ/", "鱼肉三明治", "A fish sandwich, please."],
  "tomato soup": ["/təˈmɑːtəʊ suːp/", "番茄汤", "Tomato soup is healthy."],
  "potatoes": ["/pəˈteɪtəʊz/", "土豆", "Mashed potatoes."],
  "cabbage": ["/ˈkæbɪdʒ/", "卷心菜", "Green cabbage."],
  "green tea": ["/ɡriːn tiː/", "绿茶", "Hot green tea."],
  "sing english songs": ["/sɪŋ ˈɪŋɡlɪʃ sɒŋz/", "唱英文歌", "I can sing English songs."],
  "do kung fu": ["/duː kʌŋ ˈfuː/", "练功夫", "I can do kung fu."],
  "play the pipa": ["/pleɪ ðə ˈpiːpɑː/", "弹琵琶", "She can play the pipa."],
  "draw cartoons": ["/drɔː kɑːˈtuːnz/", "画漫画", "I can draw cartoons."],
  "play basketball": ["/pleɪ ˈbɑːskɪtbɔːl/", "打篮球", "We play basketball together."],
  "play ping-pong": ["/pleɪ ˈpɪŋ pɒŋ/", "打乒乓球", "I play ping-pong well."],
  "speak english": ["/spiːk ˈɪŋɡlɪʃ/", "说英语", "Can you speak English?"],
  "what can you do": ["/wɒt kæn juː duː/", "你会做什么", "What can you do at home?"],
  "kung fu": ["/ˌkʌŋ ˈfuː/", "功夫", "Chinese kung fu is cool."],
  "front": ["/frʌnt/", "前面", "In front of the house."],
  "between": ["/bɪˈtwiːn/", "在……中间", "Between two trees."],
  "above": ["/əˈbʌv/", "在……上方", "The light is above me."],
  "beside": ["/bɪˈsaɪd/", "在……旁边", "Beside the door."],
  "behind": ["/bɪˈhaɪnd/", "在……后面", "Behind the sofa."],
  "there is": ["/ðeə ɪz/", "有(单数)", "There is a big bed."],
  "there are": ["/ðeə ɑː/", "有(复数)", "There are two photos."],
  "in my room": ["/ɪn maɪ ruːm/", "在我房间里", "In my room there is a bed."],
  "my room": ["/maɪ ruːm/", "我的房间", "My room is nice."],
  "water bottle": ["/ˈwɔːtə ˈbɒtl/", "水瓶", "My water bottle is blue."],
  "so many plants": ["/səʊ ˈmeni plɑːnts/", "这么多植物", "So many plants here!"],
  "move into": ["/muːv ˈɪntuː/", "搬进", "We move into a new house."],
  "forest": ["/ˈfɒrɪst/", "森林", "A green forest."],
  "river": ["/ˈrɪvə/", "河流", "A clean river."],
  "mountain": ["/ˈmaʊntən/", "高山", "A high mountain."],
  "bridge": ["/brɪdʒ/", "桥", "An old bridge."],
  "building": ["/ˈbɪldɪŋ/", "建筑物", "A tall building."],
  "village": ["/ˈvɪlɪdʒ/", "村庄", "A small village."],
  "house": ["/haʊs/", "房子", "My house is small."],
  "go boating": ["/ɡəʊ ˈbəʊtɪŋ/", "去划船", "Let's go boating."],
  "aren't": ["/ɑːnt/", "不是", "There aren't any lakes."],
  "nature park": ["/ˈneɪtʃə pɑːk/", "自然公园", "Let's go to the nature park."],
  "on the mountain": ["/ɒn ðə ˈmaʊntən/", "在山上", "There is a house on the mountain."],
  "under the tree": ["/ˈʌndə ðə triː/", "在树下", "There is a dog under the tree."],
  "no people": ["/nəʊ ˈpiːpl/", "没有人", "There are no people."],
  "high": ["/haɪ/", "高的", "The mountain is high."],

  // ============ 五年级下册 (PEP 5B: Day/Seasons/Calendar/Date/Animals/Work) ============
  "do morning exercises": ["/duː ˈmɔːnɪŋ ˈeksəsaɪzɪz/", "做早操", "I do morning exercises at 7."],
  "eat breakfast": ["/iːt ˈbrekfəst/", "吃早饭", "I eat breakfast at home."],
  "have class": ["/hæv klɑːs/", "上课", "We have class at 8."],
  "play sports": ["/pleɪ spɔːts/", "进行体育活动", "I play sports at 4."],
  "eat dinner": ["/iːt ˈdɪnə/", "吃晚饭", "We eat dinner at 6."],
  "when": ["/wen/", "什么时候", "When do you get up?"],
  "exercise": ["/ˈeksəsaɪz/", "锻炼", "Exercise every day."],
  "usually": ["/ˈjuːʒuəli/", "通常", "I usually go to school at 7."],
  "noon": ["/nuːn/", "中午", "I eat lunch at noon."],
  "o'clock": ["/əˈklɒk/", "……点钟", "It's 6 o'clock."],
  "why": ["/waɪ/", "为什么", "Why do you like spring?"],
  "start": ["/stɑːt/", "开始", "Class starts at 8."],
  "sound": ["/saʊnd/", "听起来", "That sounds fun."],
  "take a dancing class": ["/teɪk ə ˈdɑːnsɪŋ klɑːs/", "上舞蹈课", "I take a dancing class."],
  "dancing": ["/ˈdɑːnsɪŋ/", "跳舞", "Dancing makes me happy."],
  "last": ["/lɑːst/", "上一个", "Last weekend was fun."],
  "also": ["/ˈɔːlsəʊ/", "还/也", "I also like music."],
  "busy": ["/ˈbɪzi/", "繁忙的", "I am busy today."],
  "need": ["/niːd/", "需要", "I need your help."],
  "play music": ["/pleɪ ˈmjuːzɪk/", "演奏音乐", "I play music with friends."],
  "go for a walk": ["/ɡəʊ fɔːr ə wɔːk/", "去散步", "I go for a walk after dinner."],
  "go shopping": ["/ɡəʊ ˈʃɒpɪŋ/", "去买东西", "Let's go shopping."],
  "clean my room": ["/kliːn maɪ ruːm/", "打扫房间", "I clean my room on Saturday."],
  "take": ["/teɪk/", "学习/上(课)", "I take an art class."],
  "pick apples": ["/pɪk ˈæplz/", "摘苹果", "We pick apples in autumn."],
  "go swimming": ["/ɡəʊ ˈswɪmɪŋ/", "去游泳", "I go swimming in summer."],
  "which": ["/wɪtʃ/", "哪一个", "Which season do you like?"],
  "best": ["/best/", "最", "I like spring best."],
  "because": ["/bɪˈkɒz/", "因为", "Because it's warm."],
  "vacation": ["/vəˈkeɪʃn/", "假期", "Summer vacation is fun."],
  "leaf": ["/liːf/", "叶子", "A green leaf."],
  "leaves": ["/liːvz/", "树叶(复数)", "Colourful leaves in autumn."],
  "colourful": ["/ˈkʌləfl/", "多彩的", "Colourful flowers."],
  "paint a picture": ["/peɪnt ə ˈpɪktʃə/", "画画", "I paint a picture in autumn."],
  "merry": ["/ˈmeri/", "快乐的", "Merry Christmas!"],
  "summer is here": ["/ˈsʌmə ɪz hɪə/", "夏天到了", "Summer is here!"],
  "january": ["/ˈdʒænjuəri/", "一月", "January is the first month."],
  "february": ["/ˈfebruəri/", "二月", "February is short."],
  "march": ["/mɑːtʃ/", "三月", "March brings spring."],
  "april": ["/ˈeɪprəl/", "四月", "April showers bring flowers."],
  "may": ["/meɪ/", "五月", "May is a warm month."],
  "june": ["/dʒuːn/", "六月", "June 1st is Children's Day."],
  "july": ["/dʒuːˈlaɪ/", "七月", "July is hot."],
  "august": ["/ˈɔːɡəst/", "八月", "August is my birthday month."],
  "september": ["/sepˈtembə/", "九月", "September 10th is Teachers' Day."],
  "october": ["/ɒkˈtəʊbə/", "十月", "October 1st is our National Day."],
  "november": ["/nəʊˈvembə/", "十一月", "November is cool."],
  "december": ["/dɪˈsembə/", "十二月", "December has snow."],
  "few": ["/fjuː/", "很少", "A few apples."],
  "thing": ["/θɪŋ/", "事情", "A fun thing to do."],
  "meet": ["/miːt/", "聚会/见面", "Sports meet is in May."],
  "chinese test": ["/ˌtʃaɪˈniːz test/", "语文考试", "We have a Chinese test."],
  "sports meet": ["/spɔːts miːt/", "运动会", "The sports meet is fun."],
  "easter": ["/ˈiːstə/", "复活节", "Easter is in April."],
  "trip": ["/trɪp/", "旅行", "A school trip in autumn."],
  "year": ["/jɪə/", "年", "Happy New Year!"],
  "month": ["/mʌnθ/", "月份", "Which month is it?"],
  "first": ["/fɜːst/", "第一", "January is the first month."],
  "second": ["/ˈsekənd/", "第二", "February is the second month."],
  "third": ["/θɜːd/", "第三", "March is the third month."],
  "fourth": ["/fɔːθ/", "第四", "April is the fourth month."],
  "fifth": ["/fɪfθ/", "第五", "May is the fifth month."],
  "twelfth": ["/twelfθ/", "第十二", "December is the twelfth month."],
  "twentieth": ["/ˈtwentiəθ/", "第二十", "My birthday is on the twentieth."],
  "twenty-first": ["/ˈtwenti fɜːst/", "第二十一", "Today is October 21st."],
  "thirtieth": ["/ˈθɜːtiəθ/", "第三十", "April 30th is his birthday."],
  "special": ["/ˈspeʃl/", "特别的", "A special day."],
  "fool": ["/fuːl/", "傻瓜", "April Fools' Day is fun."],
  "date": ["/deɪt/", "日期", "What's the date today?"],
  "birthday party": ["/ˈbɜːθdeɪ ˈpɑːti/", "生日聚会", "I will have a birthday party."],
  "playing": ["/ˈpleɪɪŋ/", "玩耍(现在分词)", "The dog is playing."],
  "jumping": ["/ˈdʒʌmpɪŋ/", "跳(现在分词)", "The rabbit is jumping."],
  "eating": ["/ˈiːtɪŋ/", "吃(现在分词)", "The panda is eating bamboo."],
  "drinking": ["/ˈdrɪŋkɪŋ/", "喝(现在分词)", "The cat is drinking water."],
  "sleeping": ["/ˈsliːpɪŋ/", "睡觉(现在分词)", "The baby is sleeping."],
  "running": ["/ˈrʌnɪŋ/", "跑(现在分词)", "The horses are running."],
  "climbing": ["/ˈklaɪmɪŋ/", "爬(现在分词)", "The monkey is climbing."],
  "swinging": ["/ˈswɪŋɪŋ/", "荡秋千(现在分词)", "The monkeys are swinging."],
  "fighting": ["/ˈfaɪtɪŋ/", "打架(现在分词)", "Stop fighting, boys!"],
  "mine": ["/maɪn/", "我的", "The dog is mine."],
  "yours": ["/jɔːz/", "你的", "Is this book yours?"],
  "hers": ["/hɜːz/", "她的", "The dress is hers."],
  "theirs": ["/ðeəz/", "他们的", "The toys are theirs."],
  "ours": ["/ˈaʊəz/", "我们的", "The classroom is ours."],
  "each other": ["/iːtʃ ˈʌðə/", "互相", "We help each other."],
  "care for": ["/keə fɔː/", "爱护", "Care for the animals."],
  "look there": ["/lʊk ðeə/", "看那里", "Look there! Monkeys!"],
  "drinking water": ["/ˈdrɪŋkɪŋ ˈwɔːtə/", "在喝水", "The elephant is drinking water."],
  "so cute": ["/səʊ kjuːt/", "真可爱", "The panda is so cute."],
  "what are they doing": ["/wɒt ɑː ðeɪ ˈduːɪŋ/", "它们在做什么", "What are they doing?"],
  "having class": ["/ˈhævɪŋ klɑːs/", "在上课", "We are having an English class."],
  "eating lunch": ["/ˈiːtɪŋ lʌntʃ/", "在吃午饭", "They are eating lunch."],
  "reading a book": ["/ˈriːdɪŋ ə bʊk/", "在读书", "She is reading a book."],
  "listening to music": ["/ˈlɪsnɪŋ tuː ˈmjuːzɪk/", "在听音乐", "He is listening to music."],
  "keep to the right": ["/kiːp tuː ðə raɪt/", "靠右", "Keep to the right, please."],
  "keep your desk clean": ["/kiːp jɔː desk kliːn/", "保持桌面整洁", "Keep your desk clean."],
  "talk quietly": ["/tɔːk ˈkwaɪətli/", "小声说话", "Talk quietly in the library."],
  "take turns": ["/teɪk tɜːnz/", "按顺序来", "Take turns to play."],
  "quietly": ["/ˈkwaɪətli/", "安静地", "Walk quietly."],
  "show": ["/ʃəʊ/", "给……看", "Show me your photo."],
  "anything else": ["/ˈeniθɪŋ els/", "还有别的吗", "Anything else?"],
  "exhibition": ["/ˌeksɪˈbɪʃn/", "展览", "See the robot exhibition."],
  "say no to": ["/seɪ nəʊ tuː/", "对……说不", "Say no to bad habits."],
  "look for": ["/lʊk fɔː/", "寻找", "I'm looking for my cat."],

  // ============ 六年级上册 (PEP 6A: Directions/Ways/Plans/Pen Pals/Jobs/Feelings) ============
  "science museum": ["/ˈsaɪəns mjuˈziːəm/", "科学博物馆", "Visit the science museum."],
  "post office": ["/ˈpəʊst ɒfɪs/", "邮局", "Mail a letter at the post office."],
  "bookstore": ["/ˈbʊkstɔː/", "书店", "Buy books in the bookstore."],
  "crossing": ["/ˈkrɒsɪŋ/", "十字路口", "Turn left at the crossing."],
  "turn left": ["/tɜːn left/", "向左转", "Turn left at the school."],
  "turn right": ["/tɜːn raɪt/", "向右转", "Turn right at the park."],
  "go straight": ["/ɡəʊ streɪt/", "直行", "Go straight for 5 minutes."],
  "next to": ["/nekst tuː/", "紧挨着", "The zoo is next to the park."],
  "far": ["/fɑː/", "远的", "Is it far from here?"],
  "tell": ["/tel/", "告诉", "Tell me the way."],
  "gps": ["/ˌdʒiː piː ˈes/", "全球定位系统", "Use the GPS to find it."],
  "follow": ["/ˈfɒləʊ/", "跟随", "Follow me, please."],
  "feature": ["/ˈfiːtʃə/", "特点", "The feature of the city."],
  "italian restaurant": ["/ɪˈtæliən ˈrestrɒnt/", "意大利餐馆", "An Italian restaurant nearby."],
  "get there": ["/ɡet ðeə/", "到达那里", "How can we get there?"],
  "get to": ["/ɡet tuː/", "到达", "How do you get to school?"],
  "on foot": ["/ɒn fʊt/", "步行", "I go on foot."],
  "by bus": ["/baɪ bʌs/", "乘公交", "I go by bus."],
  "by taxi": ["/baɪ ˈtæksi/", "乘出租车", "Go by taxi."],
  "by subway": ["/baɪ ˈsʌbweɪ/", "乘地铁", "I go by subway."],
  "by train": ["/baɪ treɪn/", "乘火车", "We go by train."],
  "by ship": ["/baɪ ʃɪp/", "乘轮船", "Go by ship."],
  "by plane": ["/baɪ pleɪn/", "乘飞机", "They go by plane."],
  "by bike": ["/baɪ baɪk/", "骑自行车", "I go by bike."],
  "slow down": ["/sləʊ daʊn/", "减速", "Slow down and stop."],
  "stop and wait": ["/stɒp ənd weɪt/", "停下来等待", "Stop and wait at a red light."],
  "traffic lights": ["/ˈtræfɪk laɪts/", "交通信号灯", "Look at the traffic lights."],
  "helmet": ["/ˈhelmɪt/", "头盔", "Wear a helmet on a bike."],
  "must": ["/mʌst/", "必须", "You must stop."],
  "wear": ["/weə/", "穿戴", "Wear your helmet."],
  "pay attention to": ["/peɪ əˈtenʃn tuː/", "注意", "Pay attention to the cars."],
  "traffic": ["/ˈtræfɪk/", "交通", "Look out for the traffic."],
  "munich": ["/ˈmjuːnɪk/", "慕尼黑", "Munich is in Germany."],
  "germany": ["/ˈdʒɜːməni/", "德国", "Some children are from Germany."],
  "alaska": ["/əˈlæskə/", "阿拉斯加", "It snows in Alaska."],
  "sled": ["/sled/", "雪橇", "They go by sled."],
  "ferry": ["/ˈferi/", "渡轮", "Go by ferry."],
  "scotland": ["/ˈskɒtlənd/", "苏格兰", "The ferry goes to Scotland."],
  "so many ways": ["/səʊ ˈmeni weɪz/", "这么多方式", "So many ways to go to school."],
  "on a sled": ["/ɒn ə sled/", "坐雪橇", "They go to school on a sled."],
  "visit": ["/ˈvɪzɪt/", "拜访/参观", "Visit my grandparents."],
  "film": ["/fɪlm/", "电影", "See a film tonight."],
  "see a film": ["/siː ə fɪlm/", "看电影", "Let's see a film."],
  "take a trip": ["/teɪk ə trɪp/", "去旅行", "Take a trip to Beijing."],
  "evening": ["/ˈiːvnɪŋ/", "傍晚", "This evening is free."],
  "tonight": ["/təˈnaɪt/", "今晚", "What are you doing tonight?"],
  "tomorrow": ["/təˈmɒrəʊ/", "明天", "Tomorrow is Monday."],
  "next week": ["/nekst wiːk/", "下周", "See you next week."],
  "dictionary": ["/ˈdɪkʃənri/", "词典", "A Chinese-English dictionary."],
  "comic book": ["/ˈkɒmɪk bʊk/", "漫画书", "Read a comic book."],
  "word book": ["/wɜːd bʊk/", "单词本", "Write in my word book."],
  "postcard": ["/ˈpəʊstkɑːd/", "明信片", "Send a postcard."],
  "mid-autumn festival": ["/ˌmɪd ˈɔːtəm ˈfestɪvl/", "中秋节", "The Mid-Autumn Festival is coming."],
  "mooncake": ["/ˈmuːnkeɪk/", "月饼", "We eat mooncakes."],
  "poem": ["/ˈpəʊɪm/", "诗", "Read a poem about the moon."],
  "together": ["/təˈɡeðə/", "一起", "We get together."],
  "get together": ["/ɡet təˈɡeðə/", "聚会", "Family get together."],
  "puzzle": ["/ˈpʌzl/", "谜/拼图", "Do word puzzles."],
  "hiking": ["/ˈhaɪkɪŋ/", "远足", "Go hiking on Sunday."],
  "pen pal": ["/pen pæl/", "笔友", "I have a pen pal."],
  "jasmine flower": ["/ˈdʒæsmɪn ˈflaʊə/", "茉莉花", "The jasmine flower smells nice."],
  "idea": ["/aɪˈdɪə/", "主意", "Good idea!"],
  "canberra": ["/ˈkænbərə/", "堪培拉", "My pen pal lives in Canberra."],
  "amazing": ["/əˈmeɪzɪŋ/", "令人惊叹的", "That's amazing!"],
  "shall": ["/ʃæl/", "将要/好吗", "Shall we dance?"],
  "goal": ["/ɡəʊl/", "射门/目标", "Kick a goal!"],
  "join": ["/dʒɔɪn/", "加入", "Join our club."],
  "club": ["/klʌb/", "俱乐部", "The football club."],
  "factory worker": ["/ˈfæktri ˈwɜːkə/", "工厂工人", "My aunt is a factory worker."],
  "postman": ["/ˈpəʊstmən/", "邮递员", "The postman brings letters."],
  "businessman": ["/ˈbɪznɪsmæn/", "商人", "A rich businessman."],
  "police officer": ["/pəˈliːs ˈɒfɪsə/", "警察", "The police officer helps us."],
  "fisherman": ["/ˈfɪʃəmən/", "渔民", "The fisherman catches fish."],
  "scientist": ["/ˈsaɪəntɪst/", "科学家", "The scientist works hard."],
  "pilot": ["/ˈpaɪlət/", "飞行员", "The pilot flies planes."],
  "coach": ["/kəʊtʃ/", "教练", "Our coach is strict."],
  "country": ["/ˈkʌntri/", "国家", "A beautiful country."],
  "sea": ["/siː/", "大海", "The sea is blue."],
  "stay healthy": ["/steɪ ˈhelθi/", "保持健康", "Stay healthy every day."],
  "university": ["/ˌjuːnɪˈvɜːsəti/", "大学", "My sister goes to university."],
  "if": ["/ɪf/", "如果", "If you like it, do it."],
  "use": ["/juːz/", "使用", "Use the computer."],
  "type": ["/taɪp/", "打字", "Type quickly."],
  "quickly": ["/ˈkwɪkli/", "迅速地", "Run quickly!"],
  "angry": ["/ˈæŋɡri/", "生气的", "Don't be angry."],
  "afraid": ["/əˈfreɪd/", "害怕的", "Don't be afraid."],
  "worried": ["/ˈwʌrid/", "担心的", "Mum is worried about me."],
  "see a doctor": ["/siː ə ˈdɒktə/", "看病", "You should see a doctor."],
  "wear warm clothes": ["/weə wɔːm kləʊðz/", "穿暖和的衣服", "Wear warm clothes."],
  "take a deep breath": ["/teɪk ə diːp breθ/", "深吸一口气", "Take a deep breath."],
  "count to ten": ["/kaʊnt tuː ten/", "数到十", "Count to ten and relax."],
  "chase": ["/tʃeɪs/", "追赶", "The cat chases the mouse."],
  "mice": ["/maɪs/", "老鼠(复数)", "The cat chases the mice."],
  "bad": ["/bæd/", "坏的", "Bad weather today."],
  "hurt": ["/hɜːt/", "受伤", "My leg hurts."],
  "ill": ["/ɪl/", "有病的", "I feel ill."],
  "wrong": ["/rɒŋ/", "有毛病的/错误的", "What's wrong?"],
  "feel": ["/fiːl/", "感觉", "How do you feel?"],
  "well": ["/wel/", "健康的", "I don't feel well."],
  "sit": ["/sɪt/", "坐", "Sit on the grass."],
  "hear": ["/hɪə/", "听见", "I hear a bird."],
  "everyone": ["/ˈevriwʌn/", "每个人", "Everyone is happy."],
  "mud": ["/mʌd/", "泥", "Don't play in the mud."],
  "pull": ["/pʊl/", "拉", "Let's pull it out."],
  "what's wrong": ["/wɒts rɒŋ/", "怎么了", "What's wrong, Mum?"],
  "how does dad feel": ["/haʊ dʌz dæd fiːl/", "爸爸感觉怎么样", "How does Dad feel now?"],
  "not well": ["/nɒt wel/", "不舒服", "He is not well."],
  "go to the zoo": ["/ɡəʊ tuː ðə zuː/", "去动物园", "Let's go to the zoo."],
  "not really": ["/nɒt ˈrɪəli/", "不怎么", "Not really."],
  "run after": ["/rʌn ˈɑːftə/", "追赶", "The dog runs after the cat."],
  "look so sad": ["/lʊk səʊ sæd/", "看起来很伤心", "Why do you look so sad?"],

  // ============ 六年级下册 (PEP 6B: Comparisons/Last weekend/Holiday/Then and now) ============
  "younger": ["/ˈjʌŋɡə/", "更年轻的", "My sister is younger."],
  "older": ["/ˈəʊldə/", "年龄更大的", "My brother is older."],
  "taller": ["/ˈtɔːlə/", "更高的", "The tree is taller."],
  "shorter": ["/ˈʃɔːtə/", "更矮的/更短的", "This ruler is shorter."],
  "longer": ["/ˈlɒŋɡə/", "更长的", "The snake is longer."],
  "thinner": ["/ˈθɪnə/", "更瘦的", "He is thinner than me."],
  "heavier": ["/ˈheviə/", "更重的", "The elephant is heavier."],
  "bigger": ["/ˈbɪɡə/", "更大的", "A bigger apple."],
  "smaller": ["/ˈsmɔːlə/", "更小的", "A smaller box."],
  "stronger": ["/ˈstrɒŋɡə/", "更强壮的", "Dad is stronger."],
  "dinosaur": ["/ˈdaɪnəsɔː/", "恐龙", "A big dinosaur."],
  "hall": ["/hɔːl/", "大厅", "The dinosaurs are in the hall."],
  "meter": ["/ˈmiːtə/", "米", "It's 5 meters tall."],
  "than": ["/ðæn/", "比", "I'm taller than you."],
  "both": ["/bəʊθ/", "两个都", "We both like sports."],
  "kilogram": ["/ˈkɪləɡræm/", "千克", "It weighs 100 kilograms."],
  "countryside": ["/ˈkʌntrisaɪd/", "乡村", "My grandma lives in the countryside."],
  "lower": ["/ˈləʊə/", "更低的", "The sun is lower."],
  "shadow": ["/ˈʃædəʊ/", "影子", "My shadow is long."],
  "smarter": ["/ˈsmɑːtə/", "更聪明的", "The dog is smarter."],
  "become": ["/bɪˈkʌm/", "变成", "I want to become a pilot."],
  "cleaned my room": ["/kliːnd maɪ ruːm/", "打扫了我的房间", "I cleaned my room."],
  "washed my clothes": ["/wɒʃt maɪ kləʊðz/", "洗了我的衣服", "I washed my clothes."],
  "stayed at home": ["/steɪd æt həʊm/", "待在家里", "I stayed at home."],
  "watched tv": ["/wɒtʃt ˌtiː ˈviː/", "看了电视", "I watched TV yesterday."],
  "drank tea": ["/dræŋk tiː/", "喝了茶", "Grandpa drank tea."],
  "last weekend": ["/lɑːst ˌwiːkˈend/", "上周末", "Last weekend was fun."],
  "last night": ["/lɑːst naɪt/", "昨晚", "I read a book last night."],
  "last monday": ["/lɑːst ˈmʌndeɪ/", "上周一", "We played last Monday."],
  "yesterday": ["/ˈjestədeɪ/", "昨天", "I was busy yesterday."],
  "before": ["/bɪˈfɔː/", "在……之前", "Wash your hands before dinner."],
  "saw a film": ["/sɔː ə fɪlm/", "看了一场电影", "We saw a film."],
  "had a cold": ["/hæd ə kəʊld/", "感冒了", "I had a cold."],
  "slept": ["/slept/", "睡觉了(过去式)", "I slept all day."],
  "yesterday morning": ["/ˈjestədeɪ ˈmɔːnɪŋ/", "昨天早上", "I did sports yesterday morning."],
  "what did you do": ["/wɒt dɪd juː duː/", "你做了什么", "What did you do last night?"],
  "stayed at home and slept": ["/steɪd æt həʊm ənd slept/", "待在家睡觉", "I stayed at home and slept."],
  "cleaned the window": ["/kliːnd ðə ˈwɪndəʊ/", "擦了窗户", "I cleaned the window."],
  "washed the dishes": ["/wɒʃt ðə ˈdɪʃɪz/", "洗了碗", "Mum washed the dishes."],
  "went": ["/went/", "去了(过去式)", "I went to the park."],
  "camp": ["/kæmp/", "野营", "Went to a summer camp."],
  "went camping": ["/went ˈkæmpɪŋ/", "去野营", "We went camping."],
  "went fishing": ["/went ˈfɪʃɪŋ/", "去钓鱼", "Dad went fishing."],
  "rode a horse": ["/rəʊd ə hɔːs/", "骑了马", "I rode a horse."],
  "hurt my foot": ["/hɜːt maɪ fʊt/", "伤了我的脚", "I hurt my foot."],
  "ate fresh food": ["/et freʃ fuːd/", "吃了新鲜食物", "I ate fresh food."],
  "took pictures": ["/tʊk ˈpɪktʃəz/", "拍了照片", "We took pictures."],
  "bought gifts": ["/bɔːt ɡɪfts/", "买了礼物", "I bought gifts for friends."],
  "beach": ["/biːtʃ/", "海滩", "Play on the beach."],
  "basket": ["/ˈbɑːskɪt/", "篮子", "A picnic basket."],
  "part": ["/pɑːt/", "角色/部分", "I played a part."],
  "licked": ["/lɪkt/", "舔了(过去式)", "The dog licked my hand."],
  "laughed": ["/lɑːft/", "笑了(过去式)", "We laughed happily."],
  "till": ["/tɪl/", "直到", "Play till 5 o'clock."],
  "couldn't": ["/ˈkʊdnt/", "不能(过去式)", "I couldn't swim then."],
  "dining hall": ["/ˈdaɪnɪŋ hɔːl/", "饭厅", "We ate in the dining hall."],
  "gym": ["/dʒɪm/", "体育馆", "Play basketball in the gym."],
  "ago": ["/əˈɡəʊ/", "以前", "There was no gym ten years ago."],
  "cycling": ["/ˈsaɪklɪŋ/", "骑自行车运动", "Go cycling in the park."],
  "go cycling": ["/ɡəʊ ˈsaɪklɪŋ/", "去骑车", "I go cycling every day."],
  "ice-skate": ["/ˈaɪs skeɪt/", "滑冰", "I can ice-skate."],
  "badminton": ["/ˈbædmɪntən/", "羽毛球", "Play badminton."],
  "easy": ["/ˈiːzi/", "容易的", "It's easy for me."],
  "look up": ["/lʊk ʌp/", "查阅", "Look up the word."],
  "internet": ["/ˈɪntənet/", "互联网", "Search on the internet."],
  "different": ["/ˈdɪfrənt/", "不同的", "A different world."],
  "active": ["/ˈæktɪv/", "活跃的", "An active boy."],
  "race": ["/reɪs/", "赛跑", "Win the race."],
  "nothing": ["/ˈnʌθɪŋ/", "没有什么", "Nothing at all."],
  "thought": ["/θɔːt/", "想(过去式)", "I thought it was easy."],
  "felt": ["/felt/", "感觉(过去式)", "I felt happy."],
  "cheetah": ["/ˈtʃiːtə/", "猎豹", "The cheetah runs fast."],
  "woke": ["/wəʊk/", "醒来(过去式)", "I woke up early."],
  "dream": ["/driːm/", "梦", "A sweet dream."],
  "was": ["/wɒz/", "是(过去式)", "I was at home."],
  "were": ["/wɜː/", "是(过去式)", "We were happy."],
  "will be": ["/wɪl biː/", "将会是", "There will be a new gym."],
  "there was": ["/ðeə wɒz/", "有(过去式)", "There was a small house."],
  "there were": ["/ðeə wɜː/", "有(过去式)", "There were many trees."],
  "didn't": ["/ˈdɪdnt/", "没有(过去式)", "I didn't like winter before."]
};

// --- 语文词库：部编版统编教材生字表组词（1-6年级12册全量），教师用书审计基准 ---
// 结构: "词语": "例句"
const CN_METADATA: Record<string, string> = {
  // ============ 语文一年级上册（写字表100字组词+常用词） ============
  "一天": "一天很快就过去了。",
  "二月": "二月的春风吹绿了柳树。",
  "三人": "三人在教室里读书。",
  "上山": "我们一起上山看日出。",
  "口水": "小猫看见鱼就流口水。",
  "目光": "老师的目光很温柔。",
  "耳朵": "小兔子的耳朵长长的。",
  "手心": "手心里捧着糖果。",
  "日子": "上学的日子真开心。",
  "田里": "田里的禾苗绿油油。",
  "禾苗": "禾苗喝饱了水长得快。",
  "火车": "火车开往北京。",
  "虫子": "小鸟在草地上找虫子。",
  "云朵": "天上的云朵像棉花糖。",
  "山水": "这里的山水真美丽。",
  "八个": "桌上有八个苹果。",
  "十个": "我数到十个手指头。",
  "儿子": "儿子给妈妈倒水。",
  "大人": "大人小孩都笑了。",
  "月儿": "弯弯的月儿挂天空。",
  "头发": "奶奶的头发白了。",
  "里面": "书包里面装着课本。",
  "可是": "我想玩，可是要写作业。",
  "东方": "太阳从东方升起。",
  "西方": "彩虹挂在西方的天空。",
  "天上": "天上有许多星星。",
  "四个": "四个小朋友在跳绳。",
  "女生": "女生排队走在前面。",
  "水里": "小鱼在水里游来游去。",
  "来了": "春天来了，花开了。",
  "不会": "我现在不会，学学就会了。",
  "小心": "过马路要小心看车。",
  "多少": "你有多少本故事书？",
  "牛羊": "草原上有牛羊。",
  "果子": "秋天树上结满果子。",
  "小鸟": "小鸟在枝头唱歌。",
  "早上": "早上我背书包上学。",
  "书本": "书本要爱护好。",
  "尺子": "尺子可以画直线。",
  "本子": "本子上写字真工整。",
  "木头": "木头做的小船真可爱。",
  "树林": "树林里传来鸟叫声。",
  "泥土": "种子在泥土里发芽。",
  "力气": "大象的力气真大。",
  "心里": "我心里乐开了花。",
  "中国": "我爱我的中国。",
  "五个": "五个气球飞上天。",
  "立正": "升旗时我们要立正。",
  "正在": "我正在认真写字。",
  "后来": "后来他学会了游泳。",
  "我们": "我们都是好朋友。",
  "好人": "好人一生平安。",
  "长大": "我长大想当老师。",
  "尾巴": "小鱼的尾巴像剪刀。",
  "下雨": "下雨了，快回家吧。",
  "他们": "他们在操场上踢球。",
  "问好": "见到老师要问好。",
  "有人": "教室里有人吗？",
  "半天": "他半天没说出话来。",
  "从来": "我从来不说谎话。",
  "你们": "你们是几年级的？",
  "明天": "明天我们一起去公园。",
  "同学": "同学之间要互相帮助。",
  "学习": "学习让我更聪明。",
  "自己": "自己的事情自己做。",
  "衣服": "这件衣服真漂亮。",
  "白天": "白天上学，晚上睡觉。",
  "竹子": "熊猫爱吃竹子。",
  "牙齿": "早晚要刷牙齿。",
  "小马": "小马在草地上奔跑。",
  "用力": "拔萝卜要用力。",
  "几个": "篮子里有几个梨？",
  "一只": "一只鸭子游过来。",
  "石头": "石头上坐着一只青蛙。",
  "很多": "我有很多好朋友。",
  "出去": "我们出去玩吧。",
  "看见": "我看见彩虹了。",
  "对面": "对面走来一只小狗。",
  "妈妈": "妈妈做的饭最香。",
  "全家": "全家一起去郊游。",
  "回家": "放学后早点回家。",
  "工人": "工人叔叔在盖高楼。",
  "工厂": "工厂在生产汽车。",
  "太阳": "太阳晒得暖暖的。",
  "星星": "星星眨着小眼睛。",
  "晚上": "晚上要早点睡觉。",
  "下雪": "下雪了，我们堆雪人。",
  "冬天": "冬天到了，天气冷了。",
  "春天": "春天来了，燕子飞回。",
  "夏天": "夏天的荷花真美。",
  "秋天": "秋天果子熟了。",
  "夜晚": "夜晚的月亮圆圆的。",
  "学校": "学校里种着两棵大树。",
  "老师": "老师教我们学知识。",
  "拍手": "我们拍手唱歌真快乐。",
  "高兴": "我今天特别高兴。",
  "快乐": "祝小朋友天天快乐。",
  "游戏": "下课了我们做游戏。",
  "玩具": "玩具要收拾整齐。",
  "朋友": "朋友多了真开心。",
  "兄弟": "兄弟俩一起写作业。",
  "姐妹": "姐妹俩长得一样高。",
  "爸爸": "爸爸带我去动物园。",
  "爷爷": "爷爷在浇花。",
  "奶奶": "奶奶讲故事真好听。",
  "谢谢": "谢谢你的帮助。",
  "再见": "放学了和老师说再见。",
  "你好": "你好，请问这是哪里？",
  "大家": "大家一起做运动。",
  "一起": "我们一起画画吧。",
  "玩耍": "小伙伴们在玩耍。",
  "唱歌": "小鸟在树上唱歌。",
  "跳舞": "我们跳舞庆祝节日。",
  "画画": "我画画画了一只小猫。",
  "看书": "睡前看书真安静。",
  "写字": "写字要做到三个一。",
  "读书": "读书声音要洪亮。",
  "听讲": "上课要专心听讲。",
  "举手": "回答问题先举手。",
  "起立": "老师上课我们起立。",
  "坐下": "请坐下慢慢说。",
  "窗户": "打开窗户透透气。",
  "桌子": "把桌子擦得干干净净。",
  "椅子": "椅子要轻轻搬。",
  "铅笔": "铅笔削得尖尖的。",
  "橡皮": "橡皮帮我擦错字。",
  "花朵": "花朵开得五颜六色。",
  "小草": "小草从土里钻出来。",
  "大树": "大树底下好乘凉。",
  "叶子": "秋天的叶子黄了。",
  "河水": "河水清清看得见鱼。",
  "大海": "大海的浪花一朵朵。",
  "鱼儿": "鱼儿吐着小泡泡。",
  "乌龟": "乌龟慢慢爬过石头。",
  "兔子": "兔子爱吃胡萝卜。",
  "青蛙": "青蛙在荷叶上跳。",
  "鸭子": "鸭子嘎嘎叫着下水。",
  "国旗": "升国旗时我们要敬礼。",
  "美丽": "公园的花真美丽。",
  "白云": "白云在天上散步。",
  "土地": "土地是我们的宝藏。",
  "天空": "天空飘着白云。",
  "树木": "山坡上种满树木。",
  "森林": "森林是小动物的家。",
  "什么": "你在看什么书？",
  "说话": "上课不随便说话。",

  // ============ 语文一年级下册（写字表200字组词） ============
  "春风": "春风吹绿了小草。",
  "冬雪": "冬雪盖住了麦苗。",
  "花开": "春天到了，花开满园。",
  "飞鸟": "飞鸟在天空自由飞翔。",
  "入水": "小鸭子扑通入水。",
  "国王": "国王住在城堡里。",
  "王子": "王子骑马去探险。",
  "红色": "红色的气球飞上天。",
  "绿色": "绿色的田野真广阔。",
  "晴天": "晴天我们去看白云。",
  "请问": "请问图书馆在哪里？",
  "清水": "清水从山上流下来。",
  "心情": "今天心情真好。",
  "事情": "自己的事情自己做。",
  "生动": "老师讲故事真生动。",
  "千万": "过马路千万要小心。",
  "百花": "春天百花齐放。",
  "齐心": "大家齐心搬走大石头。",
  "电话": "我给外婆打电话。",
  "友谊": "友谊像花儿一样美。",
  "高山": "高山上有一座宝塔。",
  "语文": "语文课上学拼音。",
  "数学": "数学题难不倒我。",
  "音乐": "音乐响起我们跳舞。",
  "伙伴": "伙伴们一起做游戏。",
  "这里": "这里的风景真美。",
  "那里": "那里有一片果林。",
  "月亮": "月亮弯弯像小船。",
  "故乡": "故乡的小河真清。",
  "身体": "多运动身体好。",
  "运动": "运动场上真热闹。",
  "远近": "远近闻名的大鸭梨。",
  "听说": "听说动物园来了熊猫。",
  "左右": "上下楼梯靠右走。",
  "因为": "因为下雨，所以没去。",
  "江南": "江南的荷花开了。",
  "荷叶": "荷叶是小鱼的凉伞。",
  "红豆": "红豆生南国。",
  "地方": "这是个好玩的地方。",
  "没有": "我没有带雨伞。",
  "许多": "天上飞来许多鸽子。",
  "种子": "种子发芽了。",
  "发芽": "春天种子发芽了。",
  "树叶": "树叶飘下来像蝴蝶。",
  "雨水": "雨水滋润了大地。",
  "青草": "青草地上放风筝。",
  "河水清": "河水清清鱼儿游。",
  "温暖": "温暖的阳光照大地。",
  "冰冷": "冰冷的北风吹脸上。",
  "金色": "金色的稻谷熟了。",
  "银色": "银色的月光洒下来。",
  "彩色": "彩色画笔画彩虹。",
  "彩虹": "雨后天空出彩虹。",
  "阳光": "阳光照进教室。",
  "影子": "影子跟着我走。",
  "前后": "排队分清前后。",
  "旁边": "学校旁边是书店。",
  "中间": "中间坐着老师。",
  "上面": "书放在桌子上面。",
  "下面": "小猫躲在床下面。",
  "左右手": "左右手都要练习。",
  "名字": "我把名字写工整。",
  "生字": "生字要一笔一笔写。",
  "词语": "我们积累了好多词语。",
  "句子": "用好字造个句子。",
  "课文": "课文朗读要流利。",
  "故事": "睡前听个故事。",
  "童话": "童话里有小精灵。",
  "汽车": "汽车在马路上跑。",
  "飞机": "飞机飞得比云高。",
  "轮船": "轮船在大海上航行。",
  "走路": "走路要看红绿灯。",
  "跑步": "跑步让身体更强壮。",
  "跳跃": "小鹿在林间跳跃。",
  "游泳": "夏天游泳真凉快。",
  "骑车": "我学会骑车了。",
  "书包": "书包里有新课本。",
  "铅笔盒": "铅笔盒里装着尺子。",
  "本领": "小猫钓鱼学本领。",
  "本领大": "谁的本领大？",
  "主意": "我想出好主意了。",
  "办法": "乌鸦想出喝水办法。",
  "着急": "别着急，慢慢来。",
  "高兴地": "我们高兴地拍手。",
  "慢慢地": "小蜗牛慢慢地爬。",
  "轻轻地": "轻轻地关门别吵醒妹妹。",
  "认真地": "我认真地写每个字。",
  "快乐地": "小鸟快乐地唱歌。",
  "邻居": "邻居家的姐姐帮我补习。",
  "家乡": "家乡的西瓜最甜。",
  "亲人": "过年亲人都团聚。",
  "热情": "热情帮助有困难的同学。",
  "礼貌": "有礼貌的孩子人人爱。",
  "帮助": "帮助别人真开心。",
  "感谢": "感谢老师教我们知识。",
  "劳动": "劳动最光荣。",
  "干净": "教室打扫得真干净。",
  "整齐": "队伍排得整整齐齐。",
  "明亮": "明亮的教室真宽敞。",
  "安静": "图书馆里要安静。",
  "温暖的家": "家是最温暖的港湾。",
  "爱护": "爱护公园里的花草。",
  "保护": "保护环境从我做起。",
  "空气": "早晨的空气真新鲜。",
  "新鲜": "菜市场有新鲜的蔬菜。",
  "健康": "早睡早起身体健健康康。",
  "平安": "祝大家一路平安。",
  "生气": "小猪气得直跺脚。",
  "开心": "六一儿童节真开心。",

  // ============ 语文二年级上册（小蝌蚪找妈妈/植物妈妈有办法/场景歌等课文词语） ============
  "两个": "两个小朋友一起走。",
  "哪里": "小蝌蚪的妈妈在哪里？",
  "宽大": "宽大的荷叶像雨伞。",
  "头顶": "头顶上戴着草帽。",
  "眼睛": "明亮的大眼睛。",
  "肚皮": "雪白的大肚皮。",
  "孩子": "懂事乖巧的孩子。",
  "跳高": "运动会上比跳高。",
  "变化": "四季景色多变化。",
  "一片": "一片金黄的稻田。",
  "傍晚": "傍晚晚霞红彤彤。",
  "海洋": "广阔无边的海洋。",
  "工作": "辛勤工作创未来。",
  "坏事": "知错改正不做坏事。",
  "如果": "如果明天下雨就带伞。",
  "毛笔": "用毛笔练习书法。",
  "写信": "写信问候远方的爷爷。",
  "圆珠笔": "用圆珠笔做笔记。",
  "电灯": "电灯照亮了书房。",
  "电影": "周末看科普电影。",
  "今天": "今天天气真晴朗。",
  "深处": "走进森林深处。",
  "熊猫": "国宝大熊猫吃竹子。",
  "辛苦": "老师备课真辛苦。",
  "农忙": "秋天农忙收庄稼。",
  "归来": "傍晚渔船满载归来。",
  "爱戴": "大家真心爱戴老师。",
  "英雄": "向英雄致敬。",
  "队旗": "少先队队旗迎风飘。",
  "铜号": "吹响嘹亮的铜号。",
  "欢笑": "操场传来欢笑声。",
  "杨树": "高大挺拔的杨树。",
  "壮丽": "祖国山河壮丽雄奇。",
  "梧桐": "梧桐树叶像手掌。",
  "枫叶": "秋天枫叶红似火。",
  "松柏": "松柏四季常青。",
  "棉花": "棉花白如雪。",
  "杉树": "笔直的水杉树。",
  "化石": "恐龙是远古化石。",
  "季节": "丰收的美好季节。",
  "蝴蝶": "花丛中蝴蝶飞舞。",
  "麦苗": "麦苗青青长势好。",
  "桑叶": "蚕宝宝吃桑叶。",
  "农家": "宁静祥和的农家小院。",
  "植物": "植物妈妈的办法多。",
  "旅行": "蒲公英去旅行。",
  "准备": "出发前做好准备。",
  "降落伞": "蒲公英像降落伞。",
  "纷纷": "树叶纷纷落下来。",
  "观察": "仔细观察小昆虫。",
  "粗心": "做题不能粗心。",
  "得到": "努力得到好成绩。",
  "知识": "知识就是力量。",
  "四海为家": "植物四海为家。",
  "脚尖": "踮起脚尖看远方。",
  "愉快": "愉快的周末郊游。",
  "广场": "广场上放风筝的人真多。",
  "围绕": "水池周围围着栅栏。",
  "池塘": "池塘里荷花盛开。",
  "名胜古迹": "游览名胜古迹。",
  "群山": "群山环绕着小村庄。",
  "凉快": "树荫下面真凉快。",
  "百闻不如一见": "百闻不如一见。",
  "展翅": "雄鹰展翅高飞。",
  "滑冰": "冬天在湖面滑冰。",
  "报纸": "爷爷每天看报纸。",
  "雪花": "雪花漫天飞舞。",
  "名不虚传": "这里的风景名不虚传。",
  "一动不动": "青蛙一动不动地蹲着。",
  "淹没": "洪水淹没了庄稼。",
  "冲毁": "大水冲毁了堤坝。",
  "灾害": "洪水是无情的灾害。",
  "恢复": "灾后重建恢复家园。",
  "教训": "记住这个教训。",
  "治理": "大禹治理洪水。",
  "疏通": "疏通河道引水入海。",
  "驱赶": "驱赶蚊虫用扇子。",
  "房屋": "山坡上有间小房屋。",
  "其余": "其余同学去操场。",
  "带领": "老师带领我们做实验。",
  "哨兵": "大雁是旅行团的哨兵。",
  "翻译": "妈妈帮我翻译单词。",
  "危险": "危险的地方不能去。",
  "讨好": "狐狸讨好老虎。",
  "百兽": "老虎是百兽之王。",
  "违抗": "不能违抗命令。",
  "纳闷": "小马心里很纳闷。",
  "拔河": "运动会拔河比赛。",
  "为难得": "为难的时候找人帮忙。",
  "亲切": "老师亲切地问我。",
  "脚印": "雪地上留下小脚印。",
  "暖和": "棉衣穿着真暖和。",
  "痛快": "痛痛快快玩一场。",
  "盛开": "鲜花盛开满校园。",
  "喊叫": "他大声喊叫起来。",
  "纷纷出发": "种子纷纷出发去远方。",

  // ============ 语文二年级下册（找春天/古诗二首/笋芽儿等课文词语） ============
  "寻找": "我们去寻找春天的足迹。",
  "姑娘": "美丽聪慧的小姑娘。",
  "野花": "山坡上盛开着野花。",
  "柳枝": "柔软的柳枝随风摇。",
  "桃花": "粉红的桃花朵朵开。",
  "杏花": "洁白的杏花枝头俏。",
  "冲出": "小溪流冲出山谷。",
  "原来": "原来是大自然的规律。",
  "叔叔": "邮递员叔叔送信来。",
  "邮局": "到邮局寄送明信片。",
  "礼物": "收到一份珍贵的礼物。",
  "先生": "鹿先生和鼹鼠先生。",
  "太太": "松鼠太太笑了。",
  "做客": "到好朋友家里做客。",
  "惊奇": "大家都感到很惊奇。",
  "快活": "小鸟在枝头快活唱歌。",
  "美好": "创造美好的明天。",
  "植树": "春天参加植树活动。",
  "格外": "阳光显得格外灿烂。",
  "引人注目": "金黄的花海引人注目。",
  "满意": "老师露出满意的笑容。",
  "休息": "课间适当放松休息。",
  "树苗": "种下一株株小树苗。",
  "笔直": "笔直挺拔的白杨树。",
  "汗珠": "额头滚落勤劳的汗珠。",
  "甚至": "甚至比想象中更出色。",
  "花草": "爱护公园的花草树木。",
  "原野": "辽阔无边的大原野。",
  "五颜六色": "五颜六色的气球飞上天。",
  "精灵": "森林里快乐的小精灵。",
  "叮咛": "妈妈临行的亲切叮咛。",
  "聊天": "和好朋友开怀聊天。",
  "草坪": "在绿茵茵的草坪踢球。",
  "烟囱": "屋顶烟囱升起炊烟。",
  "一般": "像童话世界一般美好。",
  "梦想": "怀揣科学家的梦想。",
  "拉手": "小伙伴手拉手心连心。",
  "结果": "努力结出丰硕成果。",
  "苹果": "红彤彤的大苹果。",
  "喜欢": "我喜欢读科普书。",
  "碧绿": "碧绿的湖水像镜子。",
  "剪刀": "燕子的尾巴像剪刀。",
  "细雨": "细雨蒙蒙润万物。",
  "洒脱": "草原骑马真洒脱。",
  "敲鼓": "敲锣打鼓庆丰收。",
  "漫步": "在林间小道漫步。",
  "凉棚": "葡萄架下搭凉棚。",
  "难道": "难道你不想去吗？",
  "神气": "小公鸡神气地走路。",
  "住嘴": "请大家安静住嘴。",
  "争论": "不要无谓地争论。",
  "评理": "找大象爷爷评理。",
  "道理": "做人要讲道理。",
  "一致": "大家一致表示同意。",
  "清晨": "清晨空气最新鲜。",
  "相遇": "在路口相遇。",
  "狐狸": "狡猾的狐狸骗乌鸦。",
  "老虎": "威风凛凛的老虎。",
  "肉": "乌鸦嘴里叼着肉。",
  "抬": "抬起头看蓝天。",
  "值日": "今天轮到我值日。",
  "干涸": "小河干涸见底了。",
  "井": "村口有一口老井。",
  "泉眼": "山间泉眼冒清水。",
  "尽": "用尽全力跳过去。",
  "惜": "珍惜每一粒粮食。",
  "照": "镜子照出笑脸。",
  "晴": "雨过天晴空气好。",
  "柔": "柳枝柔软随风摆。",
  "荷": "夏日荷塘飘清香。",
  "露": "荷叶上滚动露珠。",

  // ============ 语文三年级上册（大青树下的小学/金色草地/秋天的雨等课文词语） ============
  "早晨": "早晨的校园书声琅琅。",
  "穿戴": "各民族同学穿戴鲜艳。",
  "鲜艳": "鲜艳的红领巾飘胸前。",
  "服装": "民族服装真漂亮。",
  "打扮": "节日里大家打扮得美美的。",
  "敬爱": "敬爱的老师您好。",
  "敬礼": "向国旗庄严敬礼。",
  "树枝": "小鸟站在树枝上歌唱。",
  "好奇": "孩子对世界充满好奇。",
  "招引": "花香招引来蝴蝶。",
  "洁白": "洁白的云朵飘啊飘。",
  "摇晃": "风儿摇晃着小树。",
  "落下": "树叶慢慢落下来。",
  "荒野": "荒野上开满小花。",
  "狂欢": "节日里大家尽情狂欢。",
  "互相": "同学之间互相帮助。",
  "能够": "我能够自己完成作业。",
  "猜出": "谜语被我猜出来了。",
  "扬起": "扬起笑脸迎接客人。",
  "双臂": "张开双臂拥抱大海。",
  "朗读": "有感情地朗读课文。",
  "飘扬": "五星红旗迎风飘扬。",
  "假日": "假日里去郊外游玩。",
  "教师": "教师是辛勤的园丁。",
  "蒲公英": "蒲公英随风去旅行。",
  "合拢": "花瓣慢慢合拢了。",
  "手掌": "张开手掌数一数。",
  "一本正经": "他一本正经地模仿老师。",
  "假睡": "小猫假睡等老鼠。",
  "寒冷": "寒冷的冬天北风呼啸。",
  "雨珠": "雨珠在叶尖跳舞。",
  "钥匙": "秋雨是开启冬天的钥匙。",
  "颜料": "秋天有五彩的颜料。",
  "频频": "大雁频频点头告别。",
  "凉爽": "秋风吹来格外凉爽。",
  "丰收": "金色的田野丰收在望。",
  "加紧": "小动物加紧准备粮食。",
  "过冬": "燕子飞去南方过冬。",
  "歌曲": "唱一首动听的歌曲。",
  "温柔": "妈妈的声音真温柔。",
  "留意": "留心观察身边的事物。",
  "香甜": "果园飘来香甜的味道。",
  "蜂蜜": "小蜜蜂酿出甜甜蜂蜜。",
  "清甜": "泉水清甜可口。",
  "油亮亮": "柿子长得油亮亮。",
  "火红": "火红的枫叶真美。",
  "邮票": "集邮册里珍藏着邮票。",
  "邮票洞": "秋姑娘的邮票是落叶。",
  "菊花": "秋菊傲霜绽放。",
  "仙子": "桂花像金色的小仙子。",
  "丁香": "丁香花散发着幽香。",
  "盛气凌人": "不要盛气凌人。",
  "挖掘": "考古学家挖掘化石。",
  "水泥": "水泥路铺到村口。",
  "亮晶晶": "亮晶晶的水珠滚动。",
  "图案": "民族服饰图案精美。",
  "排列": "图书排列得整整齐齐。",
  "规则": "遵守交通规则。",
  "凌乱": "书桌整理得不凌乱。",
  "增添": "为教室增添绿意。",
  "棕红": "棕红色的小船飘远。",
  "迟到": "今天千万不能迟到。",
  "经常": "我经常帮妈妈做家务。",
  "故宫": "故宫是宏伟的古建筑。",
  "蚂蚁": "蚂蚁搬家要下雨。",
  "兄台": "蟋蟀的住宅真讲究。",
  "住宅": "蟋蟀的住宅像别墅。",
  "临时": "图书馆临时闭馆。",
  "住址": "信封上写清住址。",
  "洞穴": "动物的洞穴真奇妙。",
  "专家": "动物是筑巢专家。",
  "顺畅": "文章读起来很顺畅。",
  "卧室": "卧室收拾得干干净净。",
  "卫生间": "卫生间要勤打扫。",
  "选择": "好好选择读物。",
  "搜集": "搜集落叶做标本。",
  "倾斜": "屋顶向一边倾斜。",
  "隧道": "火车穿过隧道。",
  "搜索": "搜索知识的宝藏。",
  "扑空": "两次搜索都扑空了。",
  "趁机": "小猫趁机溜进屋。",
  "痕迹": "雪地上有小兔的痕迹。",
  "懒惰": "懒惰的小猪睡大觉。",
  "平展": "白鹭平展着翅膀。",
  "悲哀": "不要停留在悲哀中。",
  "镜子": "湖水像一面镜子。",
  "消毒": "伤口要及时消毒。",
  "忧虑": "不要有过多的忧虑。",
  "若明若暗": "灯光若明若暗。",
  "即使": "即使下雨也要上学。",
  "警觉": "小鹿十分警觉。",
  "锐利": "老鹰的眼睛很锐利。",
  "十分": "今天的作业十分简单。",
  "洞口": "洞口藏着小刺猬。",
  "翘起": "小狗翘起尾巴。",
  "讨厌": "不能讨厌劳动。",
  "讨厌的": "骄傲是讨厌的缺点。",
  "发明": "古人发明了造纸术。",
  "百发百中": "后羿射日百发百中。",
  "掌声": "掌声送给勇敢的你。",
  "文静": "她是个文静的女孩。",
  "默默": "默默地做好事。",
  "轮流": "值日生轮流站岗。",
  "讲台": "老师站在讲台前。",
  "热烈": "热烈欢迎新同学。",
  "持久": "掌声经久不息很持久。",
  "平息": "风波慢慢平息了。",
  "情况": "老师了解每个同学的情况。",
  "鼓励": "老师鼓励我大胆发言。",
  "勇气": "勇气战胜了胆怯。",
  "鞠躬": "向老师深深鞠躬。",
  "司空见惯": "这种现象已是司空见惯。",

  // ============ 语文三年级下册（燕子/荷花/守株待兔等课文词语） ============
  "燕子": "燕子是春天的使者。",
  "乌黑": "燕子羽毛乌黑发亮。",
  "轻快": "燕子飞行轻快敏捷。",
  "翅膀": "鸽子展开翅膀飞翔。",
  "活泼": "小猴子活泼又机灵。",
  "微风": "微风吹拂着柳枝。",
  "赶集": "人们像赶集似的聚拢。",
  "聚拢": "荷叶聚拢成绿伞。",
  "光彩夺目": "宝石在阳光下光彩夺目。",
  "掠过": "燕子掠过湖面。",
  "稻田": "稻田翻起金色波浪。",
  "偶尔": "偶尔有鱼儿跃出水面。",
  "沾水": "蜻蜓轻轻沾水。",
  "荡漾": "小船在湖心荡漾。",
  "荷花": "夏日荷花开满池。",
  "清香": "荷花开出淡淡清香。",
  "莲蓬": "莲蓬里藏着莲子。",
  "破裂": "荷叶的水珠滚来滚去。",
  "姿势": "荷花姿态万千。",
  "仿佛": "我仿佛来到了江南。",
  "衣裳": "换上漂亮的衣裳。",
  "舞蹈": "蝴蝶翩翩起舞。",
  "翩翩起舞": "蝴蝶在花丛翩翩起舞。",
  "蜻蜓": "蜻蜓立在荷尖上。",
  "守株待兔": "守株待兔不可取。",
  "耕田": "农民伯伯在耕田。",
  "触株": "兔子触株折颈。",
  "颈部": "长颈鹿的颈部很长。",
  "释放": "释放压力心情好。",
  "骄傲": "骄傲使人落后。",
  "谦虚": "谦虚使人进步。",
  "懦弱": "要勇敢不做懦弱的人。",
  "尘土": "马车扬起尘土。",
  "捧起": "捧起书本认真读。",
  "擦洗": "把桌子擦洗干净。",
  "古代": "长城是古代建筑。",
  "价值": "诚信有金子般的价值。",
  "动手": "自己动手丰衣足食。",
  "狮子": "狮子是草原之王。",
  "鹿角": "梅花鹿的鹿角真美。",
  "欣赏": "欣赏美丽的风景。",
  "匀称": "这棵树长得匀称。",
  "精美": "礼物包装十分精美。",
  "别致": "这座桥造型别致。",
  "犹豫": "遇事果断不犹豫。",
  "机灵": "机灵的小松鼠藏松果。",
  "逼近": "猎狗一步步逼近。",
  "没精打采": "他没精打采地走开。",
  "争奇斗艳": "花园里百花争奇斗艳。",
  "芬芳": "鲜花吐露芬芳。",
  "展示": "向大家展示作品。",
  "修建": "修建崭新的学校。",
  "组成": "小组由五人组成。",
  "蜜蜂": "蜜蜂勤劳采花蜜。",
  "辨认": "能辨认回家的路。",
  "能力": "自学能力很重要。",
  "阻力": "空气阻力会减慢速度。",
  "包括": "全班包括老师都到了。",
  "准确": "钟表走时很准确。",
  "无误": "计算准确无误。",
  "沿路": "沿路风景美如画。",
  "陌生": "陌生的地方要结伴去。",
  "超常": "蜜蜂有超常的记忆力。",
  "记忆": "童年记忆真美好。",
  "本能": "吸吮是婴儿的本能。",
  "放下": "放下书本去运动。",
  "实际": "理论联系实际。",
  "看法": "大家的看法很一致。",
  "幸福": "幸福的生活靠劳动。",
  "集合": "运动员集合了。",
  "国家": "国家兴亡匹夫有责。",
  "沙滩": "沙滩上捡贝壳。",
  "迅速": "迅速赶到现场。",
  "海参": "海底有懒洋洋的海参。",
  "海藻": "海藻随波摇曳。",
  "攻击": "不要攻击小动物。",
  "窃窃私语": "他们在窃窃私语。",
  "属": "虎年属虎的宝宝。",
  "内": "教室内安静无声。",
  "营养": "蔬菜富含营养。",
  "领土": "祖国领土神圣不可侵犯。",
  "差异": "南北气候差异大。",
  "物质": "水是生命物质。",
  "宋": "宋朝人擅长写词。",
  "排": "排队要有秩序。",
  "服饰": "民族服饰五彩斑斓。",
  "观望": "观望等待时机。",
  "旭日": "旭日东升照大地。",

  // ============ 语文四年级上册（观潮/走月亮/呼风唤雨的世纪等课文词语） ============
  "观潮": "我们去钱塘江观潮。",
  "据说": "据说潮水非常壮观。",
  "大堤": "大堤上站满了观潮的人。",
  "宽阔": "江面宽阔平静。",
  "笼罩": "薄雾笼罩着江面。",
  "人山人海": "广场上人山人海。",
  "屹立": "宝塔屹立在山顶。",
  "若隐若现": "远山若隐若现。",
  "昂首": "大鹅昂首挺胸地走。",
  "顿时": "人群顿时沸腾起来。",
  "人声鼎沸": "街上人声鼎沸。",
  "浩浩荡荡": "车队浩浩荡荡出发。",
  "山崩地裂": "潮声如同山崩地裂。",
  "霎时": "霎时天空中乌云密布。",
  "余波": "潮水过去了还有余波。",
  "依旧": "江面依旧风号浪吼。",
  "牵手": "我们手牵手过马路。",
  "鹅卵石": "河滩上布满鹅卵石。",
  "坑坑洼洼": "小路坑坑洼洼。",
  "填平": "把坑坑洼洼填平。",
  "庄稼": "庄稼喝足了水。",
  "风俗": "家乡有独特的风俗。",
  "跃出": "鱼儿跃出水面。",
  "葡萄": "葡萄架下乘凉真甜。",
  "稻谷": "秋天稻谷金黄一片。",
  "成熟": "果子成熟了。",
  "柔和": "月光柔和地照着大地。",
  "河床": "干涸的河床露出来。",
  "修补": "渔网要经常修补。",
  "科学": "科学改变生活。",
  "横贯": "彩虹横贯天空。",
  "虚弱": "病后身体很虚弱。",
  "呼风唤雨": "科技呼风唤雨。",
  "世纪": "二十一世纪了不起。",
  "技术": "现代技术突飞猛进。",
  "改变": "知识改变命运。",
  "程度": "进步的程度不同。",
  "超过": "成绩超过了我。",
  "幻想": "古人的幻想变成了现实。",
  "原子核": "原子核能量巨大。",
  "奥秘": "探索宇宙的奥秘。",
  "日益": "生活日益美好。",
  "联系": "电话联系着亲人。",
  "哲学家": "苏格拉底是哲学家。",
  "任何": "困难都难不倒我们。",
  "改善": "环境得到了改善。",
  "蝙蝠": "蝙蝠夜间飞行。",
  "雷达": "雷达是飞机的眼睛。",
  "避开": "敏捷地避开障碍物。",
  "敏捷": "动作敏捷像小猴。",
  "捕捉": "猫头鹰夜间捕捉田鼠。",
  "苍蝇": "苍蝇拍打死苍蝇。",
  "揭开": "揭开科学的奥秘。",
  "推进": "火箭推进飞船升空。",
  "障碍": "雷达帮飞机避开障碍。",
  "荧光屏": "荧光屏显示图案。",
  "恐龙": "恐龙早已灭绝。",
  "凶猛": "霸王龙很凶猛。",
  "笨重": "犀牛身体笨重。",
  "迟钝": "寒冬里蛇很迟钝。",
  "鸽子": "鸽子象征和平。",
  "末期": "白垩纪是恐龙末期。",
  "描绘": "蓝图描绘未来。",
  "形态": "云的形态千变万化。",
  "膨大": "蒸汽使气球膨大。",
  "前肢": "恐龙的前肢短小。",
  "具备": "具备了飞行条件。",
  "开辟": "开辟新的航线。",
  "脱离": "脱离了危险。",
  "无忧无虑": "童年的生活无忧无虑。",
  "无忧无虑的": "小鸟无忧无虑地飞翔。",
  "生气勃勃": "校园生气勃勃。",
  "天高地阔": "乡下人家天高地阔。",
  "月明人静": "月明人静的夜晚。",
  "一丝不苟": "他做事一丝不苟。",
  "空空如也": "口袋空空如也。",
  "枝折花落": "淘气猫闹得枝折花落。",
  "从容不迫": "他从容不迫地回答。",
  "扬长而去": "小狗被训后扬长而去。",
  "没完没了": "知了没完没了地叫。",
  "屏息凝视": "猫屏息凝视等老鼠。",
  "变化多端": "天气变化多端。",
  "屋檐": "燕子在屋檐下筑巢。",
  "装饰": "鲜花装饰着教室。",
  "顺序": "按顺序排队。",
  "华丽": "孔雀的尾巴真华丽。",
  "独特": "每个民族都有独特文化。",
  "照例": "他照例早起跑步。",
  "率领": "老师率领我们参观。",
  "觅食": "母鸡带小鸡觅食。",
  "捣衣": "溪边传来捣衣声。",
  "向导": "导游是我们的向导。",
  "和谐": "人与自然和谐相处。",
  "蚕桑": "乡下养蚕桑忙。",
  "耘田": "童孙也学耘田。",
  "慰藉": "书籍是心灵的慰藉。",
  "卜落": "雨点卜落卜落地落。",
  "威力": "台风威力真大。",
  "河滩": "河滩上晒着渔网。",
  "帐子": "蚊帐挡住蚊子。",
  "闪烁": "星星闪烁着光芒。",
  "奇幻": "森林里有奇幻的传说。",
  "帐单": "付清了电费帐单。",

  // ============ 语文四年级下册（乡下人家/天窗/琥珀等课文词语） ============
  "寂静": "夜晚的田野十分寂静。",
  "譬如": "譬如燕子是候鸟。",
  "敏锐": "反应敏锐很重要。",
  "例行": "例行检查保安全。",
  "检查": "认真检查作业。",
  "庄严": "升旗仪式庄严隆重。",
  "胸脯": "挺起胸脯走路。",
  "站岗": "战士为国站岗。",
  "帐篷": "郊外搭起帐篷。",
  "倒霉": "出门忘带伞真倒霉。",
  "忧伤": "不要一直忧伤。",
  "处境": "处境艰难仍要乐观。",
  "理智": "遇事要理智冷静。",
  "控制": "控制好情绪。",
  "混乱": "房间要整理不能混乱。",
  "简陋": "山区的教室很简陋。",
  "野蛮": "不能有野蛮行为。",
  "忧郁": "阳光驱走忧郁。",
  "至于": "至于结果并不重要。",
  "淡忘": "往事渐渐淡忘。",
  "宽慰": "老师的话让我宽慰。",
  "荒岛": "鲁滨逊漂流荒岛。",
  "凄凉": "故事结局有些凄凉。",
  "寂寞": "独自在家不寂寞。",
  "恐惧": "战胜恐惧就赢一半。",
  "宴会": "国庆盛宴招待客人。",
  "栅栏": "篱笆栅栏围着菜园。",
  "贷方": "学会理财不乱花钱。",
  "凄惨": "卖火柴的小女孩好凄惨。",
  "欣慰": "妈妈欣慰地笑了。",
  "书籍": "好书是最好的伙伴。",
  "而已": "只是小事而已。",
  "栅栏里": "小羊关在栅栏里。",
  "复活": "春天万物复苏。",
  "节日": "六一儿童节最快乐。",
  "鞭炮": "春节放鞭炮。",
  "腊月": "腊月里家家忙年。",
  "大蒜": "大蒜杀菌有益健康。",
  "饺子": "冬至吃饺子。",
  "摊贩": "街上有许多摊贩。",
  "彼此": "彼此分享最快乐。",
  "贺年": "给老师贺年。",
  "骆驼": "骆驼是沙漠之舟。",
  "恰好": "他恰好路过。",
  "一律": "校园里一律讲普通话。",
  "彩绘": "风筝彩绘真漂亮。",
  "糊涂": "难得糊涂。",
  "搅和": "面团要慢慢搅和。",
  "浓稠": "腊八粥熬得浓稠。",
  "可靠": "他是一个可靠的朋友。",
  "猜想": "大胆猜想小心求证。",
  "粉碎": "困难被我们粉碎。",
  "外套": "冬天穿上棉外套。",
  "解释": "耐心解释这道题。",
  "教授": "王教授讲学。",
  "困境": "摆脱困境靠智慧。",
  "既然": "既然错了就改正。",
  "此时": "此时此刻最难忘。",
  "万象更新": "新年万象更新。",
  "悬灯结彩": "元宵悬灯结彩。",
  "不可思议": "大自然不可思议。",
  "见微知著": "见微知著善于发现。",
  "锲而不舍": "锲而不舍金石可镂。",
  "追根求源": "学习要追根求源。",
  "无独有偶": "无独有偶又一个例证。",
  "饶有趣味": "实验饶有趣味。",
  "焉知非福": "塞翁失马焉知非福。",
  "截然不同": "两个答案截然不同。",
  "哄堂大笑": "表演引得哄堂大笑。",
  "能歌善舞": "傣族姑娘能歌善舞。",
  "随心所欲": "不能随心所欲。",
  "绿毯": "草原像绿毯。",
  "线条": "勾勒出柔美线条。",
  "柔美": "舞姿柔美动人。",
  "惊叹": "不禁惊叹这美景。",
  "回味": "回味无穷的旅行。",
  "乐趣": "读书有无穷乐趣。",
  "目的地": "终于到达目的地。",
  "马蹄": "马蹄声得得。",
  "拘束": "初次见面有些拘束。",
  "羞涩": "她害羞地笑了。",
  "摔跤": "草原上小朋友摔跤。",
  "偏偏": "他偏偏不来。",
  "河": "清澈的小河。",
  "敬酒": "主人热情敬酒。",
  "奏": "乐队奏起乐曲。",

  // ============ 语文五年级上册（白鹭/落花生/桂花雨/圆明园的毁灭等课文词语） ============
  "白鹭": "白鹭是一首精巧的诗。",
  "精巧": "这件手工艺品真精巧。",
  "色素": "白鹭的色素配合适宜。",
  "适宜": "温度适宜种子发芽。",
  "生硬": "说话不要太生硬。",
  "流线型": "燕子是流线型的身躯。",
  "孤独": "书是孤独时的朋友。",
  "悠闲": "老爷爷悠闲地散步。",
  "黄昏": "黄昏的晚霞真美。",
  "恩惠": "铭记老师的恩惠。",
  "播种": "春天播种秋收。",
  "浇水": "给花浇水施肥。",
  "吩咐": "妈妈吩咐我扫地。",
  "爱慕": "不能只外表惹人爱慕。",
  "体面": "做人要做有用体面的人。",
  "深浅": "先试试水的深浅。",
  "分辨": "分辨东西南北。",
  "便宜": "不能贪小便占便宜。",
  "石榴": "石榴笑得咧开了嘴。",
  "架子": "葡萄搭起长架子。",
  "尤其": "我尤其喜欢读史书。",
  "缠着": "妹妹缠着要听故事。",
  "及时": "雨来得真及时。",
  "完整": "答案要写完整。",
  "杭州": "杭州有美丽的西湖。",
  "茶叶": "龙井茶叶香。",
  "飘落": "桂花飘落像雨。",
  "迷信": "相信科学不迷信。",
  "紧邻": "学校紧邻图书馆。",
  "至少": "每天至少读书半小时。",
  "懂得": "要懂得感恩父母。",
  "担忧": "不要为小事担忧。",
  "上瘾": "看书看到入了迷。",
  "缠问": "妹妹缠着问不停。",
  "糕饼": "桂花糕饼香甜。",
  "浸泡": "茶叶浸泡出清香。",
  "杭绸": "杭绸柔软光滑。",
  "收获": "秋天是收获的季节。",
  "吩咐过": "妈妈吩咐过我。",
  "榨油": "花生可以榨油。",
  "短促": "哨声短促有力。",
  "茂盛": "草木茂盛夏天。",
  "珍惜": "珍惜宝贵的时光。",
  "迟延": "不能迟延一分钟。",
  "协调": "动作协调很优美。",
  "素净": "房间布置得素净。",
  "愈": "病愈后多锻炼。",
  "酬谢": "要懂得酬谢别人。",
  "珍宝": "博物馆里珍宝多。",
  "叮嘱": "老师再三叮嘱安全。",
  "崩塌": "洪水崩塌了堤坝。",
  "发誓": "发誓要努力学习。",
  "谎话": "不能说谎话。",
  "牺牲": "铭记牺牲的先烈。",
  "千真万确": "这是千真万确的。",
  "牛郎": "牛郎织女的故事。",
  "嫂子": "嫂子待人真亲切。",
  "床铺": "床铺整理得整齐。",
  "笑嘻嘻": "爷爷笑嘻嘻地喝茶。",
  "成家立业": "长大后成家立业。",
  "相依为命": "母女相依为命。",
  "晚霞": "晚霞映红了半边天。",
  "温和": "奶奶性情温和。",
  "亲密": "我们是亲密的伙伴。",
  "灿烂": "阳光灿烂的日子。",
  "怒发冲冠": "壮士怒发冲冠。",
  "难以置信": "成绩好得难以置信。",
  "举世闻名": "长城举世闻名。",
  "众星拱月": "群岛众星拱月般环绕。",
  "玲珑剔透": "水晶玲珑剔透。",
  "诗情画意": "江南充满诗情画意。",
  "太平盛世": "生逢太平盛世幸福。",
  "金碧辉煌": "宫殿金碧辉煌。",
  "完好无缺": "宝物保存完好无缺。",
  "灰烬": "化为灰烬真可惜。",
  "奉命": "奉命巡逻边疆。",
  "肩负": "肩负起责任。",
  "漫游": "书海漫游乐趣多。",
  "估量": "不可估量的损失。",
  "瑰宝": "圆明园是艺术瑰宝。",
  "建筑": "古建筑巧夺天工。",
  "宏伟": "故宫建筑宏伟。",
  "仿照": "仿照样品做模型。",
  "仿制": "仿制要注明出处。",
  "统统": "把书本统统搬走。",
  "销毁": "销毁假冒伪劣商品。",
  "罪证": "留下了侵略罪证。",
  "朗诵": "深情朗诵爱国诗篇。",
  "背诵": "背诵课文要熟读。",
  "训斥": "不要训斥孩子。",
  "名夷": "廉颇负荆请罪。",
  "负荆请罪": "知错负荆请罪。",
  "同心协力": "大家同心协力。",
  "攻无不克": "攻无不克战无不胜。",
  "战无不胜": "团结就战无不胜。",
  "完璧归赵": "完璧归赵传佳话。",
  "理直气壮": "他说得理直气壮。",
  "无价之宝": "诚信是无价之宝。",
  "绝口不提": "他绝口不提此事。",
  "神机妙算": "诸葛亮神机妙算。",
  "喜不自胜": "听了好消息喜不自胜。",
  "天造地设": "这里美景天造地设。",
  "踉踉跄跄": "他踉踉跄跄地走。",
  "抓耳挠腮": "急得抓耳挠腮。",
  "伸头缩颈": "乌龟伸头缩颈。",
  "力倦神疲": "跑到力倦神疲。",

  // ============ 语文五年级下册（古诗三首/草船借箭/景阳冈/猴王出世等课文词语） ============
  "昼夜": "昼夜苦读圣贤书。",
  "耕耘": "耕耘知识的田野。",
  "稚子": "稚子金盆脱晓冰。",
  "蚂蚱": "草丛里蹦出蚂蚱。",
  "樱桃": "红樱桃甜又香。",
  "瞎闹": "不要瞎闹要安静。",
  "锄头": "扛起锄头去种地。",
  "承认": "勇于承认错误。",
  "随意": "随意涂抹可不行。",
  "阴凉": "大树底下好阴凉。",
  "割草": "小羊在坡上割草。",
  "倭瓜": "倭瓜爬满了篱笆。",
  "威吓": "不要威吓小朋友。",
  "露馅": "谎话露馅了。",
  "屏障": "山是天然屏障。",
  "芝麻": "芝麻开花节节高。",
  "神圣": "祖国领土神圣。",
  "侵犯": "不能侵犯他人。",
  "乐此不疲": "读书乐此不疲。",
  "情不自禁": "情不自禁地鼓掌。",
  "肃然起敬": "对英雄肃然起敬。",
  "摩拳擦掌": "比赛前摩拳擦掌。",
  "跃跃欲试": "个个跃跃欲试。",
  "兴致勃勃": "兴致勃勃地参加。",
  "养尊处优": "不能养尊处优。",
  "手忙脚乱": "第一次做饭手忙脚乱。",
  "恍然大悟": "我恍然大悟。",
  "哭笑不得": "顽皮猫让人哭笑不得。",
  "若有所思": "他若有所思地望着远方。",
  "半信半疑": "他半信半疑地问。",
  "瞑目蹲身": "石猴瞑目蹲身一跳。",
  "纵身": "纵身跃入水中。",
  "颤抖": "冻得浑身颤抖。",
  "慈祥": "奶奶慈祥地笑了。",
  "荣幸": "获奖深感荣幸。",
  "眷恋": "海外游子眷恋祖国。",
  "锻炼": "天天锻炼身体好。",
  "繁忙": "爸爸工作繁忙。",
  "特殊": "特殊情况特殊处理。",
  "尊重": "尊重他人是美德。",
  "呐喊": "运动场上呐喊助威。",
  "陷坑": "小心前面的陷坑。",
  "诡计": "识破敌人的诡计。",
  "霹雳": "晴天一声霹雳。",
  "酥软": "吓得浑身酥软。",
  "耻笑": "不要耻笑别人。",
  "胸膛": "挺起胸膛做真人。",
  "拳头": "举起拳头宣誓。",
  "恶意": "不要有恶意。",
  "败坏": "不能败坏风气。",
  "祸事": "闯了祸事要承认。",
  "袍子": "穿上新袍子。",
  "嫌弃": "不能嫌弃同学。",
  "讥笑": "不要讥笑落后者。",
  "顽劣": "石猴顽劣又勇敢。",
  "家具": "新家具真漂亮。",
  "桥梁": "长江大桥真雄伟。",
  "眉目": "事情有了眉目。",
  "搔痒": "猴子互相搔痒。",
  "屡次": "屡次获得表扬。",
  "锈": "铁器生锈要防潮。",
  "断绝": "断绝不良习惯。",
  "拱桥": "赵州桥是石拱桥。",
  "屏息": "屏息静听心跳。",
  "巅峰": "攀上知识巅峰。",
  "阔别": "阔别多年的故乡。",
  "晶莹": "露珠晶莹剔透。",
  "蒸腾": "热气蒸腾。",
  "跋涉": "长途跋涉不怕苦。",
  "污迹": "洗掉衣服污迹。",
  "懊悔": "懊悔虚度了光阴。",
  "狂奔": "野马在草原狂奔。",
  "惊慌": "遇事不要惊慌。",
  "渗透": "雨水渗透泥土。",
  "拥挤": "高峰地铁很拥挤。",
  "遮蔽": "大树遮蔽烈日。",
  "朦胧": "月色朦胧如纱。",
  "玫瑰": "红玫瑰象征友谊。",
  "继续": "继续努力不放弃。",
  "缠绵": "细雨缠绵下不停。",
  "模仿": "不要盲目模仿。",
  "聘请": "学校聘请外教。",
  "燃烧": "火苗燃烧得正旺。",
  "铃铛": "驼队铃铛叮当响。",
  "枣红": "枣红马跑得快。",
  "挣断": "挣断了缰绳。",
  "揭穿": "揭穿谎言要证据。",
  "静候": "静候佳音。",
  "谴责": "要谴责不良行为。",
  "碍事": "杂物堆放碍事。",
  "怀疑": "怀疑要靠证据验证。",
  "阵亡": "悼念阵亡将士。",
  "招募": "招募小小志愿者。",
  "服从": "服从裁判的判罚。",
  "残疾": "关爱残疾朋友。",
  "犹豫不决": "他做事犹豫不决。",
  "创举": "赵州桥是大创举。",
  "雕刻": "石刻雕像真精美。",
  "遗产": "保护文化遗产。",
  "智慧": "劳动人民的智慧。",
  "才干": "增长才干靠实践。",
  "妒忌": "不能妒忌别人。",
  "军令状": "立下军令状必胜。",
  "探听": "不要探听隐私。",
  "幔子": "帐篷围着青布幔子。",
  "私自": "不能私自离队。",
  "调度": "科学调度保畅通。",
  "水寨": "水军驻扎水寨。",
  "擂鼓": "擂鼓呐喊助威。",
  "支援": "支援灾区献爱心。",
  "丞相": "诸葛亮是蜀国丞相。",
  "限度": "疲劳超过了限度。",
  "熬夜": "不能经常熬夜。",
  "吃惊": "成绩好得让人吃惊。",
  "虚张声势": "不要虚张声势。",
  "弓弩": "弓弩手严阵以待。",
  "迟": "上学不能迟到。",
  "悬挂": "灯笼高高悬挂。",

  // ============ 语文六年级上册（草原/丁香结/古诗词三首/桥等课文词语） ============
  "渲染": "中国画善用渲染。",
  "勾勒": "寥寥几笔勾勒骏马。",
  "迂回": "山路迂回盘旋。",
  "疾驰": "骏马在草原疾驰。",
  "天涯": "知己遍布天涯。",
  "幽雅": "庭院幽雅宁静。",
  "笨拙": "起步笨拙不怕。",
  "单薄": "穿着单薄要加衣。",
  "模糊": "泪眼模糊了视线。",
  "恍然": "恍然大悟明白了。",
  "赠予": "知识是最美赠予。",
  "愁怨": "不要积攒愁怨。",
  "顺心": "事事顺心如意。",
  "妩媚": "柳条妩媚动人。",
  "安适": "生活安适美满。",
  "摇篮曲": "妈妈哼着摇篮曲。",
  "催眠曲": "催眠曲伴我入睡。",
  "舒畅": "心情格外舒畅。",
  "僵硬": "冻得手脚僵硬。",
  "照耀": "阳光照耀大地。",
  "顾虑": "消除顾虑大胆说。",
  "眺望": "登上山顶眺望。",
  "茫茫": "大海茫茫无际。",
  "巍峨": "巍峨的珠穆朗玛峰。",
  "耸立": "高楼耸立入云。",
  "槐树": "老槐树下讲故事。",
  "疙瘩": "解开心里的疙瘩。",
  "先驱": "致敬科学先驱。",
  "檀香": "檀香阵阵扑鼻。",
  "督促": "妈妈督促我练琴。",
  "储蓄": "储蓄好习惯从小养。",
  "缩短": "高铁缩短了距离。",
  "距离": "缩小与优秀的距离。",
  "启迪": "好书启迪智慧。",
  "受益": "开卷受益终身。",
  "躯干": "挺直躯干站如松。",
  "徘徊": "在书店里徘徊。",
  "蒸融": "冰雪蒸融成溪。",
  "游丝": "蛛网游丝轻轻晃。",
  "赤裸裸": "要留下痕迹来过。",
  "叹息": "不要空自叹息。",
  "惋惜": "大家惋惜地摇头。",
  "队列": "队列练习要整齐。",
  "咚咚": "心咚咚直跳。",
  "揪": "不要揪小树叶子。",
  "沙哑": "嗓子喊得沙哑。",
  "放肆": "不能放肆妄为。",
  "狞笑": "死神狞笑着逼近。",
  "势不可当": "洪水势不可当。",
  "跌跌撞撞": "跌跌撞撞也要前进。",
  "祭奠": "祭奠遇难同胞。",
  "清瘦": "爷爷清瘦却硬朗。",
  "搀扶": "搀扶老人过马路。",
  "祭扫": "清明祭扫先烈。",
  "放晴": "雨后放晴空气新。",
  "惟妙惟肖": "泥人捏得惟妙惟肖。",
  "汹涌": "波涛汹涌的大海。",
  "澎湃": "心潮澎湃难平。",
  "熄灭": "炉火慢慢熄灭。",
  "掀翻": "巨浪掀翻了小船。",
  "肆虐": "台风肆虐大地。",
  "抠": "抠出字帖练字。",
  "娇小": "蜂鸟身躯娇小。",
  "流淌": "清泉流淌山间。",
  "阻止": "阻止不文明行为。",
  "禁止": "禁止践踏草坪。",
  "焦躁": "不要焦躁要冷静。",
  "熄": "熄灯后要安静。",
  "咆哮": "狂风咆哮着吹。",
  "嗓子": "唱歌要保护好嗓子。",
  "跌": "跌倒了爬起来。",
  "呻吟": "伤员痛苦地呻吟。",
  "滥": "不能滥砍滥伐。",
  "窑洞": "陕北窑洞冬暖夏凉。",
  "呛": "烟呛得直咳嗽。",
  "抉择": "面临艰难抉择。",
  "沮": "不要沮丧要振作。",
  "谜": "宇宙之谜等探索。",

  // ============ 语文六年级下册（北京的春节/腊八粥/鲁滨逊漂流记等课文词语） ============
  "腊八": "腊八熬香甜的粥。",
  "粥": "腊八粥熬得浓稠。",
  "蒜": "腊八蒜翠绿可口。",
  "醋": "饺子蘸醋更香。",
  "分外": "除夕分外热闹。",
  "行善积德": "行善积德有好报。",
  "两面三刀": "不要做两面三刀的人。",
  "残缺": "圆明园遗址是残缺的美。",
  "萦绕": "歌声萦绕在耳边。",
  "优雅": "天鹅姿态优雅。",
  "静谧": "夜晚的村庄很静谧。",
  "卓越": "卓越成绩靠努力。",
  "弥漫": "花香弥漫在空气里。",
  "卓越贡献": "致敬卓越贡献的科学家。",
  "机械": "现代机械代替手工。",
  "领域": "科学领域奥秘多。",
  "逻辑": "说话要有逻辑。",
  "真理": "实践检验真理。",
  "疑问": "带着疑问去学习。",
  "敏感": "对知识要敏感。",
  "定律": "万有引力定律。",
  "建树": "科学家建树卓著。",
  "景仰": "我们对英雄充满景仰。",
  "签名": "请在名册上签名。",
  "频率": "声音的频率不同。",
  "阀门": "关闭水阀门。",
  "爆炸": "烟花在空中爆炸。",
  "心平气和": "心平气和地讨论。",
  "理所当然": "帮助同学理所当然。",
  "难以忘怀": "这次旅行难以忘怀。",
  "振作": "重新振作起来。",
  "清醒": "遇事保持清醒。",
  "缰绳": "挣脱了缰绳。",
  "铲除": "铲除不良习惯。",
  "秃": "树秃了草黄了。",
  "蛾": "飞蛾扑火。",
  "饲料": "小鸡爱吃饲料。",
  "屿": "宝岛台湾是岛屿。",
  "救星": "他是全队的救星。",
  "复兴": "为民族复兴读书。",
  "轻蔑": "不要轻蔑别人。",
  "手枪": "军人持手枪站岗。",
  "魁梧": "黑黝黝的樵夫很魁梧。",
  "寡妇": "桑娜帮助穷寡妇。",
  "嘀咕": "心里直嘀咕。",
  "扰乱": "不要扰乱课堂秩序。",
  "忧": "不要忧心忡忡。",
  "仪式": "升旗仪式庄严。",
  "抱歉": "抱歉来晚了。",
  "埋怨": "不要埋怨别人。",
  "糟糕": "考砸了心情糟糕。",
  "碰见": "街上碰见老同学。",
  "揍": "不许揍人。",
  "缸": "水缸养着金鱼。"
};

// 各册词表（逗号分隔，多词短语用空格连接，不可含逗号）
export const RAW_TEXTS: Record<string, string> = {
  // ---------- 英语（1-2年级人教新起点 / 3-6年级人教PEP） ----------
  'GRADE 1-Fall': 'school,book,ruler,pencil,eraser,pencil box,bag,teacher,hello,hi,goodbye,bye,name,my,your,face,ear,eye,nose,mouth,look,dog,cat,bird,tiger,monkey,elephant,panda,zoo,one,two,three,four,five,six,seven,eight,nine,ten,red,yellow,blue,green,black,white,brown,orange,pink,purple,apple,pear,banana,peach,grapes,watermelon,strawberry,fruit,sweet,ant,duck,egg,jet,kite,leg,hand,foot,head,arm,body,hair,good,morning,afternoon,night,day,sun,moon,star,sky,rain,snow,wind,cloud',
  'GRADE 1-Spring': 'classroom,desk,chair,blackboard,door,window,in,on,under,where,room,table,bed,lamp,sofa,toy,plane,ball,doll,car,bus,bike,teddy bear,rice,noodles,chicken,fish,vegetable,hungry,thirsty,juice,milk,water,tea,cake,bread,hamburger,hot dog,coffee,candy,kangaroo,lion,giraffe,deer,snake,cute,fat,thin,big,small,tall,short,long,family,dad,mum,brother,sister,grandma,grandpa,friend,boy,girl,yes,no,please,sorry,ok,dance,sing,draw,jump,run,walk,swim,fly,sleep,get up,go to school,go home,bus stop',
  'GRADE 2-Fall': 'grandfather,grandmother,father,mother,man,woman,park,grass,flower,tree,lake,hill,street,shop,cinema,supermarket,hospital,train,ship,taxi,jeep,boat,map,basketball,football,ping-pong,tennis,sports,music,art,math,chinese,english,science,computer,painting,game,farmer,driver,doctor,nurse,cook,worker,pupil,study,work,play,read,write,help,love,happy,sad,new,old,cold,hot,cool,warm,breakfast,lunch,dinner,time,clock,watch,spring,summer,autumn,winter,season,sunny,windy,cloudy,rainy,snowy,shirt,skirt,dress,socks,shoes,jacket,sweater,jeans,shorts,coat',
  'GRADE 2-Spring': 'skate,plant,hobby,team,win,can,wish,party,gift,card,balloon,candle,song,letter,picture,photo,picnic,outside,weather,wet,dry,slow,fast,left,right,stop,wait,turn,money,buy,sell,cheap,expensive,pretty,beautiful,nice,clean,dirty,open,close,light,dark,floor,wall,home,phone,fridge,soup,spoon,knife,fork,bowl,chopsticks,cup,glass,plate,beef,bottle,box,cap,hat,queen,king,robot,puppy,kitten,pig,sheep,cow,horse,hen,rabbit,bear,mouse,eleven,twelve,thirteen,fourteen,fifteen,sixteen,seventeen,eighteen,nineteen,twenty,student,classmate',
  'GRADE 3-Fall': 'pen,pencil,pencil box,bag,book,ruler,eraser,crayon,school,hello,hi,goodbye,bye,i\'m,name,my,your,this,miss,mum,are,fine,thanks,let\'s,go,to,now,wow,see,say,uh,great,bye-bye,mr,good morning,good afternoon,nice to meet you,stand up,sit down,face,ear,eye,nose,mouth,head,arm,hand,leg,foot,body,red,yellow,blue,green,black,white,brown,orange,pink,purple,funny,play with,real,dog,cat,bird,tiger,monkey,elephant,panda,duck,pig,bear,rabbit,zoo,animal,bread,juice,milk,water,cake,fish,rice,egg,chicken,one,two,three,four,five,six,seven,eight,nine,ten,have some,i\'d like,here you are,thank you,you\'re welcome,can i have some,how old are you,make a wish,cut the cake,share,eat,drink,taste,smell,touch,follow me',
  'GRADE 3-Spring': 'welcome,welcome back,she,he,today,from,china,uk,usa,canada,new friend,wait a minute,how beautiful,isn\'t,family members,lovely,father,mother,man,woman,brother,sister,grandmother,grandfather,dad,mum,boy,girl,teacher,student,friend,giraffe,deer,so,children,child,tall,short,long,fat,thin,big,small,tail,come here,look at that,has,hide,find,excuse me,silly,honey,apple,pear,orange,banana,grape,watermelon,strawberry,buy,fruit,car,map,boat,desk,chair,ball,cap,toy,box,plane,in,on,under,how many,so many,good idea,open it and see,live,live in,for sale,oh no,eleven,twelve,thirteen,fourteen,fifteen,sixteen,seventeen,eighteen,nineteen,twenty',
  'GRADE 4-Fall': 'classroom,window,blackboard,light,picture,door,floor,computer,tv,really,near,clean the classroom,let me,schoolbag,candy,notebook,storybook,key,wow so much,lost,chinese book,english book,maths book,quiet,friendly,hair,shoe,glasses,his,her,or,right,strong,bedroom,living room,study,kitchen,bathroom,bed,phone,table,sofa,fridge,home,room,are they,these are,i\'m hungry,what\'s for dinner,what would you like,help yourself,pass me the bowl,cut the vegetables,use the spoon,use the fork,ready,dinner\'s ready,parents,uncle,aunt,baby brother,football player,job,basketball,football,doctor,cook,driver,farmer,nurse,people,but,little,puppy,welcome to my home,my family has,that\'s only,add,beef,chicken,noodles,soup,vegetable,chopsticks,bowl,knife,fork,spoon',
  'GRADE 4-Spring': 'playground,library,art room,computer room,music room,first floor,second floor,teachers\' office,welcome to our school,this way please,do you have,yes we do,no it isn\'t,what time is it,it\'s 7 o\'clock,english class,music class,pe class,it\'s time for,it\'s time to get up,it\'s time to go to school,it\'s time to go home,it\'s time to go to bed,just a minute,over there,school starts at,am,pm,breakfast,lunch,dinner,cold outside,be careful,weather report,what\'s the weather like,it\'s rainy today,not much,how about,degree,world,cold,cool,warm,hot,sunny,windy,cloudy,snowy,rainy,tomato,potato,green beans,carrot,horse,cow,sheep,hen,farm,these,those,animal,garden,eat up,clothes,pants,dress,skirt,coat,sweater,sock,shorts,jacket,shirt,whose,whose coat is this,it\'s mine,they\'re my father\'s,put away,put on,take off,hang up,wash,shoes,umbrella,sunglasses,scarf,gloves,how much is it,i\'ll take it,size,of course,too,more,assistant,expensive,cheap,pretty,nice',
  'GRADE 5-Fall': 'old,young,kind,strict,polite,hard-working,helpful,clever,shy,ms,mr,will,sometimes,robot,our,head teacher,very hard,is he strict,he\'s very kind,monday,tuesday,wednesday,thursday,friday,saturday,sunday,weekend,wash my clothes,watch tv,do homework,read books,play football,often,do you often,park,tired,sport,should,every day,schedule,sandwich,salad,hamburger,ice cream,tea,fresh,healthy,delicious,hot,drink,thirsty,favourite,what\'s your favourite,they\'re sweet,beef noodles,fish sandwich,tomato soup,dance,sing,draw,swim,cook,speak english,what can you do,kung fu,do kung fu,play the pipa,sing english songs,draw cartoons,play basketball,play ping-pong,clock,plant,bottle,photo,front,between,above,beside,behind,there is,there are,in my room,water bottle,so many plants,move into,just a minute,forest,river,lake,mountain,hill,tree,bridge,building,village,house,go boating,aren\'t,quiet,nature park,on the mountain,under the tree,no people,rabbit,high,wall',
  'GRADE 5-Spring': 'do morning exercises,eat breakfast,have class,play sports,eat dinner,when,exercise,usually,noon,o\'clock,why,shop,start,sound,take a dancing class,dancing,last,also,busy,need,play music,go for a walk,go shopping,clean my room,take,picnic,pick apples,go swimming,which,best,because,snow,vacation,leaf,leaves,colourful,paint a picture,merry,summer is here,january,february,march,april,may,june,july,august,september,october,november,december,few,thing,meet,chinese test,sports meet,easter,trip,year,month,first,second,third,fourth,fifth,twelfth,twentieth,twenty-first,thirtieth,special,fool,date,birthday party,playing,jumping,eating,drinking,sleeping,running,climbing,swinging,fighting,mine,yours,his,hers,theirs,ours,each other,care for,look there,drinking water,so cute,what are they doing,having class,eating lunch,reading a book,listening to music,keep to the right,keep your desk clean,talk quietly,take turns,quietly,show,anything else,exhibition,say no to,look for',
  'GRADE 6-Fall': 'science museum,post office,bookstore,cinema,hospital,crossing,turn left,turn right,go straight,next to,far,tell,gps,follow,feature,italian restaurant,get there,get to,on foot,by bus,by taxi,by subway,by train,by ship,by plane,by bike,slow down,stop and wait,traffic lights,helmet,must,wear,pay attention to,traffic,munich,germany,alaska,sled,ferry,scotland,so many ways,on a sled,visit,film,see a film,take a trip,supermarket,evening,tonight,tomorrow,next week,dictionary,comic book,word book,postcard,mid-autumn festival,mooncake,poem,moon,together,get together,study,puzzle,hiking,pen pal,hobby,jasmine flower,idea,canberra,amazing,shall,goal,join,club,share,factory worker,postman,businessman,police officer,fisherman,scientist,pilot,coach,country,sea,stay healthy,university,if,use,type,quickly,angry,afraid,sad,worried,happy,see a doctor,wear warm clothes,take a deep breath,count to ten,chase,mice,bad,hurt,ill,wrong,feel,well,sit,grass,hear,ant,everyone,mud,pull,what\'s wrong,how does dad feel,not well,go to the zoo,not really,run after,look so sad,science,teacher,student,farmer,driver,nurse,cook',
  'GRADE 6-Spring': 'younger,older,taller,shorter,longer,thinner,heavier,bigger,smaller,stronger,dinosaur,hall,meter,than,both,kilogram,countryside,lower,shadow,smarter,become,cleaned my room,washed my clothes,stayed at home,watched tv,drank tea,last weekend,last night,last monday,yesterday,before,read a book,saw a film,had a cold,slept,yesterday morning,what did you do,stayed at home and slept,cleaned the window,washed the dishes,went,camp,went camping,went fishing,rode a horse,hurt my foot,ate fresh food,took pictures,bought gifts,beach,basket,part,licked,laughed,ball,till,couldn\'t,dining hall,gym,ago,cycling,go cycling,ice-skate,badminton,star,easy,look up,internet,different,active,race,nothing,thought,felt,cheetah,woke,dream,was,were,will be,there was,there were,didn\'t',

  // ---------- 语文（部编版统编教材 1-6年级） ----------
  '语文一年级上册': '一天,二月,三人,上山,口水,目光,耳朵,手心,日子,田里,禾苗,火车,虫子,云朵,山水,八个,十个,儿子,大人,月儿,头发,里面,可是,东方,西方,天上,四个,女生,水里,来了,不会,小心,多少,牛羊,果子,小鸟,早上,书本,尺子,本子,木头,树林,泥土,力气,心里,中国,五个,立正,正在,后来,我们,好人,长大,尾巴,下雨,他们,问好,有人,半天,从来,你们,明天,同学,学习,自己,衣服,白天,竹子,牙齿,小马,用力,几个,一只,石头,很多,出去,看见,对面,妈妈,全家,回家,工人,工厂,太阳,星星,晚上,下雪,冬天,春天,夏天,秋天,夜晚,学校,老师,拍手,高兴,快乐,游戏,玩具,朋友,兄弟,姐妹,爸爸,爷爷,奶奶,谢谢,再见,你好,大家,一起,玩耍,唱歌,跳舞,画画,看书,写字,读书,听讲,举手,起立,坐下,窗户,桌子,椅子,铅笔,橡皮,花朵,小草,大树,叶子,河水,大海,鱼儿,乌龟,兔子,青蛙,鸭子,国旗,美丽,白云,土地,天空,树木,森林,什么,说话',
  '语文一年级下册': '春风,冬雪,花开,飞鸟,入水,国王,王子,红色,绿色,晴天,请问,清水,心情,事情,生动,千万,百花,齐心,电话,友谊,高山,语文,数学,音乐,伙伴,这里,那里,月亮,故乡,身体,运动,远近,听说,左右,因为,江南,荷叶,红豆,地方,没有,许多,种子,发芽,树叶,雨水,青草,河水清,温暖,冰冷,金色,银色,彩色,彩虹,阳光,影子,前后,旁边,中间,上面,下面,左右手,名字,生字,词语,句子,课文,故事,童话,汽车,飞机,轮船,走路,跑步,跳跃,游泳,骑车,书包,铅笔盒,本领,本领大,主意,办法,着急,高兴地,慢慢地,轻轻地,认真地,快乐地,邻居,家乡,亲人,热情,礼貌,帮助,感谢,劳动,干净,整齐,明亮,安静,温暖的家,爱护,保护,空气,新鲜,健康,平安,生气,开心',
  '语文二年级上册': '两个,哪里,宽大,头顶,眼睛,肚皮,孩子,跳高,变化,一片,傍晚,海洋,工作,坏事,办法,如果,毛笔,写信,圆珠笔,电灯,电影,今天,深处,熊猫,辛苦,农忙,归来,爱戴,英雄,队旗,铜号,欢笑,杨树,壮丽,梧桐,枫叶,松柏,棉花,杉树,化石,季节,蝴蝶,麦苗,桑叶,农家,植物,旅行,准备,降落伞,纷纷,观察,粗心,得到,知识,四海为家,脚尖,愉快,广场,围绕,池塘,名胜古迹,群山,凉快,百闻不如一见,展翅,滑冰,报纸,雪花,名不虚传,一动不动,淹没,冲毁,灾害,恢复,教训,治理,疏通,驱赶,房屋,其余,带领,哨兵,翻译,危险,讨好,百兽,违抗,纳闷,拔河,为难得,亲切,脚印,暖和,痛快,盛开,玩耍,喊叫,纷纷出发',
  '语文二年级下册': '春天,寻找,姑娘,野花,柳枝,桃花,杏花,冲出,原来,叔叔,邮局,礼物,先生,太太,做客,惊奇,快活,美好,植树,格外,引人注目,满意,休息,树苗,笔直,汗珠,甚至,花草,原野,五颜六色,精灵,叮咛,聊天,草坪,烟囱,一般,彩色,梦想,拉手,结果,苹果,喜欢,碧绿,剪刀,细雨,健康,洒脱,敲鼓,漫步,凉棚,难道,神气,住嘴,争论,评理,道理,一致,清晨,相遇,狐狸,老虎,肉,抬,值日,温暖,干涸,井,泉眼,尽,惜,照,晴,柔,荷,露',
  '语文三年级上册': '早晨,穿戴,鲜艳,服装,打扮,敬爱,敬礼,安静,树枝,好奇,招引,洁白,摇晃,影子,落下,荒野,跳舞,狂欢,互相,能够,猜出,扬起,双臂,朗读,飘扬,假日,亲人,教师,观察,蒲公英,合拢,手掌,玩耍,一本正经,引人注目,假睡,寒冷,雨珠,钥匙,颜料,频频,凉爽,丰收,加紧,过冬,歌曲,温柔,留意,香甜,蜂蜜,清甜,油亮亮,杨树,火红,邮票,菊花,仙子,丁香,盛气凌人,挖掘,水泥,亮晶晶,图案,排列,规则,凌乱,增添,棕红,迟到,经常,故宫,旅行,蚂蚁,兄台,住宅,临时,住址,洞穴,专家,顺畅,卧室,卫生间,选择,搜集,倾斜,隧道,搜索,扑空,趁机,痕迹,懒惰,平展,悲哀,镜子,消毒,忧虑,若明若暗,即使,警觉,锐利,十分,洞口,翘起,讨厌,发明,百发百中,一致,掌声,文静,默默,轮流,讲台,热烈,持久,平息,情况,鼓励,勇气,鞠躬,礼貌,司空见惯',
  '语文三年级下册': '燕子,乌黑,轻快,翅膀,剪刀,尾巴,活泼,微风,赶集,聚拢,光彩夺目,掠过,稻田,偶尔,沾水,荡漾,荷花,清香,莲蓬,破裂,姿势,仿佛,衣裳,舞蹈,翩翩起舞,蜻蜓,守株待兔,耕田,触株,颈部,释放,骄傲,谦虚,懦弱,尘土,捧起,擦洗,古代,价值,动手,狮子,鹿角,池塘,欣赏,匀称,精美,别致,犹豫,机灵,逼近,没精打采,争奇斗艳,芬芳,展示,修建,组成,蜜蜂,辨认,能力,阻力,包括,准确,无误,沿路,陌生,超常,记忆,本能,放下,实际,看法,幸福,集合,国家,云朵,沙滩,迅速,海参,海藻,危险,攻击,窃窃私语,属,内,营养,领土,差异,物质,宋,排,服饰,观望,旭日',
  '语文四年级上册': '观潮,据说,大堤,宽阔,笼罩,人山人海,屹立,若隐若现,昂首,顿时,人声鼎沸,浩浩荡荡,山崩地裂,霎时,余波,依旧,牵手,鹅卵石,坑坑洼洼,填平,庄稼,风俗,跃出,葡萄,稻谷,成熟,柔和,河床,新鲜,修补,科学,横贯,虚弱,愉快,呼风唤雨,世纪,技术,改变,程度,超过,幻想,原子核,奥秘,日益,联系,物质,哲学家,任何,改善,蝙蝠,雷达,避开,敏捷,捕捉,苍蝇,揭开,推进,障碍,荧光屏,恐龙,凶猛,笨重,迟钝,鸽子,末期,描绘,隧道,形态,膨大,前肢,具备,开辟,脱离,无忧无虑,生气勃勃,天高地阔,月明人静,一丝不苟,空空如也,枝折花落,从容不迫,扬长而去,没完没了,屏息凝视,变化多端,屋檐,装饰,顺序,华丽,独特,照例,率领,觅食,捣衣,向导,和谐,辛苦,蚕桑,耘田,慰藉,卜落,威力,锐利,河滩,帐子,闪烁,奇幻,帐单',
  '语文四年级下册': '寂静,譬如,慰藉,敏锐,例行,检查,庄严,胸脯,站岗,帐篷,倒霉,忧伤,处境,理智,控制,混乱,简陋,野蛮,忧郁,至于,淡忘,宽慰,荒岛,凄凉,寂寞,恐惧,宴会,栅栏,贷方,凄惨,欣慰,书籍,而已,聊天,复活,节日,鞭炮,腊月,大蒜,饺子,摊贩,彼此,贺年,骆驼,恰好,一律,彩绘,糊涂,搅和,浓稠,可靠,猜想,粉碎,外套,解释,教授,困境,既然,此时,万象更新,悬灯结彩,不可思议,见微知著,锲而不舍,追根求源,无独有偶,饶有趣味,焉知非福,截然不同,哄堂大笑,能歌善舞,随心所欲,绿毯,线条,柔美,惊叹,回味,乐趣,目的地,洒脱,衣裳,彩虹,马蹄,拘束,羞涩,摔跤,偏偏,河,敬酒,奏',
  '语文五年级上册': '白鹭,精巧,色素,适宜,生硬,流线型,镜子,孤独,悠闲,黄昏,恩惠,播种,浇水,吩咐,爱慕,体面,深浅,分辨,便宜,石榴,架子,尤其,缠着,盛开,及时,新鲜,完整,杭州,茶叶,飘落,迷信,紧邻,至少,懂得,担忧,上瘾,缠问,糕饼,浸泡,杭绸,收获,吩咐过,榨油,短促,茂盛,珍惜,迟延,协调,素净,愈,酬谢,珍宝,叮嘱,崩塌,发誓,谎话,牺牲,千真万确,牛郎,嫂子,床铺,笑嘻嘻,成家立业,相依为命,晚霞,温和,亲密,灿烂,怒发冲冠,难以置信,举世闻名,众星拱月,玲珑剔透,诗情画意,太平盛世,金碧辉煌,完好无缺,灰烬,奉命,肩负,漫游,悲哀,估量,瑰宝,建筑,宏伟,仿照,搜集,仿制,统统,销毁,罪证,朗诵,背诵,训斥,名夷,负荆请罪,同心协力,攻无不克,战无不胜,完璧归赵,理直气壮,无价之宝,绝口不提,神机妙算,喜不自胜,天造地设,踉踉跄跄,抓耳挠腮,伸头缩颈,力倦神疲',
  '语文五年级下册': '昼夜,耕耘,稚子,蚂蚱,樱桃,瞎闹,锄头,承认,随意,阴凉,割草,倭瓜,威吓,露馅,屏障,芝麻,神圣,侵犯,摔跤,乐此不疲,情不自禁,肃然起敬,摩拳擦掌,跃跃欲试,兴致勃勃,养尊处优,手忙脚乱,恍然大悟,哭笑不得,若有所思,半信半疑,瞑目蹲身,纵身,颤抖,慈祥,荣幸,眷恋,锻炼,繁忙,特殊,尊重,呐喊,陷坑,诡计,霹雳,酥软,耻笑,胸膛,拳头,恶意,败坏,祸事,袍子,嫌弃,讥笑,顽劣,家具,桥梁,寂寞,眉目,搔痒,屡次,锲而不舍,锈,断绝,拱桥,屏息,巅峰,锻炼,阔别,晶莹,蒸腾,跋涉,污迹,懊悔,狂奔,惊慌,渗透,拥挤,遮蔽,朦胧,玫瑰,继续,缠绵,模仿,聘请,燃烧,铃铛,枣红,挣断,揭穿,静候,谴责,碍事,怀疑,阵亡,招募,服从,残疾,犹豫,犹豫不决,创举,雕刻,遗产,智慧,才干,妒忌,军令状,迟延,探听,幔子,私自,调度,水寨,擂鼓,支援,丞相,限度,熬夜,吃惊,虚张声势,弓弩,迟,悬挂',
  '语文六年级上册': '绿毯,渲染,勾勒,洒脱,迂回,疾驰,马蹄,拘束,羞涩,摔跤,天涯,回味,幽雅,笨拙,单薄,模糊,恍然,赠予,愁怨,顺心,妩媚,安适,摇篮曲,催眠曲,舒畅,僵硬,照耀,顾虑,眺望,茫茫,巍峨,耸立,槐树,疙瘩,朦胧,先驱,檀香,督促,储蓄,缩短,距离,启迪,受益,躯干,徘徊,蒸融,游丝,赤裸裸,叹息,惋惜,队列,咚咚,揪,沙哑,凶猛,放肆,狞笑,势不可当,跌跌撞撞,祭奠,清瘦,搀扶,祭扫,放晴,惟妙惟肖,汹涌,澎湃,熄灭,掀翻,肆虐,抠,娇小,流淌,阻止,禁止,焦躁,熄,咆哮,嗓子,惊慌,跌,呻吟,滥,窑洞,呛,抉择,沮,谜',
  '语文六年级下册': '腊八,粥,蒜,醋,摊贩,彼此,贺年,骆驼,恰好,一律,彩绘,分外,搅和,可靠,猜想,粉碎,外套,解释,困境,恐惧,宴会,栅栏,帐篷,倒霉,忧伤,处境,理智,混乱,简陋,野蛮,忧郁,淡忘,宽慰,万象更新,悬灯结彩,不可思议,见微知著,司空见惯,追根求源,无独有偶,饶有趣味,焉知非福,截然不同,哄堂大笑,能歌善舞,行善积德,两面三刀,随心所欲,华丽,残缺,眷恋,萦绕,优雅,静谧,卓越,弥漫,卓越贡献,锲而不舍,机械,领域,逻辑,真理,疑问,敏感,定律,建树,景仰,签名,频率,惋惜,阀门,爆炸,心平气和,理所当然,难以忘怀,振作,清醒,缰绳,铲除,秃,蛾,饲料,屿,救星,复兴,轻蔑,手枪,恐惧,魁梧,寡妇,嘀咕,扰乱,忧,仪式,抱歉,埋怨,糟糕,碰见,揍,缸'
};

function parseTextToItems(text: string, lang: 'EN' | 'CN'): ExerciseItem[] {
  if (!text) return [];
  const keys = text.split(',').map(s => s.trim()).filter(s => s);

  return keys.map(key => {
    if (lang === 'EN') {
      const lowerKey = key.toLowerCase();
      const data = EN_METADATA[lowerKey];
      return {
        text: key,
        phonetic: data ? data[0] : "",
        translation: data ? data[1] : key,
        example: data ? data[2] : `Practice spelling: ${key}`
      };
    } else {
      const py = getPinyin(key);
      const example = CN_METADATA[key] || `请练习打字：${key}`;
      return {
        text: py,
        chinese: key,
        pinyin: py,
        example: example
      };
    }
  });
}

export const TEXTBOOK_RESOURCES: Record<string, Record<string, ExerciseItem[]>> = {
  '英语': {},
  '语文': {}
};

Object.keys(RAW_TEXTS).forEach(bookName => {
  const isEn = bookName.startsWith('GRADE');
  const lang = isEn ? '英语' : '语文';
  TEXTBOOK_RESOURCES[lang][bookName] = parseTextToItems(RAW_TEXTS[bookName], isEn ? 'EN' : 'CN');
});

export const RESOURCE_SUMS: Record<string, number> = {};
Object.keys(RAW_TEXTS).forEach(key => {
  RESOURCE_SUMS[key] = RAW_TEXTS[key].split(',').length;
});
