
import { ExerciseItem } from './types';
import { getPinyin } from './utils';

// 键盘布局
export const KEYBOARD_LAYOUT = [
  ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P'],
  ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L'],
  ['Z', 'X', 'C', 'V', 'B', 'N', 'M']
];

export const FINGER_MAPPING: Record<string, { finger: string; hand: 'left' | 'right' }> = {
  'Q': { finger: '小指', hand: 'left' }, 'A': { finger: '小指', hand: 'left' }, 'Z': { finger: '小指', hand: 'left' },
  'W': { finger: '无名指', hand: 'left' }, 'S': { finger: '无名指', hand: 'left' }, 'X': { finger: '无名指', hand: 'left' },
  'E': { finger: '中指', hand: 'left' }, 'D': { finger: '中指', hand: 'left' }, 'C': { finger: '中指', hand: 'left' },
  'R': { finger: '食指', hand: 'left' }, 'F': { finger: '食指', hand: 'left' }, 'V': { finger: '食指', hand: 'left' },
  'T': { finger: '食指', hand: 'left' }, 'G': { finger: '食指', hand: 'left' }, 'B': { finger: '食指', hand: 'left' },
  'Y': { finger: '食指', hand: 'right' }, 'H': { finger: '食指', hand: 'right' }, 'N': { finger: '食指', hand: 'right' },
  'U': { finger: '食指', hand: 'right' }, 'J': { finger: '食指', hand: 'right' }, 'M': { finger: '食指', hand: 'right' },
  'I': { finger: '中指', hand: 'right' }, 'K': { finger: '中指', hand: 'right' }, ',': { finger: '中指', hand: 'right' },
  'O': { finger: '无名指', hand: 'right' }, 'L': { finger: '无名指', hand: 'right' }, '.': { finger: '无名指', hand: 'right' },
  'P': { finger: '小指', hand: 'right' }, ';': { finger: '小指', hand: 'right' }, '/': { finger: '小指', hand: 'right' },
  ' ': { finger: '大拇指', hand: 'left' }
};

// --- DATA SOURCE: PEP Primary English & Ministry Chinese Textbooks ---
// All entries are standardized to ensure consistent quality and count (>40 items/unit)

const EN_METADATA: Record<string, [string, string, string]> = {
  // G1 Fall (Starter / Phonics)
  "apple": ["/ˈæpl/", "苹果", "A is for apple."],
  "ant": ["/ænt/", "蚂蚁", "Ants are small."],
  "bag": ["/bæg/", "包", "Open your bag."],
  "book": ["/bʊk/", "书", "Close your book."],
  "cat": ["/kæt/", "猫", "It is a fat cat."],
  "crayon": ["/ˈkreɪɒn/", "蜡笔", "I have a red crayon."],
  "dog": ["/dɒg/", "狗", "The dog runs fast."],
  "duck": ["/dʌk/", "鸭子", "The duck says quack."],
  "egg": ["/eg/", "鸡蛋", "I like eggs."],
  "elephant": ["/ˈelɪfənt/", "大象", "Look at the elephant."],
  "face": ["/feɪs/", "脸", "Touch your face."],
  "foot": ["/fʊt/", "脚", "Stomp your foot."],
  "green": ["/griːn/", "绿色", "The grass is green."],
  "gift": ["/gɪft/", "礼物", "A gift for you."],
  "hand": ["/hænd/", "手", "Clap your hands."],
  "hi": ["/haɪ/", "嗨", "Hi, nice to meet you."],
  "ice": ["/aɪs/", "冰", "Ice is cold."],
  "ice cream": ["/aɪs kriːm/", "冰淇淋", "Yummy ice cream."],
  "jet": ["/dʒet/", "喷气机", "Look at the jet."],
  "kite": ["/kaɪt/", "风筝", "Fly a kite."],
  "leg": ["/leg/", "腿", "Shake your legs."],
  "mouth": ["/maʊθ/", "嘴巴", "Open your mouth."],
  "nose": ["/nəʊz/", "鼻子", "Touch your nose."],
  "orange": ["/ˈɒrɪndʒ/", "橙子", "An orange is round."],
  "pen": ["/pen/", "钢笔", "I have a blue pen."],
  "pencil": ["/ˈpensl/", "铅笔", "Use a pencil."],
  "queen": ["/kwiːn/", "女王", "She is a queen."],
  "red": ["/red/", "红色", "A red apple."],
  "ruler": ["/ˈruːlə/", "尺子", "A long ruler."],
  "school": ["/skuːl/", "学校", "I go to school."],
  "teacher": ["/ˈtiːtʃə/", "老师", "Hello, teacher!"],
  "umbrella": ["/ʌmˈbrelə/", "雨伞", "An umbrella for rain."],
  "vegetable": ["/ˈvedʒtəbl/", "蔬菜", "Eat your vegetables."],
  "water": ["/ˈwɔːtə/", "水", "Drink some water."],
  "yellow": ["/ˈjeləʊ/", "黄色", "A yellow duck."],
  "zoo": ["/zuː/", "动物园", "Let's go to the zoo."],
  "hello": ["/həˈləʊ/", "你好", "Hello, friend."],
  "goodbye": ["/ˌgʊdˈbaɪ/", "再见", "Goodbye, see you."],
  "name": ["/neɪm/", "名字", "My name is Tom."],
  "what": ["/wɒt/", "什么", "What is your name?"],
  "my": ["/maɪ/", "我的", "This is my bag."],
  "your": ["/jɔː/", "你的", "Is this your book?"],

  // G1 Spring (Numbers, Colors, Animals)
  "one": ["/wʌn/", "一", "One finger."],
  "two": ["/tuː/", "二", "Two eyes."],
  "three": ["/θriː/", "三", "Three birds."],
  "four": ["/fɔː/", "四", "Four legs."],
  "five": ["/faɪv/", "五", "High five!"],
  "six": ["/sɪks/", "六", "Six ducks."],
  "seven": ["/ˈsevn/", "七", "Seven colours."],
  "eight": ["/eɪt/", "八", "Eight monkeys."],
  "nine": ["/naɪn/", "九", "Nine stars."],
  "ten": ["/ten/", "十", "Count to ten."],
  "baby": ["/ˈbeɪbi/", "婴儿", "A cute baby."],
  "bear": ["/beə/", "熊", "A brown bear."],
  "bird": ["/bɜːd/", "鸟", "Birds can fly."],
  "blue": ["/bluː/", "蓝色", "The sky is blue."],
  "brother": ["/ˈbrʌðə/", "兄弟", "He is my brother."],
  "brown": ["/braʊn/", "棕色", "Brown bear."],
  "cut": ["/kʌt/", "切/剪", "Cut the paper."],
  "dad": ["/dæd/", "爸爸", "I love my dad."],
  "dance": ["/dɑːns/", "跳舞", "Let's dance."],
  "draw": ["/drɔː/", "画画", "Draw a picture."],
  "ear": ["/ɪə/", "耳朵", "Listen with ears."],
  "eye": ["/aɪ/", "眼睛", "Close your eyes."],
  "family": ["/ˈfæmɪli/", "家庭", "A happy family."],
  "father": ["/ˈfɑːðə/", "父亲", "This is my father."],
  "fish": ["/fɪʃ/", "鱼", "Fish swim."],
  "friend": ["/frend/", "朋友", "We are friends."],
  "grandmother": ["/ˈgrænmʌðə/", "奶奶", "My grandmother."],
  "grandfather": ["/ˈgrænfɑːðə/", "爷爷", "My grandfather."],
  "jump": ["/dʒʌmp/", "跳", "Jump high."],
  "milk": ["/mɪlk/", "牛奶", "Drink milk."],
  "monkey": ["/ˈmʌŋki/", "猴子", "Funny monkey."],
  "mother": ["/ˈmʌðə/", "母亲", "My mother is kind."],
  "mum": ["/mʌm/", "妈妈", "Hi, mum."],
  "panda": ["/ˈpændə/", "熊猫", "Cute panda."],
  "pear": ["/peə/", "梨", "Yummy pear."],
  "run": ["/rʌn/", "跑", "Run fast."],
  "sing": ["/sɪŋ/", "唱", "Sing a song."],
  "sister": ["/ˈsɪstə/", "姐妹", "Little sister."],
  "tiger": ["/ˈtaɪgə/", "老虎", "Big tiger."],
  "white": ["/waɪt/", "白色", "White snow."],
  "black": ["/blæk/", "黑色", "Black cat."],

  // G2 Fall (Food, Body, Transport)
  "bus": ["/bʌs/", "公共汽车", "Take the bus."],
  "bike": ["/baɪk/", "自行车", "Ride a bike."],
  "taxi": ["/ˈtæksi/", "出租车", "Take a taxi."],
  "train": ["/treɪn/", "火车", "A fast train."],
  "ship": ["/ʃɪp/", "轮船", "A big ship."],
  "plane": ["/pleɪn/", "飞机", "Fly by plane."],
  "car": ["/kɑː/", "汽车", "Drive a car."],
  "jeep": ["/dʒiːp/", "吉普车", "A green jeep."],
  "lamp": ["/læmp/", "台灯", "Turn on the lamp."],
  "desk": ["/desk/", "课桌", "On the desk."],
  "chair": ["/tʃeə/", "椅子", "Under the chair."],
  "walkman": ["/ˈwɔːkmən/", "随身听", "Listen to walkman."],
  "park": ["/pɑːk/", "公园", "Play in the park."],
  "cinema": ["/ˈsɪnəmə/", "电影院", "Go to the cinema."],
  "hospital": ["/ˈhɒspɪtl/", "医院", "Go to the hospital."],
  "shop": ["/ʃɒp/", "商店", "Go to the shop."],
  "rice": ["/raɪs/", "米饭", "Eat rice."],
  "beef": ["/biːf/", "牛肉", "I like beef."],
  "bread": ["/bred/", "面包", "Bread and milk."],
  "chicken": ["/ˈtʃɪkɪn/", "鸡肉", "Fried chicken."],
  // "window": ["/ˈwɪndəʊ/", "窗户", "Open the window."],
  // "door": ["/dɔː/", "门", "Close the door."],
  "window": ["/ˈwɪndəʊ/", "窗户", "Open the window."],
  "door": ["/dɔː/", "门", "Close the door."],
  "floor": ["/flɔː/", "地板", "Sweep the floor."],
  "wall": ["/wɔːl/", "墙", "White wall."],
  "farmer": ["/ˈfɑːmə/", "农民", "He is a farmer."],
  "driver": ["/ˈdraɪvə/", "司机", "Bus driver."],
  "doctor": ["/ˈdɒktə/", "医生", "See a doctor."],
  "nurse": ["/nɜːs/", "护士", "A kind nurse."],
  "cook": ["/kʊk/", "厨师", "A good cook."],
  "music": ["/ˈmjuːzɪk/", "音乐", "I love music."],
  "science": ["/ˈsaɪəns/", "科学", "Science class."],
  "sports": ["/spɔːts/", "体育运动", "Do sports."],
  "chinese": ["/ˌtʃaɪˈniːz/", "语文/中文", "Chinese book."],
  "english": ["/ˈɪŋglɪʃ/", "英语", "Speak English."],
  "math": ["/mæθ/", "数学", "Math problem."],
  "painting": ["/ˈpeɪntɪŋ/", "绘画", "Nice painting."],
  "computer": ["/kəmˈpjuːtə/", "电脑", "Use computer."],
  "game": ["/geɪm/", "游戏", "Play a game."],
  // "zoo": ["/zuː/", "动物园", "Let's go to the zoo."], // Duplicate

  // G2 Spring (Seasons, Time, Activities)
  "spring": ["/sprɪŋ/", "春天", "Spring is green."],
  "summer": ["/ˈsʌmə/", "夏天", "Summer is hot."],
  "autumn": ["/ˈɔːtəm/", "秋天", "Autumn is gold."],
  "winter": ["/ˈwɪntə/", "冬天", "Winter is white."],
  "season": ["/ˈsiːzn/", "季节", "Four seasons."],
  "swim": ["/swɪm/", "游泳", "Swim in summer."],
  "fly": ["/flaɪ/", "飞", "Birds fly."],
  "sleep": ["/sliːp/", "睡觉", "Go to sleep."],
  "skate": ["/skeɪt/", "滑冰", "Skate on ice."],
  "plant": ["/plɑːnt/", "种植", "Plant trees."],
  "clock": ["/klɒk/", "时钟", "Look at the clock."],
  "time": ["/taɪm/", "时间", "What time is it?"],
  "day": ["/deɪ/", "天", "A sunny day."],
  "night": ["/naɪt/", "夜晚", "Good night."],
  "breakfast": ["/ˈbrekfəst/", "早餐", "Eat breakfast."],
  "lunch": ["/lʌntʃ/", "午餐", "Have lunch."],
  "dinner": ["/ˈdɪnə/", "晚餐", "Big dinner."],
  "class": ["/klɑːs/", "课程", "English class."],
  "pe": ["/ˌpiː ˈiː/", "体育", "PE class."],
  "art": ["/ɑːt/", "美术", "Art room."],
  "cold": ["/kəʊld/", "冷", "It is cold."],
  "hot": ["/hɒt/", "热", "Very hot."],
  "cool": ["/kuːl/", "凉爽", "Cool weather."],
  "warm": ["/wɔːm/", "温暖", "Warm spring."],
  "sunny": ["/ˈsʌni/", "晴朗", "Sunny day."],
  "windy": ["/ˈwɪndi/", "多风", "Windy day."],
  "cloudy": ["/ˈklaʊdi/", "多云", "Cloudy sky."],
  "rainy": ["/ˈreɪni/", "下雨", "Rainy day."],
  "snowy": ["/ˈsnəʊi/", "下雪", "Snowy day."],
  "shirt": ["/ʃɜːt/", "衬衫", "Blue shirt."],
  "skirt": ["/skɜːt/", "短裙", "Red skirt."],
  "dress": ["/dres/", "连衣裙", "Pretty dress."],
  "socks": ["/sɒks/", "袜子", "White socks."],
  "shoes": ["/ʃuːz/", "鞋子", "New shoes."],
  "jacket": ["/ˈdʒækɪt/", "夹克", "Warm jacket."],
  "sweater": ["/ˈswetə/", "毛衣", "Wool sweater."],
  "jeans": ["/dʒiːnz/", "牛仔裤", "Blue jeans."],
  "shorts": ["/ʃɔːts/", "短裤", "Summer shorts."],
  "big": ["/bɪg/", "大", "Too big."],
  "small": ["/smɔːl/", "小", "Too small."],
  "long": ["/lɒŋ/", "长", "Long hair."],
  "short": ["/ʃɔːt/", "短", "Short tail."],

  // G3 Fall (Classroom, School items, Body parts)
  "eraser": ["/ɪˈreɪzə/", "橡皮", "Use an eraser."],
  "pencil box": ["/ˈpensl bɒks/", "铅笔盒", "Put it in the pencil box."],
  "head": ["/hed/", "头", "Nod your head."],
  "arm": ["/ɑːm/", "胳膊", "Wave your arm."],
  "body": ["/ˈbɒdi/", "身体", "Shake your body."],
  "purple": ["/ˈpɜːpl/", "紫色", "Purple grapes."],
  "pig": ["/pɪg/", "猪", "Pig is pink."],
  "cake": ["/keɪk/", "蛋糕", "Birthday cake."],
  "juice": ["/dʒuːs/", "果汁", "Apple juice."],
  // Duplicates removed from G3 Fall (pen, pencil, bag, book, ruler, crayon, face, nose, mouth, eye, ear, hand, leg, foot, red, yellow, green, blue, white, black, orange, brown, cat, dog, monkey, panda, duck, bird, bear, elephant, tiger, zoo, bread, milk, water, egg, fish, rice, one...ten)

  // G3 Spring (Family, Animals, Fruits, Positions)
  "boy": ["/bɔɪ/", "男孩", "He is a boy."],
  "girl": ["/gɜːl/", "女孩", "She is a girl."],
  "student": ["/ˈstjuːdnt/", "学生", "I am a student."],
  "man": ["/mæn/", "男人", "A tall man."],
  "woman": ["/ˈwʊmən/", "女人", "A kind woman."],
  "giraffe": ["/dʒəˈrɑːf/", "长颈鹿", "Tall giraffe."],
  "deer": ["/dɪə/", "鹿", "Run like a deer."],
  "tall": ["/tɔːl/", "高", "He is tall."],
  "fat": ["/fæt/", "胖", "Fat cat."],
  "thin": ["/θɪn/", "瘦", "Thin monkey."],
  "banana": ["/bəˈnɑːnə/", "香蕉", "Yellow banana."],
  "grape": ["/greɪp/", "葡萄", "Purple grape."],
  "watermelon": ["/ˈwɔːtəmelən/", "西瓜", "Big watermelon."],
  "strawberry": ["/ˈstrɔːbəri/", "草莓", "Red strawberry."],
  "buy": ["/baɪ/", "买", "Buy fruit."],
  "fruit": ["/fruːt/", "水果", "I like fruit."],
  "map": ["/mæp/", "地图", "Read a map."],
  "boat": ["/bəʊt/", "小船", "Row a boat."],
  "ball": ["/bɔːl/", "球", "Play ball."],
  "cap": ["/kæp/", "帽子", "Wear a cap."],
  // "toy": ["/tɔɪ/", "玩具", "Toy car."], // Kept here, unique in G3 Spring context vs G4 Fall
  "toy": ["/tɔɪ/", "玩具", "Toy car."],
  "box": ["/bɒks/", "盒子", "In the box."],
  "in": ["/ɪn/", "在...里", "In the bag."],
  "on": ["/ɒn/", "在...上", "On the bed."],
  "under": ["/ˈʌndə/", "在...下", "Under the tree."],
  "eleven": ["/ɪˈlevn/", "十一", "Eleven pens."],
  "twelve": ["/twelv/", "十二", "Twelve months."],
  "thirteen": ["/ˌθɜːˈtiːn/", "十三", "Thirteen birds."],
  "fourteen": ["/ˌfɔːˈtiːn/", "十四", "Fourteen dogs."],
  "fifteen": ["/ˌfɪfˈtiːn/", "十五", "Fifteen cats."],
  "sixteen": ["/ˌsɪksˈtiːn/", "十六", "Sixteen books."],
  "seventeen": ["/ˌsevnˈtiːn/", "十七", "Seventeen rulers."],
  "eighteen": ["/ˌeɪˈtiːn/", "十八", "Eighteen boys."],
  "nineteen": ["/ˌnaɪnˈtiːn/", "十九", "Nineteen girls."],
  "twenty": ["/ˈtwenti/", "二十", "Twenty points."],
  // Duplicates removed from G3 Spring (teacher, friend, father, mother, brother, sister, grandfather, grandmother, apple, pear, orange, car, desk, chair, plane)

  // G4 Fall (Classroom facilities, Jobs, Vegetables, House)
  "classroom": ["/ˈklɑːsruːm/", "教室", "Clean classroom."],
  "blackboard": ["/ˈblækbɔːd/", "黑板", "Look at the blackboard."],
  "light": ["/laɪt/", "电灯", "Turn on the light."],
  "picture": ["/ˈpɪktʃə/", "图画", "A nice picture."],
  "teacher's desk": ["/ˈtiːtʃəz desk/", "讲台", "Near the teacher's desk."],
  "fan": ["/fæn/", "风扇", "Turn on the fan."],
  "strong": ["/strɒŋ/", "强壮的", "He is strong."],
  "friendly": ["/ˈfrendli/", "友好的", "She is friendly."],
  "quiet": ["/ˈkwaɪət/", "安静的", "Be quiet."],
  "hair": ["/heə/", "头发", "Long hair."],
  "shoe": ["/ʃuː/", "鞋", "Blue shoes."],
  "glasses": ["/ˈglɑːsɪz/", "眼镜", "Wear glasses."],
  "hat": ["/hæt/", "帽子", "Nice hat."],
  "candy": ["/ˈkændi/", "糖果", "Sweet candy."],
  "key": ["/kiː/", "钥匙", "Key to the door."],
  "notebook": ["/ˈnəʊtbʊk/", "笔记本", "Write in notebook."],
  "bedroom": ["/ˈbedruːm/", "卧室", "Sleep in bedroom."],
  "living room": ["/ˈlɪvɪŋ ruːm/", "客厅", "Watch TV in living room."],
  "study": ["/ˈstʌdi/", "书房", "Read in study."],
  "kitchen": ["/ˈkɪtʃɪn/", "厨房", "Cook in kitchen."],
  "bathroom": ["/ˈbɑːθruːm/", "浴室", "Take a bath."],
  "bed": ["/bed/", "床", "Make the bed."],
  "phone": ["/fəʊn/", "电话", "Answer the phone."],
  "table": ["/ˈteɪbl/", "桌子", "Set the table."],
  "sofa": ["/ˈsəʊfə/", "沙发", "Sit on sofa."],
  "fridge": ["/frɪdʒ/", "冰箱", "Open the fridge."],
  "noodles": ["/ˈnuːdlz/", "面条", "Yummy noodles."],
  "soup": ["/suːp/", "汤", "Hot soup."],
  "chopsticks": ["/ˈtʃɒpstɪks/", "筷子", "Use chopsticks."],
  "spoon": ["/spuːn/", "勺子", "Soup spoon."],
  "knife": ["/naɪf/", "刀", "Knife and fork."],
  "fork": ["/fɔːk/", "叉子", "Use a fork."],
  "bowl": ["/bəʊl/", "碗", "A bowl of rice."],
  "people": ["/ˈpiːpl/", "人们", "Many people."],
  "but": ["/bʌt/", "但是", "Small but strong."],
  "little": ["/ˈlɪtl/", "小的", "Little puppy."],
  "puppy": ["/ˈpʌpi/", "小狗", "Cute puppy."],
  "football": ["/ˈfʊtbɔːl/", "足球", "Play football."],
  "basketball": ["/ˈbɑːskɪtbɔːl/", "篮球", "Play basketball."],
  // Duplicates removed (window, door, floor, wall, computer, beef, chicken, vegetable, doctor, cook, driver, farmer, nurse, toy)

  // G4 Spring (School, Time, Weather, Clothes, Animals, Shopping)
  "playground": ["/ˈpleɪgraʊnd/", "操场", "Run on playground."],
  "library": ["/ˈlaɪbrəri/", "图书馆", "Read in library."],
  "art room": ["/ɑːt ruːm/", "美术室", "Draw in art room."],
  "computer room": ["/kəmˈpjuːtə ruːm/", "计算机房", "Use computers."],
  "music room": ["/ˈmjuːzɪk ruːm/", "音乐教室", "Sing in music room."],
  "first floor": ["/fɜːst flɔː/", "一楼", "On the first floor."],
  "second floor": ["/ˈsekənd flɔː/", "二楼", "On the second floor."],
  "teachers' office": ["/ˈtiːtʃəz ˈɒfɪs/", "教师办公室", "Go to office."],
  "english class": ["/ˈɪŋglɪʃ klɑːs/", "英语课", "English class begins."],
  "music class": ["/ˈmjuːzɪk klɑːs/", "音乐课", "I love music class."],
  "pe class": ["/piː iː klɑːs/", "体育课", "Run in PE class."],
  "get up": ["/get ʌp/", "起床", "Get up early."],
  "go to school": ["/gəʊ tuː skuːl/", "去上学", "Time to go to school."],
  "go home": ["/gəʊ həʊm/", "回家", "Let's go home."],
  "go to bed": ["/gəʊ tuː bed/", "睡觉", "Go to bed at 9."],
  "tomato": ["/təˈmɑːtəʊ/", "西红柿", "Red tomato."],
  "potato": ["/pəˈteɪtəʊ/", "土豆", "Big potato."],
  "green bean": ["/griːn biːn/", "四季豆", "Green beans."],
  "carrot": ["/ˈkærət/", "胡萝卜", "Orange carrot."],
  "horse": ["/hɔːs/", "马", "Ride a horse."],
  "cow": ["/kaʊ/", "母牛", "Milk a cow."],
  "sheep": ["/ʃiːp/", "绵羊", "White sheep."],
  "hen": ["/hen/", "母鸡", "Hen lays eggs."],
  "clothes": ["/kləʊðz/", "衣服", "Wash clothes."],
  "pants": ["/pænts/", "裤子", "Blue pants."],
  // "hat": ... // Duplicate
  "coat": ["/kəʊt/", "外衣", "Winter coat."],
  "sock": ["/sɒk/", "短袜", "Put on socks."],
  "glove": ["/glʌv/", "手套", "Warm gloves."],
  "scarf": ["/skɑːf/", "围巾", "Red scarf."],
  "sunglasses": ["/ˈsʌnglæsɪz/", "太阳镜", "Cool sunglasses."],
  "pretty": ["/ˈprɪti/", "漂亮的", "She is pretty."],
  "expensive": ["/ɪkˈspensɪv/", "昂贵的", "Too expensive."],
  "cheap": ["/tʃiːp/", "便宜的", "Very cheap."],
  "nice": ["/naɪs/", "好的", "Nice to meet you."],
  // Duplicates removed (breakfast, lunch, dinner, cold, hot, cool, warm, sunny, windy, cloudy, snowy, rainy, dress, skirt, sweater, shorts, jacket, shirt, umbrella)

  // G5 Fall (Character, Week, Food, Abilities, House/Nature)
  "old": ["/əʊld/", "年老的", "My grandpa is old."],
  "young": ["/jʌŋ/", "年轻的", "She is young."],
  "funny": ["/ˈfʌni/", "滑稽的", "He is funny."],
  "kind": ["/kaɪnd/", "和蔼的", "A kind teacher."],
  "strict": ["/strɪkt/", "严格的", "Strict teacher."],
  "polite": ["/pəˈlaɪt/", "有礼貌的", "Be polite."],
  "hard-working": ["/hɑːd ˈwɜːkɪŋ/", "勤奋的", "Hard-working student."],
  "helpful": ["/ˈhelpfl/", "乐于助人的", "He is helpful."],
  "clever": ["/ˈklevə/", "聪明的", "Clever fox."],
  "shy": ["/ʃaɪ/", "害羞的", "Don't be shy."],
  "monday": ["/ˈmʌndeɪ/", "星期一", "Start of week."],
  "tuesday": ["/ˈtjuːzdeɪ/", "星期二", "On Tuesday."],
  "wednesday": ["/ˈwenzdeɪ/", "星期三", "Mid-week."],
  "thursday": ["/ˈθɜːzdeɪ/", "星期四", "Almost Friday."],
  "friday": ["/ˈfraɪdeɪ/", "星期五", "TGIF."],
  "saturday": ["/ˈsætədeɪ/", "星期六", "Weekend."],
  "sunday": ["/ˈsʌndeɪ/", "星期日", "Rest day."],
  "weekend": ["/ˌwiːkˈend/", "周末", "Happy weekend."],
  "wash": ["/wɒʃ/", "洗", "Wash clothes."],
  "watch": ["/wɒtʃ/", "看", "Watch TV."],
  "do": ["/duː/", "做", "Do homework."],
  // "read": ... // Unique here (G5 Fall) but read is in G5 Spring below? Actually read in G5 Fall, G6 Spring? Wait.
  "read": ["/riːd/", "读", "Read books."],
  // "play": ... // Unique here
  "play": ["/pleɪ/", "玩", "Play football."],
  "sandwich": ["/ˈsænwɪtʃ/", "三明治", "Ham sandwich."],
  "salad": ["/ˈsæləd/", "沙拉", "Fruit salad."],
  "hamburger": ["/ˈhæmbɜːgə/", "汉堡包", "Beef hamburger."],
  "tea": ["/tiː/", "茶", "Hot tea."],
  "fresh": ["/freʃ/", "新鲜的", "Fresh fruit."],
  "healthy": ["/ˈhelθi/", "健康的", "Healthy food."],
  "delicious": ["/dɪˈlɪʃəs/", "美味的", "It is delicious."],
  "sweet": ["/swiːt/", "甜的", "Sweet candy."],
  "speak": ["/spiːk/", "说", "Speak English."],
  "ping-pong": ["/pɪŋ pɒŋ/", "乒乓球", "Play ping-pong."],
  "bottle": ["/ˈbɒtl/", "瓶子", "Water bottle."],
  "photo": ["/ˈfəʊtəʊ/", "照片", "Take a photo."],
  "front": ["/frʌnt/", "前面", "In front of."],
  "between": ["/bɪˈtwiːn/", "中间", "Between us."],
  "above": ["/əˈbʌv/", "上面", "Above the bed."],
  "beside": ["/bɪˈsaɪd/", "旁边", "Beside me."],
  "behind": ["/bɪˈhaɪnd/", "后面", "Behind the door."],
  "forest": ["/ˈfɒrɪst/", "森林", "In the forest."],
  "river": ["/ˈrɪvə/", "河流", "Long river."],
  "lake": ["/leɪk/", "湖泊", "Blue lake."],
  "mountain": ["/ˈmaʊntən/", "高山", "High mountain."],
  "hill": ["/hɪl/", "小山", "Up the hill."],
  "tree": ["/triː/", "树", "Green tree."],
  "bridge": ["/brɪdʒ/", "桥", "Cross the bridge."],
  "building": ["/ˈbɪldɪŋ/", "建筑物", "Tall building."],
  "village": ["/ˈvɪlɪdʒ/", "村庄", "Small village."],
  "house": ["/haʊs/", "房子", "My house."],
  // Duplicates removed (ice cream, dance, sing, draw, swim, cook, basketball, clock, plant)

  // G5 Spring (Daily routine, Seasons, Dates, Rules)
  "eat breakfast": ["/iːt ˈbrekfəst/", "吃早饭", "Eat breakfast at 7."],
  "do morning exercises": ["/duː ˈmɔːnɪŋ ˈeksəsaɪzɪz/", "做早操", "Exercise daily."],
  "have class": ["/hæv klɑːs/", "上课", "Have class now."],
  "eat lunch": ["/iːt lʌntʃ/", "吃午饭", "Lunch time."],
  "read a book": ["/riːd ə bʊk/", "看书", "Read a book."],
  "listen to music": ["/ˈlɪsn tuː ˈmjuːzɪk/", "听音乐", "Listen to music."],
  "play sports": ["/pleɪ spɔːts/", "进行体育运动", "Play sports."],
  "eat dinner": ["/iːt ˈdɪnə/", "吃晚饭", "Dinner with family."],
  "clean my room": ["/kliːn maɪ ruːm/", "打扫房间", "Clean my room."],
  "go for a walk": ["/gəʊ fɔː ə wɔːk/", "散步", "Go for a walk."],
  "go shopping": ["/gəʊ ˈʃɒpɪŋ/", "去买东西", "Go shopping."],
  "take": ["/teɪk/", "学习/上(课)", "Take a class."],
  "dancing": ["/ˈdɑːnsɪŋ/", "跳舞", "Go dancing."],
  "picnic": ["/ˈpɪknɪk/", "野餐", "Go on a picnic."],
  "pick": ["/pɪk/", "摘", "Pick apples."],
  "snowman": ["/ˈsnəʊmæn/", "雪人", "Make a snowman."],
  "go swimming": ["/gəʊ ˈswɪmɪŋ/", "去游泳", "Go swimming."],
  "january": ["/ˈdʒænjuəri/", "一月", "New Year."],
  "february": ["/ˈfebruəri/", "二月", "Cold month."],
  "march": ["/mɑːtʃ/", "三月", "March begins."],
  "april": ["/ˈeɪprəl/", "四月", "April showers."],
  "may": ["/meɪ/", "五月", "May flowers."],
  "june": ["/dʒuːn/", "六月", "Children's Day."],
  "july": ["/dʒuˈlaɪ/", "七月", "Summer holiday."],
  "august": ["/ɔːˈgʌst/", "八月", "Hot August."],
  "september": ["/sepˈtembə/", "九月", "School starts."],
  "october": ["/ɒkˈtəʊbə/", "十月", "National Day."],
  "november": ["/nəʊˈvembə/", "十一月", "Thanksgiving."],
  "december": ["/dɪˈsembə/", "十二月", "Christmas."],
  "first": ["/fɜːst/", "第一", "1st."],
  "second": ["/ˈsekənd/", "第二", "2nd."],
  "third": ["/θɜːd/", "第三", "3rd."],
  "fourth": ["/fɔːθ/", "第四", "4th."],
  "fifth": ["/fɪfθ/", "第五", "5th."],
  "twelfth": ["/twelfθ/", "第十二", "12th."],
  "twentieth": ["/ˈtwentiəθ/", "第二十", "20th."],
  "climb": ["/klaɪm/", "攀登", "Climb mountains."],
  "eat": ["/iːt/", "吃", "Eat food."],
  "drink": ["/drɪŋk/", "喝", "Drink water."],
  // Duplicates removed (spring...winter, season, play, jump, sleep)

  // G6 Fall (Directions, Transport, Dictionary, Hobby, Jobs, Feelings)
  "museum": ["/mjuˈziːəm/", "博物馆", "Visit museum."],
  "post office": ["/pəʊst ˈɒfɪs/", "邮局", "Send letter."],
  "bookstore": ["/ˈbʊkstɔː/", "书店", "Buy books."],
  "crossing": ["/ˈkrɒsɪŋ/", "十字路口", "At the crossing."],
  "turn": ["/tɜːn/", "转弯", "Turn left."],
  "left": ["/left/", "左", "Turn left."],
  "right": ["/raɪt/", "右", "Turn right."],
  "straight": ["/streɪt/", "笔直地", "Go straight."],
  "subway": ["/ˈsʌbweɪ/", "地铁", "By subway."],
  "stop": ["/stɒp/", "停", "Stop here."],
  "wait": ["/weɪt/", "等待", "Wait for me."],
  "go": ["/gəʊ/", "去", "Let's go."],
  "dictionary": ["/ˈdɪkʃənri/", "词典", "Look up word."],
  "comic": ["/ˈkɒmɪk/", "连环画", "Comic book."],
  "word": ["/wɜːd/", "单词", "New word."],
  "postcard": ["/ˈpəʊstkɑːd/", "明信片", "Send postcard."],
  "visit": ["/ˈvɪzɪt/", "拜访", "Visit friends."],
  "film": ["/fɪlm/", "电影", "See a film."],
  "trip": ["/trɪp/", "旅行", "Take a trip."],
  "supermarket": ["/ˈsuːpəmɑːkɪt/", "超市", "Go to supermarket."],
  "evening": ["/ˈiːvnɪŋ/", "晚上", "This evening."],
  "tonight": ["/təˈnaɪt/", "今晚", "Tonight."],
  "tomorrow": ["/təˈmɒrəʊ/", "明天", "Tomorrow morning."],
  "next": ["/nekst/", "下周", "Next week."],
  "teach": ["/tiːtʃ/", "教", "Teach English."],
  "singer": ["/ˈsɪŋə/", "歌唱家", "Famous singer."],
  "writer": ["/ˈraɪtə/", "作家", "Good writer."],
  "actor": ["/ˈæktə/", "男演员", "Movie actor."],
  "artist": ["/ˈɑːtɪst/", "画家", "Great artist."],
  "policeman": ["/pəˈliːsmən/", "男警察", "Police officer."],
  "reporter": ["/rɪˈpɔːtə/", "记者", "News reporter."],
  "fisherman": ["/ˈfɪʃəmən/", "渔民", "Catch fish."],
  "scientist": ["/ˈsaɪəntɪst/", "科学家", "Smart scientist."],
  "pilot": ["/ˈpaɪlət/", "飞行员", "Fly a plane."],
  "coach": ["/kəʊtʃ/", "教练", "Football coach."],
  "angry": ["/ˈæŋgri/", "生气的", "Don't be angry."],
  "afraid": ["/əˈfreɪd/", "害怕", "Afraid of dogs."],
  "sad": ["/sæd/", "难过的", "I feel sad."],
  "worried": ["/ˈwʌrid/", "担心的", "Don't be worried."],
  "happy": ["/ˈhæpi/", "高兴的", "Be happy."],
  "count": ["/kaʊnt/", "数数", "Count to ten."],
  // Duplicates removed (science, cinema, hospital, train, bus, taxi, ship, plane, foot)

  // G6 Spring (Comparatives, Past Tense, Camping)
  "younger": ["/ˈjʌŋə/", "更年轻", "You are younger."],
  "older": ["/ˈəʊldə/", "更年长", "I am older."],
  "taller": ["/ˈtɔːlə/", "更高", "He is taller."],
  "shorter": ["/ˈʃɔːtə/", "更矮", "She is shorter."],
  "longer": ["/ˈlɒŋə/", "更长", "Longer hair."],
  "thinner": ["/ˈθɪnə/", "更瘦", "Thinner now."],
  "heavier": ["/ˈheviə/", "更重", "Heavier bag."],
  "bigger": ["/ˈbɪgə/", "更大", "Bigger house."],
  "smaller": ["/ˈsmɔːlə/", "更小", "Smaller car."],
  "stronger": ["/ˈstrɒŋə/", "更强壮", "Stronger man."],
  "dinosaur": ["/ˈdaɪnəsɔː/", "恐龙", "Big dinosaur."],
  "hall": ["/hɔːl/", "大厅", "Dining hall."],
  "meter": ["/ˈmiːtə/", "米", "One meter."],
  "kilogram": ["/ˈkɪləgræm/", "千克", "50 kilograms."],
  "lower": ["/ˈləʊə/", "更低", "Lower price."],
  "shadow": ["/ˈʃædəʊ/", "影子", "Long shadow."],
  "smart": ["/smɑːt/", "聪明的", "Smart dog."],
  "become": ["/bɪˈkʌm/", "变成", "Become strong."],
  "countryside": ["/ˈkʌntrisaɪd/", "乡村", "In the countryside."],
  "cleaned": ["/kliːnd/", "打扫(过)", "Cleaned room."],
  "stayed": ["/steɪd/", "停留(过)", "Stayed home."],
  "washed": ["/wɒʃt/", "洗(过)", "Washed face."],
  "watched": ["/wɒtʃt/", "看(过)", "Watched TV."],
  "had": ["/hæd/", "患病/有(过)", "Had a cold."],
  "slept": ["/slept/", "睡觉(过)", "Slept late."],
  "saw": ["/sɔː/", "看见(过)", "Saw a film."],
  "last": ["/lɑːst/", "上一个", "Last night."],
  "yesterday": ["/ˈjestədeɪ/", "昨天", "Yesterday."],
  "before": ["/bɪˈfɔː/", "在...之前", "Before now."],
  "went": ["/went/", "去(过)", "Went fishing."],
  "camp": ["/kæmp/", "野营", "Go camping."],
  "fishing": ["/ˈfɪʃɪŋ/", "钓鱼", "Go fishing."],
  "hurt": ["/hɜːt/", "受伤", "Hurt my foot."],
  "ate": ["/et/", "吃(过)", "Ate food."],
  "bought": ["/bɔːt/", "买(过)", "Bought a gift."],
  "took": ["/tʊk/", "拍照(过)", "Took pictures."],
  "mule": ["/mjuːl/", "骡子", "Ride a mule."],
  "beach": ["/biːtʃ/", "海滩", "On the beach."],
  "basket": ["/ˈbɑːskɪt/", "篮子", "Fruit basket."],
  "part": ["/pɑːt/", "角色", "Play a part."],
  "licked": ["/lɪkt/", "舔(过)", "Licked honey."],
  "laughed": ["/lɑːft/", "笑(过)", "Laughed aloud."],
  "rode": ["/rəʊd/", "骑(过)", "Rode a horse."],
  "gym": ["/dʒɪm/", "体育馆", "Go to gym."],
  "grass": ["/grɑːs/", "草坪", "On the grass."]
  // Duplicates removed (read, gift)
};

const CN_METADATA: Record<string, string> = {
  // G1 Fall
  "一二三": "一二三，木头人。",
  "四五六": "四五六，翻跟斗。",
  "七八九": "七八九，手牵手。",
  "十百千": "十百千，万万年。",
  "上中下": "上中下，要注意。",
  "人口手": "人口手，不乱动。",
  "日月": "日月如梭，光阴似箭。",
  "水火": "水火无情。",
  "山石": "山石嶙峋。",
  "田土": "田土肥沃。",
  "禾苗": "禾苗青青。",
  "云雨": "云雨巫山。",
  "风雪": "风雪交加。",
  "花鸟": "花鸟虫鱼。",
  "爸妈": "爸妈辛苦了。",
  "马牛羊": "马牛羊，吃青草。",
  "鸡鸭鹅": "鸡鸭鹅，叫嘎嘎。",
  "小大": "小大由之。",
  "多少": "多少钱。",
  "前后": "前后左右。",
  "左右": "左右逢源。",
  "东南西北": "东南西北风。",
  "春夏秋冬": "春夏秋冬四季。",
  "男女": "男女平等。",
  "开关": "开关门窗。",
  "正反": "正反两面。",
  "来去": "来去匆匆。",
  "出入": "出入平安。",
  "坐立": "坐立不安。",
  "走跑": "走跑跳跃。",
  "白云": "白云飘飘。",
  "土地": "土地辽阔。",
  "天空": "天空湛蓝。",
  "树木": "树木葱茏。",
  "森林": "森林茂密。",
  "中国": "中国富强。",
  "国旗": "国旗飘扬。",
  "五星": "五星红旗。",
  "美丽": "美丽家园。",
  "你好": "你好，朋友。",
  "再见": "再见，老师。",
  "谢谢": "谢谢帮助。",
  "不客气": "不客气。",
  "对不起": "对不起。",
  "没关系": "没关系。",

  // G1 Spring
  "春风": "春风拂面。",
  "冬雪": "冬雪皑皑。",
  "花开": "花开富贵。",
  "飞鸟": "飞鸟惊蛇。",
  "入水": "入水能游。",
  "什么": "什么名字。",
  "多么": "多么美好。",
  "双人": "双人成行。",
  "国王": "国王陛下。",
  "王子": "王子公主。",
  "方圆": "方圆十里。",
  "生字": "学习生字。",
  "红色": "红色革命。",
  "绿色": "绿色环保。",
  "晴天": "晴天霹雳。",
  "请问": "请问路在何方。",
  "清水": "清水出芙蓉。",
  "心情": "心情愉快。",
  "事情": "事情经过。",
  "生动": "生动形象。",
  "万一": "万一有变。",
  "千万": "千万小心。",
  "百花": "百花齐放。",
  "齐心": "齐心协力。",
  "说话": "说话算数。",
  "电话": "电话联系。",
  "朋友": "朋友情深。",
  "友谊": "友谊长存。",
  "高山": "高山流水。",
  "江湖": "江湖救急。",
  "语文": "语文课本。",
  "数学": "数学难题。",
  "音乐": "音乐优美。",
  "伙伴": "我的伙伴。",
  "大家": "大家一起。",
  "这里": "这里风景独好。",
  "那里": "那里有人。",
  "太阳": "太阳当空照。",
  "月亮": "月亮弯弯。",
  "故乡": "思念故乡。",
  "高兴": "高兴极了。",
  "拍手": "拍手称快。",
  "身体": "身体健康。",
  "运动": "运动健身。",
  "远近": "远近闻名。",
  "听说": "听说你来了。",

  // G2 Fall
  "两个": "两个黄鹂鸣翠柳。",
  "哪里": "哪里有彩虹。",
  "宽大": "宽大的袍子。",
  "头顶": "头顶蓝天。",
  "眼睛": "眼睛雪亮。",
  "肚皮": "肚皮鼓鼓。",
  "孩子": "孩子是希望。",
  "跳高": "跳高比赛。",
  "变化": "变化多端。",
  "极点": "达到极点。",
  "一片": "一片丹心。",
  "傍晚": "傍晚时分。",
  "海洋": "海洋浩瀚。",
  "工作": "工作顺利。",
  "坏事": "坏事变好事。",
  "办法": "办法总比困难多。",
  "如果": "如果有时光机。",
  "更有": "更有甚者。",
  "毛笔": "毛笔书法。",
  "写信": "写信回家。",
  "圆珠笔": "圆珠笔画。",
  "电灯": "电灯明亮。",
  "电影": "电影精彩。",
  "今天": "今天星期几。",
  "别处": "别处风景。",
  "深处": "深处有人家。",
  "熊猫": "熊猫可爱。",
  "辛苦": "辛苦工作。",
  "农忙": "农忙时节。",
  "归来": "归来仍是少年。",
  "爱戴": "爱戴领袖。",
  "英雄": "英雄本色。",
  "队旗": "队旗飘飘。",
  "铜号": "铜号嘹亮。",
  "欢笑": "欢笑声声。",
  "杨树": "杨树高大。",
  "壮丽": "壮丽河山。",
  "梧桐": "梧桐落叶。",
  "枫叶": "枫叶似火。",
  "松柏": "松柏常青。",
  "棉花": "棉花洁白。",
  "杉树": "杉树笔直。",
  "化石": "化石珍贵。",
  "季节": "季节更替。",
  "蝴蝶": "蝴蝶飞舞。",
  "麦苗": "麦苗青青。",
  "桑叶": "桑叶养蚕。",
  "肥胖": "肥胖可爱。",
  "农家": "农家乐趣。",
  // "朋友": "朋友情深。", // Duplicate

  // G2 Spring
  "春天": "春天来了。",
  "寻找": "寻找宝藏。",
  "姑娘": "灰姑娘。",
  "野花": "野花飘香。",
  "柳枝": "柳枝摇曳。",
  "桃花": "桃花朵朵。",
  "杏花": "杏花微雨。",
  "冲出": "冲出重围。",
  // "原来": "原来如此。", // Duplicate line in source
  "叔叔": "警察叔叔。",
  "邮局": "邮局寄信。",
  "礼物": "生日礼物。",
  "先生": "先生你好。",
  "原来": "原来如此。",
  "太太": "富贵太太。",
  "做客": "去朋友家做客。",
  "惊奇": "感到惊奇。",
  "快活": "快活似神仙。",
  "美好": "美好生活。",
  "邓小平": "邓小平爷爷。",
  "植树": "植树造林。",
  "格外": "格外美丽。",
  "引人注目": "引人注目的成就。",
  "满意": "满意的笑容。",
  "休息": "休息一下。",
  "树苗": "小树苗。",
  "小心": "小心谨慎。",
  "笔直": "笔直的马路。",
  "汗珠": "晶莹的汗珠。",
  "甚至": "甚至更好。",
  "花草": "花草树木。",
  "原野": "广阔原野。",
  "葱葱": "郁郁葱葱。",
  "五颜六色": "五颜六色的花。",
  "精灵": "森林精灵。",
  "叮咛": "千叮咛万嘱咐。",
  "聊天": "聊天记录。",
  "草坪": "绿色草坪。",
  "葱郁": "葱郁的森林。",
  "烟囱": "高耸的烟囱。",
  "一般": "一般见识。",
  "彩色": "彩色照片。",
  "梦想": "梦想成真。",
  "拉手": "拉手言欢。",
  "结果": "开花结果。",
  "苹果": "红红的苹果。",
  "喜欢": "喜欢读书。",
  // "森林": "森林茂密。", // Duplicate

  // G3 Fall
  "早晨": "早晨好。",
  "穿戴": "穿戴整齐。",
  "鲜艳": "鲜艳夺目。",
  "服装": "民族服装。",
  "打扮": "打扮漂亮。",
  "敬爱": "敬爱的领袖。",
  // "国旗": "升国旗。", // Duplicate
  "敬礼": "敬礼致意。",
  "安静": "安静下来。",
  "树枝": "树枝折断。",
  "好奇": "好奇心强。",
  "招引": "招引顾客。",
  "洁白": "洁白无瑕。",
  "摇晃": "摇晃不定。",
  "影子": "影子相随。",
  "落下": "落下帷幕。",
  "荒野": "荒野求生。",
  "口笛": "吹口笛。",
  "跳舞": "跳舞毯。",
  "狂欢": "狂欢节。",
  "罚站": "被罚站。",
  "互相": "互相尊重。",
  "能够": "能够做到。",
  "猜出": "猜出谜底。",
  "扬起": "扬起风帆。",
  "双臂": "张开双臂。",
  "汉族": "汉族文化。",
  "绒球": "绒球花。",
  "坪坝": "坪坝上。",
  "飘扬": "红旗飘扬。",
  "朗读": "朗读课文。",
  "摔跤": "摔跤比赛。",
  "凤尾竹": "凤尾竹下。",
  "罚款": "罚款单。",
  "放假": "放假回家。",
  // "洁白": "洁白无瑕。", // Duplicate
  // "互相": "互相尊重。", // Duplicate
  "所见": "所见所闻。",
  "牧童": "牧童骑黄牛。",
  "振动": "振动翅膀。",
  "意欲": "意欲何为。",
  "捕鸣蝉": "意欲捕鸣蝉。",
  "忽然": "忽然醒悟。",
  "闭口": "闭口不言。",
  "立在": "立在枝头。",
  "水泥": "水泥路。",
  "亮晶晶": "亮晶晶的星星。",
  "图案": "精美图案。",
  "排列": "排列整齐。",
  "规则": "遵守规则。",
  "凌乱": "凌乱不堪。",
  "棕红": "棕红色的马。",
  "迟到": "上学迟到。",

  // G3 Spring
  "燕子": "小燕子。",
  "乌黑": "乌黑亮丽。",
  "轻快": "轻快步伐。",
  "翅膀": "翅膀硬了。",
  "剪刀": "剪刀手。",
  "尾巴": "尾巴翘起。",
  "活泼": "活泼可爱。",
  "机灵": "机灵鬼。",
  "微风": "微风拂面。",
  "赶集": "赶集去。",
  "聚拢": "聚拢过来。",
  "光彩夺目": "光彩夺目。",
  "增添": "增添色彩。",
  "生机": "生机勃勃。",
  "掠过": "掠过水面。",
  "稻田": "稻田守望者。",
  "偶尔": "偶尔一次。",
  "沾水": "沾水即化。",
  "荡漾": "碧波荡漾。",
  "荷花": "荷花仙子。",
  "清香": "清香扑鼻。",
  "碧绿": "碧绿荷叶。",
  "莲蓬": "莲蓬多子。",
  "破裂": "感情破裂。",
  "姿势": "姿势优美。",
  "仿佛": "仿佛昨日。",
  "衣裳": "美丽衣裳。",
  "舞蹈": "舞蹈演员。",
  "翩翩起舞": "翩翩起舞。",
  "蜻蜓": "蜻蜓点水。",
  "守株待兔": "守株待兔。",
  "耕田": "耕田种地。",
  "触株": "触株而死。",
  "颈部": "颈部按摩。",
  "释放": "释放压力。",
  "其他": "其他事项。",
  "骄傲": "骄傲自满。",
  "谦虚": "谦虚使人进步。",
  "懦弱": "性格懦弱。",
  "尘土": "尘土飞扬。",
  "捧起": "捧起双手。",
  "擦洗": "擦洗干净。",
  "古代": "古代文明。",
  "价值": "价值连城。",
  "动手": "动手能力。",
  // "国王": "国王的新衣。", // Duplicate
  "狮子": "狮子王。",
  "鹿角": "鹿角海棠。",
  "池塘": "池塘边。",
  "欣赏": "欣赏音乐。",
  "匀称": "身材匀称。",
  "精美": "精美礼品。",
  "别致": "别致造型。",

  // G4 Fall
  "观潮": "天下奇观。",
  "据说": "据说如此。",
  "大堤": "防洪大堤。",
  "宽阔": "宽阔胸怀。",
  "笼罩": "夜色笼罩。",
  "人山人海": "人山人海。",
  "屹立": "屹立不倒。",
  "若隐若现": "若隐若现。",
  "昂首": "昂首挺胸。",
  "顿时": "顿时醒悟。",
  "人声鼎沸": "人声鼎沸。",
  "浩浩荡荡": "浩浩荡荡。",
  "山崩地裂": "山崩地裂。",
  "霎时": "霎时间。",
  "余波": "余波未平。",
  "依旧": "风采依旧。",
  "牵手": "牵手同行。",
  "鹅卵石": "鹅卵石路。",
  "坑坑洼洼": "坑坑洼洼。",
  "填平": "填平沟壑。",
  "庄稼": "庄稼丰收。",
  "风俗": "风俗习惯。",
  "跃出": "跃出水面。",
  "葡萄": "葡萄美酒。",
  "稻谷": "稻谷飘香。",
  "成熟": "成熟稳重。",
  "柔和": "光线柔和。",
  "河床": "河床干涸。",
  "新鲜": "新鲜空气。",
  "修补": "修补衣物。",
  "即使": "即使这样。",
  "科学": "科学技术。",
  "横贯": "横贯东西。",
  "虚弱": "身体虚弱。",
  "愉快": "心情愉快。",
  "呼风唤雨": "呼风唤雨。",
  "世纪": "新世纪。",
  "技术": "技术含量。",
  "改变": "改变世界。",
  "程度": "程度不同。",
  "超过": "超过预期。",
  "幻想": "不切实际的幻想。",
  "原子核": "原子核能。",
  "奥秘": "探索奥秘。",
  "日益": "日益增长。",
  "联系": "联系实际。",
  "物质": "物质生活。",
  "哲学家": "哲学家。",
  "任何": "任何时候。",
  "改善": "改善生活。",

  // G4 Spring
  "屋檐": "屋檐下。",
  "装饰": "装饰品。",
  "顺序": "按顺序。",
  "华丽": "华丽转身。",
  "独特": "独特见解。",
  "照例": "照例进行。",
  "率领": "率领部队。",
  "觅食": "鸟儿觅食。",
  "捣衣": "捣衣砧。",
  "向导": "旅游向导。",
  "和谐": "和谐社会。",
  // "辛苦": "辛苦工作。", // Duplicate G2 Fall
  "蚕桑": "蚕桑养殖。",
  "耘田": "耘田除草。",
  "慰藉": "心灵慰藉。",
  "卜落": "卜落声。",
  "威力": "威力巨大。",
  "锐利": "锐利目光。",
  "河滩": "河滩烧烤。",
  "帐子": "蚊帐子。",
  "闪烁": "闪烁其词。",
  "奇幻": "奇幻漂流。",
  "蝙蝠": "蝙蝠侠。",
  "雷达": "倒车雷达。",
  "避开": "避开锋芒。",
  "敏捷": "思维敏捷。",
  "捕捉": "捕捉瞬间。",
  "苍蝇": "苍蝇拍。",
  "揭开": "揭开面纱。",
  "推进": "推进改革。",
  "障碍": "障碍赛跑。",
  "荧光屏": "荧光屏。",
  "恐龙": "恐龙化石。",
  "凶猛": "凶猛野兽。",
  "笨重": "笨重机器。",
  "迟钝": "反应迟钝。",
  "鸽子": "和平鸽。",
  "末期": "癌症末期。",
  "描绘": "描绘蓝图。",
  "隧道": "时空隧道。",
  "形态": "意识形态。",
  "膨大": "膨大剂。",
  "前肢": "前肢发达。",
  "具备": "具备条件。",
  "开辟": "开辟新路。",
  "脱离": "脱离危险。",
  "无忧无虑": "无忧无虑。",
  "因为": "因为所以。",
  "生气勃勃": "生气勃勃。",
  "天高地阔": "天高地阔。",
  "月明人静": "月明人静。",
  "一丝不苟": "一丝不苟。",
  "空空如也": "空空如也。",
  "枝折花落": "枝折花落。",
  "从容不迫": "从容不迫。",
  "扬长而去": "扬长而去。",
  "没完没了": "没完没了。",
  // "归来": "归来仍是少年。", // Duplicate

  // G5 Fall
  "白鹭": "一行白鹭上青天。",
  "精巧": "精巧绝伦。",
  "色素": "天然色素。",
  "适宜": "适宜居住。",
  "播种": "播种希望。",
  "浇水": "浇水施肥。",
  "吩咐": "听从吩咐。",
  "爱慕": "爱慕虚荣。",
  "体面": "体面工作。",
  "懒惰": "懒惰成性。",
  "尤其": "尤其是你。",
  "协调": "协调发展。",
  "酬谢": "酬谢金。",
  "珍宝": "稀世珍宝。",
  "叮嘱": "再三叮嘱。",
  "崩塌": "雪山崩塌。",
  "稀罕": "稀罕物。",
  "所谓": "所谓伊人。",
  "猎人": "猎人笔记。",
  "黎明": "黎明静悄悄。",
  "漆黑": "漆黑一片。",
  "完好无缺": "完好无缺。",
  "怒发冲冠": "怒发冲冠。",
  "难以置信": "难以置信。",
  "举世闻名": "举世闻名。",
  "众星拱月": "众星拱月。",
  "玲珑剔透": "玲珑剔透。",
  "诗情画意": "诗情画意。",
  "太平盛世": "太平盛世。",
  "美中不足": "美中不足。",
  "金碧辉煌": "金碧辉煌。",
  "绝口不提": "绝口不提。",
  "无价之宝": "无价之宝。",
  "理直气壮": "理直气壮。",
  "完璧归赵": "完璧归赵。",
  "攻无不克": "攻无不克。",
  "战无不胜": "战无不胜。",
  "负荆请罪": "负荆请罪。",
  "同心协力": "同心协力。",
  "自有妙用": "自有妙用。",
  "神机妙算": "神机妙算。",
  "踉踉跄跄": "踉踉跄跄。",
  "喜不自胜": "喜不自胜。",
  "天造地设": "天造地设。",
  "伸头缩颈": "伸头缩颈。",
  "抓耳挠腮": "抓耳挠腮。",
  "力倦神疲": "力倦神疲。",
  "人而无信": "人而无信，不知其可。",
  "饮水思源": "饮水思源。",
  "相依为命": "相依为命。",

  // G5 Spring
  "昼夜": "昼夜兼程。",
  "耕耘": "辛勤耕耘。",
  "稚子": "稚子无知。",
  "蚂蚱": "秋后的蚂蚱。",
  "樱桃": "樱桃小丸子。",
  "瞎闹": "别瞎闹。",
  "锄头": "挥舞锄头。",
  "承认": "承认错误。",
  "随意": "随意发挥。",
  "阴凉": "阴凉处。",
  // "蜻蜓": "蜻蜓点水。", // Duplicate
  "割草": "割草机。",
  "倭瓜": "大倭瓜。",
  "威吓": "威吓手段。",
  "露馅": "露馅了。",
  "屏障": "天然屏障。",
  "芝麻": "芝麻开花。",
  "神圣": "神圣使命。",
  "侵犯": "侵犯版权。",
  // "摔跤": "摔跤比赛。", // Duplicate
  "乐此不疲": "乐此不疲。",
  "情不自禁": "情不自禁。",
  "肃然起敬": "肃然起敬。",
  "摩拳擦掌": "摩拳擦掌。",
  "跃跃欲试": "跃跃欲试。",
  "兴致勃勃": "兴致勃勃。",
  "养尊处优": "养尊处优。",
  "手忙脚乱": "手忙脚乱。",
  "恍然大悟": "恍然大悟。",
  "哭笑不得": "哭笑不得。",
  "若有所思": "若有所思。",
  "半信半疑": "半信半疑。",
  // "神机妙算": "神机妙算。", // Duplicate
  // "自有妙用": "自有妙用。", // Duplicate
  // "踉踉跄跄": "踉踉跄跄。", // Duplicate
  "瞑目蹲身": "瞑目蹲身。",
  // "喜不自胜": "喜不自胜。", // Duplicate
  // "天造地设": "天造地设。", // Duplicate
  // "伸头缩颈": "伸头缩颈。", // Duplicate
  // "抓耳挠腮": "抓耳挠腮。", // Duplicate
  // "力倦神疲": "力倦神疲。", // Duplicate
  "纵身": "纵身一跃。",
  "颤抖": "瑟瑟颤抖。",
  "慈祥": "慈祥的面容。",
  "荣幸": "感到荣幸。",
  "眷恋": "眷恋故土。",
  "锻炼": "体育锻炼。",
  "繁忙": "工作繁忙。",
  "特殊": "特殊情况。",
  "尊重": "互相尊重。",

  // G6 Fall
  "绿毯": "像绿毯一样。",
  "线条": "线条流畅。",
  "柔美": "姿态柔美。",
  "惊叹": "令人惊叹。",
  "回味": "回味无穷。",
  "乐趣": "无穷乐趣。",
  "目的地": "到达目的地。",
  "洒脱": "性格洒脱。",
  // "衣裳": "美丽衣裳。", // Duplicate
  "惹人": "惹人喜爱。",
  "微笑": "微笑服务。",
  "愁怨": "心中愁怨。",
  "顺心": "事事顺心。",
  "也就是": "也就是这样。",
  "稍微": "稍微快点。",
  "比如": "比如说。",
  "笨拙": "动作笨拙。",
  "参差": "参差不齐。",
  "单薄": "衣着单薄。",
  "照耀": "阳光照耀。",
  "文豪": "一代文豪。",
  "模糊": "视线模糊。",
  "幽雅": "环境幽雅。",
  "或者是": "或者是我。",
  "飞驰": "飞驰人生。",
  "礼貌": "懂礼貌。",
  "拘束": "感到拘束。",
  "羞涩": "羞涩的笑。",
  // "摔跤": "摔跤比赛。", // Duplicate
  "宅院": "深宅大院。",
  "幽静": "幽静小路。",
  "纯熟": "技艺纯熟。",
  "陌生": "陌生人。",
  "清秀": "眉清目秀。",
  "陶醉": "自我陶醉。",
  "苏醒": "大地苏醒。",
  "呻吟": "痛苦呻吟。",
  "探望": "探望长辈。",
  "照顾": "照顾生活。",
  "敲门": "敲门砖。",
  "拜访": "拜访客户。",
  "刺猬": "像刺猬一样。",
  "翠色欲流": "翠色欲流。",
  "意味深长": "意味深长。",
  "硕大无朋": "硕大无朋。",
  "顾影自怜": "顾影自怜。",
  "孤芳自赏": "孤芳自赏。",
  "汹涌澎湃": "汹涌澎湃。",
  "斩钉截铁": "斩钉截铁。",
  "居高临下": "居高临下。",
  "排山倒海": "排山倒海。",
  "别出心裁": "别出心裁。",
  "技高一筹": "技高一筹。",
  "弄巧成拙": "弄巧成拙。",
  "作茧自缚": "作茧自缚。",
  "饱经风霜": "饱经风霜。",
  "囫囵吞枣": "囫囵吞枣。",
  "张冠李戴": "张冠李戴。",
  "大步流星": "大步流星。",
  "怒气冲冲": "怒气冲冲。",
  "暴露无遗": "暴露无遗。",
  "难以忘怀": "难以忘怀。",

  // G6 Spring
  "腊八": "腊八粥。",
  "粥": "八宝粥。",
  "蒜": "糖蒜。",
  "醋": "山西陈醋。",
  "饺子": "东北饺子。",
  "摊贩": "流动摊贩。",
  "彼此": "彼此彼此。",
  "贺年": "贺年卡片。",
  "骆驼": "骆驼祥子。",
  "恰好": "恰好经过。",
  "一律": "一律免单。",
  "彩绘": "彩绘玻璃。",
  "分外": "分外妖娆。",
  "糊涂": "难得糊涂。",
  "搅和": "瞎搅和。",
  "浓稠": "浓稠的粥。",
  "可靠": "消息可靠。",
  "猜想": "大胆猜想。",
  "粉碎": "粉碎性骨折。",
  "外套": "羽绒外套。",
  "解释": "解释清楚。",
  "教授": "客座教授。",
  "困境": "陷入困境。",
  "既然": "既然如此。",
  "此时": "此时此刻。",
  "恐惧": "恐惧心理。",
  "凄凉": "晚景凄凉。",
  "安慰": "安慰奖。",
  "寂寞": "寂寞沙洲冷。",
  "宴会": "慈善宴会。",
  "栅栏": "木栅栏。",
  "帐篷": "露营帐篷。",
  "倒霉": "倒霉熊。",
  "忧伤": "忧伤的歌。",
  "处境": "处境尴尬。",
  "理智": "理智与情感。",
  "控制": "控制变量。",
  "吹嘘": "吹嘘自己。",
  "混乱": "混乱不堪。",
  "废话": "废话连篇。",
  "简陋": "简陋的屋子。",
  "野蛮": "野蛮人。",
  "忧郁": "忧郁症。",
  "至于": "至于吗。",
  "淡忘": "逐渐淡忘。",
  "宽慰": "宽慰自己。",
  // "甚至": "甚至更好。", // Duplicate
  "万象更新": "万象更新。",
  "悬灯结彩": "悬灯结彩。",
  "不可思议": "不可思议。",
  "见微知著": "见微知著。",
  "锲而不舍": "锲而不舍。",
  "司空见惯": "司空见惯。",
  "追根求源": "追根求源。",
  "无独有偶": "无独有偶。",
  "饶有趣味": "饶有趣味。",
  "焉知非福": "焉知非福。",
  "截然不同": "截然不同。",
  "哄堂大笑": "哄堂大笑。",
  "能歌善舞": "能歌善舞。",
  "行善积德": "行善积德。",
  "两面三刀": "两面三刀。",
  "随心所欲": "随心所欲。"
};

export const RAW_TEXTS: Record<string, string> = {
  // English
  'GRADE 1-Fall': 'apple,ant,bag,book,cat,crayon,dog,duck,egg,elephant,face,foot,green,gift,hand,hi,ice,ice cream,jet,kite,leg,mouth,nose,orange,pen,pencil,queen,red,ruler,school,teacher,umbrella,vegetable,water,yellow,zoo,hello,goodbye,name,what,my,your',
  'GRADE 1-Spring': 'one,two,three,four,five,six,seven,eight,nine,ten,baby,bear,bird,blue,brother,brown,cut,dad,dance,draw,ear,eye,family,father,fish,friend,grandmother,grandfather,jump,milk,monkey,mother,mum,panda,pear,run,sing,sister,tiger,white,black',
  'GRADE 2-Fall': 'bus,bike,taxi,train,ship,plane,car,jeep,lamp,desk,chair,walkman,zoo,park,cinema,hospital,shop,rice,beef,bread,chicken,egg,window,door,floor,wall,farmer,driver,doctor,nurse,cook,music,science,sports,chinese,english,math,painting,computer,game',
  'GRADE 2-Spring': 'spring,summer,autumn,winter,season,swim,fly,sleep,skate,plant,clock,time,day,night,breakfast,lunch,dinner,class,music,pe,art,cold,hot,cool,warm,sunny,windy,cloudy,rainy,snowy,shirt,skirt,dress,socks,shoes,jacket,sweater,jeans,shorts,big,small,long,short',
  'GRADE 3-Fall': 'pen,pencil,bag,book,eraser,ruler,pencil box,crayon,head,face,nose,mouth,eye,ear,arm,hand,leg,foot,body,red,yellow,green,blue,purple,white,black,orange,brown,cat,dog,monkey,panda,duck,pig,bird,bear,elephant,tiger,zoo,cake,bread,juice,milk,water,egg,fish,rice,one,two,three,four,five,six,seven,eight,nine,ten',
  'GRADE 3-Spring': 'boy,girl,teacher,student,friend,man,woman,father,mother,brother,sister,grandfather,grandmother,giraffe,deer,tall,short,long,fat,thin,big,small,apple,banana,pear,orange,grape,watermelon,strawberry,buy,fruit,car,map,boat,desk,chair,ball,cap,toy,box,plane,in,on,under,eleven,twelve,thirteen,fourteen,fifteen,sixteen,seventeen,eighteen,nineteen,twenty',
  'GRADE 4-Fall': 'classroom,window,blackboard,light,picture,door,floor,computer,teacher\'s desk,wall,fan,strong,friendly,quiet,hair,shoe,glasses,bag,hat,candy,key,toy,notebook,bedroom,living room,study,kitchen,bathroom,bed,phone,table,sofa,fridge,beef,chicken,noodles,soup,vegetable,chopsticks,spoon,knife,fork,bowl,doctor,cook,driver,farmer,nurse,people,but,little,puppy,football,basketball',
  'GRADE 4-Spring': 'playground,library,art room,computer room,music room,first floor,second floor,teachers\' office,breakfast,lunch,dinner,english class,music class,pe class,get up,go to school,go home,go to bed,cold,cool,warm,hot,sunny,windy,cloudy,snowy,rainy,tomato,potato,green bean,carrot,horse,cow,sheep,hen,clothes,pants,hat,dress,skirt,coat,sweater,sock,shorts,jacket,shirt,glove,scarf,umbrella,sunglasses,pretty,expensive,cheap,nice',
  'GRADE 5-Fall': 'old,young,funny,kind,strict,polite,hard-working,helpful,clever,shy,monday,tuesday,wednesday,thursday,friday,saturday,sunday,weekend,wash,watch,do,read,play,sandwich,salad,hamburger,ice cream,tea,fresh,healthy,delicious,hot,sweet,dance,sing,draw,swim,speak,cook,basketball,ping-pong,clock,plant,bottle,photo,front,between,above,beside,behind,forest,river,lake,mountain,hill,tree,bridge,building,village,house',
  'GRADE 5-Spring': 'eat breakfast,do morning exercises,have class,eat lunch,read a book,listen to music,play sports,eat dinner,clean my room,go for a walk,go shopping,take,dancing,spring,summer,autumn,winter,season,picnic,pick,snowman,go swimming,january,february,march,april,may,june,july,august,september,october,november,december,first,second,third,fourth,fifth,twelfth,twentieth,climb,eat,play,jump,drink,sleep',
  'GRADE 6-Fall': 'science,museum,post office,bookstore,cinema,hospital,crossing,turn,left,right,straight,subway,train,bus,taxi,ship,plane,foot,stop,wait,go,dictionary,comic,word,postcard,visit,film,trip,supermarket,evening,tonight,tomorrow,next,teach,singer,writer,actor,artist,policeman,reporter,fisherman,scientist,pilot,coach,angry,afraid,sad,worried,happy,count',
  'GRADE 6-Spring': 'younger,older,taller,shorter,longer,thinner,heavier,bigger,smaller,stronger,dinosaur,hall,meter,kilogram,lower,shadow,smart,become,countryside,cleaned,stayed,washed,watched,had,slept,read,saw,last,yesterday,before,went,camp,fishing,hurt,ate,bought,gift,took,mule,beach,basket,part,licked,laughed,rode,gym,grass',

  // Chinese
  '语文一年级上册': '一二三,四五六,七八九,十百千,上中下,人口手,日月,水火,山石,田土,禾苗,云雨,风雪,花鸟,爸妈,马牛羊,鸡鸭鹅,小大,多少,前后,左右,东南西北,春夏秋冬,男女,开关,正反,来去,出入,坐立,走跑,白云,土地,天空,树木,森林,中国,国旗,五星,美丽,你好,再见,谢谢,不客气,对不起,没关系',
  '语文一年级下册': '春风,冬雪,花开,飞鸟,入水,什么,多么,双人,国王,王子,方圆,生字,左右,红色,绿色,晴天,请问,清水,心情,事情,生动,万一,千万,百花,齐心,说话,电话,朋友,友谊,高山,江湖,语文,数学,音乐,伙伴,大家,这里,那里,太阳,月亮,故乡,高兴,拍手,身体,运动,远近,听说',
  '语文二年级上册': '两个,哪里,宽大,头顶,眼睛,肚皮,孩子,跳高,变化,极点,一片,傍晚,海洋,工作,坏事,办法,如果,更有,毛笔,写信,圆珠笔,电灯,电影,今天,别处,深处,熊猫,朋友,辛苦,农忙,归来,爱戴,英雄,队旗,铜号,欢笑,杨树,壮丽,梧桐,枫叶,松柏,棉花,杉树,化石,季节,蝴蝶,麦苗,桑叶,肥胖,农家',
  '语文二年级下册': '春天,寻找,姑娘,野花,眼睛,柳枝,桃花,杏花,冲出,原来,叔叔,邮局,礼物,先生,原来,太太,做客,惊奇,快活,美好,邓小平,植树,格外,引人注目,满意,休息,树苗,小心,笔直,汗珠,甚至,花草,原野,葱葱,五颜六色,精灵,叮咛,聊天,草坪,葱郁,烟囱,一般,彩色,梦想,森林,拉手,结果,苹果,喜欢',
  '语文三年级上册': '早晨,穿戴,鲜艳,服装,打扮,敬爱,国旗,敬礼,安静,树枝,好奇,招引,洁白,摇晃,影子,落下,荒野,口笛,跳舞,狂欢,罚站,互相,能够,猜出,扬起,双臂,汉族,绒球,坪坝,飘扬,朗读,摔跤,凤尾竹,洁白,罚款,放假,互相,所见,牧童,振动,意欲,捕鸣蝉,忽然,闭口,立在,水泥,亮晶晶,图案,排列,规则,凌乱,棕红,迟到',
  '语文三年级下册': '燕子,乌黑,轻快,翅膀,剪刀,尾巴,活泼,机灵,微风,赶集,聚拢,光彩夺目,增添,生机,掠过,稻田,偶尔,沾水,荡漾,荷花,清香,碧绿,莲蓬,破裂,姿势,仿佛,衣裳,舞蹈,翩翩起舞,蜻蜓,守株待兔,耕田,触株,颈部,释放,其他,骄傲,谦虚,懦弱,尘土,捧起,擦洗,古代,价值,动手,国王,狮子,鹿角,池塘,欣赏,匀称,精美,别致',
  '语文四年级上册': '观潮,据说,大堤,宽阔,笼罩,人山人海,屹立,若隐若现,昂首,顿时,人声鼎沸,浩浩荡荡,山崩地裂,霎时,余波,依旧,牵手,鹅卵石,坑坑洼洼,填平,庄稼,风俗,跃出,葡萄,稻谷,成熟,柔和,河床,新鲜,修补,即使,科学,横贯,虚弱,愉快,呼风唤雨,世纪,技术,改变,程度,超过,幻想,原子核,奥秘,日益,联系,物质,哲学家,任何,改善',
  '语文四年级下册': '屋檐,装饰,顺序,华丽,独特,照例,率领,觅食,捣衣,向导,和谐,辛苦,蚕桑,耘田,归来,慰藉,卜落,威力,锐利,河滩,帐子,闪烁,奇幻,蝙蝠,雷达,避开,敏捷,捕捉,苍蝇,揭开,推进,障碍,荧光屏,恐龙,凶猛,笨重,迟钝,鸽子,末期,描绘,隧道,形态,膨大,前肢,具备,开辟,脱离,无忧无虑,因为,生气勃勃,天高地阔,月明人静,一丝不苟,空空如也,枝折花落,从容不迫,扬长而去,没完没了',
  '语文五年级上册': '白鹭,精巧,色素,适宜,播种,浇水,吩咐,爱慕,体面,懒惰,尤其,协调,酬谢,珍宝,叮嘱,崩塌,稀罕,所谓,猎人,黎明,漆黑,完好无缺,怒发冲冠,难以置信,举世闻名,众星拱月,玲珑剔透,诗情画意,太平盛世,美中不足,金碧辉煌,绝口不提,无价之宝,理直气壮,完璧归赵,攻无不克,战无不胜,负荆请罪,同心协力,自有妙用,神机妙算,踉踉跄跄,喜不自胜,天造地设,伸头缩颈,抓耳挠腮,力倦神疲,人而无信,饮水思源,相依为命',
  '语文五年级下册': '昼夜,耕耘,稚子,蚂蚱,樱桃,瞎闹,锄头,承认,随意,阴凉,蜻蜓,割草,倭瓜,威吓,露馅,屏障,芝麻,神圣,侵犯,摔跤,乐此不疲,情不自禁,肃然起敬,摩拳擦掌,跃跃欲试,兴致勃勃,养尊处优,手忙脚乱,恍然大悟,哭笑不得,若有所思,半信半疑,神机妙算,自有妙用,踉踉跄跄,瞑目蹲身,喜不自胜,天造地设,伸头缩颈,抓耳挠腮,力倦神疲,纵身,颤抖,慈祥,荣幸,眷恋,锻炼,繁忙,特殊,尊重',
  '语文六年级上册': '绿毯,线条,柔美,惊叹,回味,乐趣,目的地,洒脱,衣裳,惹人,微笑,愁怨,顺心,也就是,稍微,比如,笨拙,参差,单薄,照耀,文豪,模糊,幽雅,或者是,飞驰,礼貌,拘束,羞涩,摔跤,宅院,幽静,纯熟,陌生,清秀,陶醉,苏醒,呻吟,探望,照顾,敲门,拜访,刺猬,翠色欲流,意味深长,硕大无朋,顾影自怜,孤芳自赏,汹涌澎湃,斩钉截铁,居高临下,排山倒海,别出心裁,技高一筹,弄巧成拙,作茧自缚,饱经风霜,囫囵吞枣,张冠李戴,大步流星,怒气冲冲,暴露无遗,难以忘怀',
  '语文六年级下册': '腊八,粥,蒜,醋,饺子,摊贩,彼此,贺年,骆驼,恰好,一律,彩绘,分外,糊涂,搅和,浓稠,可靠,猜想,粉碎,外套,解释,教授,困境,既然,此时,恐惧,凄凉,安慰,寂寞,宴会,栅栏,帐篷,倒霉,忧伤,处境,理智,控制,吹嘘,混乱,废话,简陋,野蛮,忧郁,至于,淡忘,甚至,宽慰,万象更新,悬灯结彩,不可思议,见微知著,锲而不舍,司空见惯,追根求源,无独有偶,饶有趣味,焉知非福,截然不同,哄堂大笑,能歌善舞,行善积德,两面三刀,随心所欲'
};

function parseTextToItems(text: string, lang: 'EN' | 'CN'): ExerciseItem[] {
  if (!text) return [];
  const keys = text.split(',').map(s => s.trim()).filter(s => s);
  
  return keys.map(key => {
    if (lang === 'EN') {
      const lowerKey = key.toLowerCase();
      const data = EN_METADATA[lowerKey];
      return {
        text: key,
        phonetic: data ? data[0] : "",
        translation: data ? data[1] : key,
        example: data ? data[2] : `Practice spelling: ${key}`
      };
    } else {
      const py = getPinyin(key);
      const example = CN_METADATA[key] || `请练习打字：${key}`;
      return {
        text: py,
        chinese: key,
        example: example
      };
    }
  });
}

export const TEXTBOOK_RESOURCES: Record<string, Record<string, ExerciseItem[]>> = {
  '英语': {},
  '语文': {}
};

Object.keys(RAW_TEXTS).forEach(bookName => {
  const isEn = bookName.startsWith('GRADE');
  const lang = isEn ? '英语' : '语文';
  TEXTBOOK_RESOURCES[lang][bookName] = parseTextToItems(RAW_TEXTS[bookName], isEn ? 'EN' : 'CN');
});

export const RESOURCE_SUMS: Record<string, number> = {};
Object.keys(RAW_TEXTS).forEach(key => {
  RESOURCE_SUMS[key] = RAW_TEXTS[key].split(',').length;
});
