// 英语例句中文翻译（由 GLM-4-Flash 批量生成，905 条）
// key = 英文例句原文，value = 中文翻译
export const EN_EXAMPLE_ZH: Record<string, string> = {
  "I go to school.": "我去上学。",
  "Open your book.": "打开你的书。",
  "This is my ruler.": "这是我的尺。",
  "I have a pencil.": "我有一支铅笔。",
  "Where is my eraser?": "我的橡皮在哪里？",
  "My pencil box is new.": "我的铅笔盒是新的。",
  "My bag is heavy.": "我的包很重。",
  "Hello, teacher!": "你好，老师！",
  "Hello, my friend.": "你好，我的朋友。",
  "Hi, I'm Amy.": "嗨，我是艾米。",
  "Goodbye, see you.": "再见，再见。",
  "Bye-bye, Tom!": "再见，汤姆！",
  "My name is Sam.": "我叫山姆。",
  "This is my bag.": "这是我的包。",
  "What's your name?": "你叫什么名字？",
  "Touch your face.": "摸摸你的脸。",
  "Listen with your ears.": "用耳朵听。",
  "Close your eyes.": "闭上眼睛。",
  "Touch your nose.": "摸摸你的鼻子。",
  "Open your mouth.": "张开嘴巴。",
  "Look at me!": "看着我！",
  "The dog runs fast.": "狗跑得快。",
  "It is a fat cat.": "它是一只胖猫。",
  "Birds can fly.": "鸟儿会飞。",
  "The tiger is strong.": "老虎很强大。",
  "The monkey likes bananas.": "猴子喜欢香蕉。",
  "Look at the elephant.": "看那只大象。",
  "The panda is cute.": "熊猫很可爱。",
  "Let's go to the zoo.": "我们去动物园吧。",
  "One finger.": "一个手指。",
  "Two eyes.": "两只眼睛。",
  "Three birds.": "三只鸟。",
  "Four legs.": "四条腿。",
  "High five!": "击个掌！",
  "Six ducks.": "六只鸭子。",
  "Seven colours.": "七种颜色。",
  "Eight monkeys.": "八只猴子。",
  "Nine stars.": "九颗星星。",
  "Count to ten.": "数到十。",
  "A red apple.": "一个红苹果。",
  "A yellow duck.": "一只黄鸭子。",
  "The sky is blue.": "天空是蓝色的。",
  "The grass is green.": "草地是绿色的。",
  "A black cat.": "一只黑猫。",
  "White clouds.": "白云。",
  "A brown bear.": "一只棕熊。",
  "An orange is round.": "橙子是圆的。",
  "A pink dress.": "一条粉红色的裙子。",
  "Purple grapes.": "紫葡萄。",
  "A is for apple.": "A代表苹果。",
  "A sweet pear.": "一个甜梨。",
  "A yellow banana.": "一根黄香蕉。",
  "The peach is sweet.": "桃子很甜。",
  "I like grapes.": "我喜欢葡萄。",
  "A big watermelon.": "一个大西瓜。",
  "A sweet strawberry.": "一个甜草莓。",
  "I eat fruit every day.": "我每天都吃水果。",
  "The apple is sweet.": "苹果很甜。",
  "Ants are small.": "蚂蚁很小。",
  "The duck says quack.": "鸭子说嘎嘎。",
  "I like eggs.": "我喜欢鸡蛋。",
  "Look at the jet.": "看那架飞机。",
  "Fly a kite.": "放风筝。",
  "Shake your legs.": "摇摇你的腿。",
  "Clap your hands.": "拍拍手。",
  "Stomp your foot.": "跺跺脚。",
  "Touch your head.": "摸摸头。",
  "Wave your arms.": "挥挥手。",
  "Move your body.": "动动身体。",
  "Her hair is long.": "她的头发很长。",
  "Good morning!": "早上好！",
  "Good morning, Mum.": "早上好，妈妈。",
  "Good afternoon, class.": "下午好，同学们。",
  "Good night, Dad.": "晚安，爸爸。",
  "Have a nice day!": "祝你有个美好的一天！",
  "The sun is big.": "太阳很大。",
  "The moon is bright.": "月亮很亮。",
  "I see a star.": "我看到一颗星星。",
  "Rain falls down.": "雨往下落。",
  "Snow is white.": "雪是白色的。",
  "The wind blows.": "风吹了。",
  "A white cloud.": "一朵白云。",
  "This is my classroom.": "这是我的教室。",
  "My desk is clean.": "我的桌子很干净。",
  "Sit on the chair.": "坐在椅子上。",
  "Look at the blackboard.": "看黑板。",
  "Close the door.": "关门。",
  "Open the window.": "开窗户。",
  "The cat is in the box.": "猫在盒子里。",
  "The book is on the desk.": "书在桌子上。",
  "The ball is under the bed.": "球在床下。",
  "Where is my cat?": "我的猫在哪里？",
  "My room is small.": "我的房间很小。",
  "The tea is on the table.": "茶在桌子上。",
  "Go to bed now.": "现在去睡觉。",
  "Turn on the lamp.": "打开灯。",
  "The sofa is soft.": "沙发很软。",
  "This is my toy.": "这是我的玩具。",
  "The plane flies high.": "飞机飞得很高。",
  "Bounce the ball.": "拍球。",
  "The doll is pretty.": "娃娃很漂亮。",
  "My toy car is red.": "我的玩具车是红色的。",
  "I take the bus.": "我坐公交车。",
  "Ride a bike.": "骑自行车。",
  "I love my teddy bear.": "我爱我的泰迪熊。",
  "I eat rice.": "我吃米饭。",
  "Noodles are long.": "面条很长。",
  "The chicken is yummy.": "鸡肉好好吃。",
  "Fish swim.": "鱼游来游去。",
  "Eat your vegetables.": "吃你的蔬菜。",
  "I am hungry.": "我饿了。",
  "I am thirsty.": "我渴了。",
  "Orange juice is sweet.": "橙汁甜甜的。",
  "Drink milk daily.": "每天喝牛奶。",
  "Drink some water.": "喝点水。",
  "Hot tea for Dad.": "给爸爸泡杯热茶。",
  "A birthday cake.": "一个生日蛋糕。",
  "Fresh bread.": "新鲜面包。",
  "A big hamburger.": "一个大汉堡。",
  "I like hot dogs.": "我喜欢热狗。",
  "Coffee is for Dad.": "咖啡是爸爸的。",
  "Sweet candy.": "甜甜的糖果。",
  "The kangaroo jumps.": "袋鼠跳。",
  "The lion is brave.": "狮子很勇敢。",
  "A tall giraffe.": "高高的长颈鹿。",
  "A fast deer.": "跑得快的鹿。",
  "The snake is long.": "蛇很长。",
  "A fat pig.": "胖胖的猪。",
  "A thin monkey.": "瘦瘦的猴子。",
  "A big elephant.": "大大的象。",
  "A small ant.": "小小的蚂蚁。",
  "A tall tree.": "高高的树。",
  "A short pencil.": "短短铅笔。",
  "A long ruler.": "长长的尺。",
  "A happy family.": "快乐的一家。",
  "I love my dad.": "我爱爸爸。",
  "I love my mum.": "我爱妈妈。",
  "He is my brother.": "他是我的哥哥。",
  "My little sister.": "我的小妹妹。",
  "Grandma is kind.": "奶奶很善良。",
  "Grandpa smiles.": "爷爷笑。",
  "We are friends.": "我们是朋友。",
  "A clever boy.": "聪明的男孩。",
  "A pretty girl.": "漂亮的女孩。",
  "Yes, I can.": "是的，我可以。",
  "No, thank you.": "不，谢谢。",
  "Please sit down.": "请坐下。",
  "Sorry, Mum.": "对不起，妈妈。",
  "OK, let's go.": "好的，我们走吧。",
  "Let's dance.": "让我们跳舞。",
  "Sing a song.": "唱首歌。",
  "Draw a picture.": "画幅画。",
  "Jump high!": "跳得高！",
  "Run fast.": "跑得快。",
  "Walk to school.": "走去学校。",
  "Birds fly.": "鸟儿飞。",
  "Good sleep.": "睡个好觉。",
  "I get up early.": "我早起。",
  "Let's go home.": "我们回家。",
  "Wait at the bus stop.": "在公交车站等。",
  "My grandfather is wise.": "我爷爷很聪明。",
  "My grandmother cooks.": "我奶奶会做饭。",
  "This is my father.": "这是我的爸爸。",
  "My mother loves me.": "妈妈爱我。",
  "A tall man.": "一个高个子男人。",
  "A kind woman.": "一个善良的女人。",
  "Play in the park.": "在公园里玩。",
  "A red flower.": "一朵红花。",
  "The lake is blue.": "湖水是蓝色的。",
  "Climb the hill.": "爬上小山。",
  "The street is busy.": "街道很热闹。",
  "A toy shop.": "玩具店。",
  "Go to the cinema.": "去看电影。",
  "Shop at the supermarket.": "在超市购物。",
  "The hospital is big.": "医院很大。",
  "A fast train.": "一列快车。",
  "A big ship.": "一艘大船。",
  "Take a taxi.": "坐出租车。",
  "A green jeep.": "一辆绿色的吉普车。",
  "Row a boat.": "划船。",
  "Look at the map.": "看看地图。",
  "Play basketball.": "打篮球。",
  "Kick the football.": "踢足球。",
  "Play ping-pong.": "打乒乓球。",
  "Tennis is fun.": "网球很有趣。",
  "I love sports.": "我喜欢运动。",
  "I like music.": "我喜欢音乐。",
  "Art class is fun.": "美术课很有趣。",
  "Math is easy.": "数学很简单。",
  "I study Chinese.": "我学中文。",
  "I speak English.": "我说英语。",
  "Science is cool.": "科学很酷。",
  "A new computer.": "一台新电脑。",
  "A beautiful painting.": "一幅美丽的画。",
  "Play a game.": "玩游戏。",
  "A busy farmer.": "一个忙碌的农夫。",
  "A bus driver.": "一位公交车司机。",
  "See a doctor.": "去看医生。",
  "A gentle nurse.": "一位温柔的护士。",
  "A great cook.": "一位了不起的厨师。",
  "A hard worker.": "勤劳的人。",
  "I am a pupil.": "我是学生。",
  "I study hard.": "我学习很努力。",
  "Dad goes to work.": "爸爸去上班了。",
  "We play together.": "我们一起玩。",
  "Read a book.": "读一本书。",
  "Write your name.": "写你的名字。",
  "I help Mum.": "我帮妈妈。",
  "I love my family.": "我爱我的家人。",
  "I am happy.": "我很开心。",
  "Don't be sad.": "不要难过。",
  "A new bag.": "一个新的书包。",
  "An old book.": "一本旧书。",
  "It is cold today.": "今天很冷。",
  "The tea is hot.": "茶很热。",
  "Cool wind blows.": "凉风吹。",
  "Warm spring days.": "温暖的春天。",
  "Eat breakfast.": "吃早餐。",
  "Yummy lunch.": "美味的午餐。",
  "Family dinner.": "家庭晚餐。",
  "What time is it?": "现在几点了？",
  "The clock ticks.": "钟在滴答响。",
  "Watch a cartoon.": "看动画片。",
  "Warm spring.": "温暖的春天。",
  "Hot summer.": "炎热的夏天。",
  "Golden autumn.": "金色的秋天。",
  "Cold winter.": "寒冷的冬天。",
  "Four seasons.": "四季。",
  "A sunny day.": "晴朗的一天。",
  "A windy day.": "风大的日子。",
  "A cloudy sky.": "多云的天空。",
  "A rainy day.": "下雨天。",
  "A snowy winter.": "雪天的冬天。",
  "A white shirt.": "一件白衬衫。",
  "A pink skirt.": "一条粉色的裙子。",
  "A pretty dress.": "一条漂亮的裙子。",
  "Warm socks.": "一双暖和的袜子。",
  "Running shoes.": "一双运动鞋。",
  "A blue jacket.": "一件蓝色的夹克。",
  "A cozy sweater.": "一件舒适的毛衣。",
  "Blue jeans.": "蓝色牛仔裤。",
  "Summer shorts.": "夏天的短裤。",
  "A warm coat.": "一件暖和的大衣。",
  "Skate on ice.": "在冰上滑冰。",
  "Plant flowers.": "种花。",
  "My hobby is reading.": "我的爱好是看书。",
  "Our team wins.": "我们队赢了。",
  "We win the game.": "我们赢了比赛。",
  "I can swim.": "我会游泳。",
  "Make a wish.": "许个愿。",
  "A birthday party.": "生日派对。",
  "A gift for you.": "给你一个礼物。",
  "Make a card.": "做一个卡片。",
  "A red balloon.": "一个红色的气球。",
  "Light the candle.": "点燃蜡烛。",
  "Write a letter.": "写一封信。",
  "A family photo.": "一张家庭照片。",
  "A spring picnic.": "春天野餐。",
  "Play outside.": "到外面玩。",
  "How's the weather?": "天气怎么样？",
  "The grass is wet.": "草地是湿的。",
  "The towel is dry.": "毛巾是干的。",
  "A slow snail.": "一只慢吞吞的蜗牛。",
  "A fast car.": "一辆快车。",
  "Turn left.": "向左转。",
  "Turn right.": "向右转。",
  "Stop at the red light.": "红灯停。",
  "Wait for me.": "等我。",
  "Turn around.": "转身。",
  "Save your money.": "存点钱。",
  "Buy some fruit.": "买些水果。",
  "They sell apples.": "他们卖苹果。",
  "Cheap candy.": "便宜的糖果。",
  "An expensive watch.": "一块昂贵的手表。",
  "A pretty flower.": "一朵漂亮的花。",
  "A beautiful day.": "一个好天气。",
  "Nice to meet you.": "很高兴见到你。",
  "A clean room.": "一个干净的房间。",
  "Dirty hands.": "脏手。",
  "Open the box.": "打开盒子。",
  "Close your book.": "把书合上。",
  "Turn on the light.": "开灯。",
  "The room is dark.": "房间黑黑的。",
  "Clean the floor.": "把地板擦干净。",
  "A picture on the wall.": "墙上的画。",
  "Welcome home.": "欢迎回家。",
  "Answer the phone.": "接电话。",
  "Milk in the fridge.": "冰箱里有牛奶。",
  "Hot soup.": "热汤。",
  "A soup spoon.": "汤勺。",
  "A sharp knife.": "一把锋利的刀。",
  "A silver fork.": "一把银色的叉子。",
  "A rice bowl.": "一个饭碗。",
  "Use chopsticks.": "用筷子。",
  "A tea cup.": "一个茶杯。",
  "A glass of water.": "一杯水。",
  "A big plate.": "一个大盘子。",
  "Yummy beef.": "好吃的牛肉。",
  "A water bottle.": "一瓶水。",
  "A toy box.": "一个玩具箱。",
  "Put on your cap.": "戴上你的帽子。",
  "A sun hat.": "一顶太阳帽。",
  "The queen smiles.": "皇后笑了。",
  "A kind king.": "一位善良的国王。",
  "A smart robot.": "一个聪明的机器人。",
  "A cute puppy.": "一只可爱的小狗。",
  "A little kitten.": "一只小猫。",
  "A pink pig.": "一只粉红色的小猪。",
  "White sheep.": "一只白羊。",
  "A milk cow.": "一头奶牛。",
  "A fast horse.": "一匹快马。",
  "A hen lays eggs.": "母鸡下蛋。",
  "A white rabbit.": "一只白兔。",
  "A small mouse.": "一只小老鼠。",
  "Eleven birds.": "十一个鸟。",
  "Twelve months.": "十二个月。",
  "Thirteen apples.": "十三个苹果。",
  "Fourteen kites.": "十四个风筝。",
  "Fifteen stars.": "十五颗星星。",
  "Sixteen flowers.": "十六朵花。",
  "Seventeen ducks.": "十七只鸭子。",
  "Eighteen cars.": "十八辆车。",
  "Nineteen balls.": "十九个球。",
  "Twenty pupils.": "二十个学生。",
  "A good student.": "一个好学生。",
  "My classmate is kind.": "我的同学很友好。",
  "I'm Sam.": "我是山姆。",
  "I have a red crayon.": "我有一支红蜡笔。",
  "Good morning, Miss Li.": "早上好，李老师。",
  "This is my friend.": "这是我的朋友。",
  "Good morning, Miss White.": "早上好，怀特老师。",
  "How are you?": "你好吗？",
  "I'm fine, thank you.": "我很好，谢谢。",
  "Thanks a lot.": "非常感谢。",
  "Let's go to school.": "我们去学校吧。",
  "Let's go!": "走吧！",
  "Go to school.": "去上学。",
  "Now it's my turn.": "现在轮到我了。",
  "Wow, so beautiful!": "哇，真漂亮！",
  "Nice to see you.": "很高兴见到你。",
  "Say hello to Dad.": "跟爸爸问好。",
  "Uh, let me see.": "嗯，让我看看。",
  "Great job!": "做得好！",
  "Bye-bye, everyone!": "再见，大家！",
  "Mr Jones, hello!": "琼斯先生，你好！",
  "I see a blue crayon.": "我看到一支蓝蜡笔。",
  "Good afternoon, Mr Jones.": "下午好，琼斯先生。",
  "Nice to meet you!": "很高兴认识你！",
  "Stand up, please.": "请站起来。",
  "Sit down, please.": "请坐下。",
  "A funny clown.": "一个有趣的丑角。",
  "I play with my friends.": "我和朋友们玩。",
  "It's a real dog!": "这是一只真的狗！",
  "Have some bread.": "吃点面包。",
  "I'd like some juice.": "我想喝点果汁。",
  "Here you are!": "给你！",
  "Thank you very much.": "非常感谢。",
  "You're welcome!": "不客气！",
  "Can I have some water?": "我能喝点水吗？",
  "How old are you?": "你多大了？",
  "Make a wish, Sam!": "萨姆，许个愿吧！",
  "Let's cut the cake.": "咱们切蛋糕吧。",
  "Share your candy.": "把你的糖果分一下。",
  "Eat some fruit.": "吃点水果。",
  "Drink some juice.": "喝点果汁。",
  "It tastes sweet.": "这个很甜。",
  "Smell the flowers.": "闻闻花香。",
  "I love animals.": "我喜欢动物。",
  "Follow me, please!": "请跟上来！",
  "Welcome to our school.": "欢迎来到我们的学校。",
  "Welcome back to school.": "欢迎回到学校。",
  "She is my teacher.": "她是我的老师。",
  "He is a student.": "他是学生。",
  "Today is Monday.": "今天是星期一。",
  "I'm from China.": "我来自中国。",
  "She is from the UK.": "她来自英国。",
  "He is from the USA.": "他来自美国。",
  "Amy is from Canada.": "艾米来自加拿大。",
  "We have a new friend.": "我们有个新朋友。",
  "Wait a minute!": "等一下！",
  "How beautiful!": "真漂亮！",
  "This isn't my bag.": "这不是我的包。",
  "Meet my family members.": "见见我的家人。",
  "A lovely girl.": "一个可爱的女孩。",
  "It's so tall!": "这么高！",
  "Children, look here.": "孩子们，看这里。",
  "A happy child.": "一个快乐的孩子。",
  "The monkey has a long tail.": "猴子有一条长尾巴。",
  "Come here, children!": "孩子们，过来！",
  "Look at that panda.": "看那只熊猫。",
  "It has a long nose.": "它有一个长鼻子。",
  "Hide and seek.": "捉迷藏。",
  "I can't find my pen.": "我找不到我的笔了。",
  "Excuse me, where is the zoo?": "打扰一下，动物园在哪里？",
  "Don't be silly.": "别傻了。",
  "Honey, come here.": "宝贝，过来。",
  "How many kites?": "有多少风筝？",
  "So many apples!": "这么多苹果！",
  "That's a good idea!": "这是个好主意！",
  "Open it and see!": "打开看看！",
  "Where do you live?": "你住在哪里？",
  "I live in Beijing.": "我住在北京。",
  "Toys for sale.": "玩具出售。",
  "Oh no! My kite!": "哎呀！我的风筝！",
  "It's really big.": "真的很大。",
  "My home is near the park.": "我家靠近公园。",
  "Watch TV.": "看电视。",
  "Let's clean the classroom.": "我们来打扫一下教室。",
  "Let me help you.": "让我帮你。",
  "My schoolbag is heavy.": "我的书包很重。",
  "Write in your notebook.": "在你的笔记本上写。",
  "Read a storybook.": "读一本故事书。",
  "Where is my key?": "我的钥匙在哪里？",
  "Wow, so much candy!": "哇，这么多糖果！",
  "My cat is lost.": "我的猫丢了。",
  "Where is my Chinese book?": "我的中文书在哪里？",
  "My English book is new.": "我的英语书是新的。",
  "I have a new maths book.": "我有一本新的数学书。",
  "Be quiet in the library.": "在图书馆里安静点。",
  "A friendly girl.": "一个友好的女孩。",
  "He wears glasses.": "他戴眼镜。",
  "His bag is blue.": "他的包是蓝色的。",
  "Is he tall or short?": "他高还是矮？",
  "His shoes are new.": "他的鞋子是新的。",
  "My dad is strong.": "我爸爸很强壮。",
  "This is my bedroom.": "这是我的卧室。",
  "Watch TV in the living room.": "在客厅看电视。",
  "Mum cooks in the kitchen.": "妈妈在厨房做饭。",
  "Take a shower in the bathroom.": "在浴室洗澡。",
  "Have a nap, dear.": "宝贝，午睡一下吧。",
  "Read a book in the study.": "在书房里读书。",
  "Take a shower.": "洗澡。",
  "I watch TV at night.": "我晚上看电视。",
  "Are they on the bed?": "他们在床上吗？",
  "I'm hungry, Mum.": "妈妈，我饿了。",
  "What's for dinner?": "晚饭吃什么？",
  "What would you like for dinner?": "你晚饭想吃什么？",
  "Help yourself to some fish.": "自己拿点鱼吃。",
  "Pass me the bowl, please.": "请把碗递给我。",
  "Cut the vegetables.": "切一下蔬菜。",
  "Use the spoon to eat soup.": "用勺子喝汤。",
  "Use the fork to eat beef.": "用叉子吃牛肉。",
  "Dinner is ready!": "晚饭好了！",
  "Dinner's ready! Come on!": "晚饭好了！快点儿！",
  "My parents love me.": "爸爸妈妈爱我。",
  "My uncle is a driver.": "我叔叔是司机。",
  "My aunt is a nurse.": "我阿姨是护士。",
  "My baby brother is cute.": "我弟弟好可爱。",
  "He is a football player.": "他是个足球运动员。",
  "What's your father's job?": "你爸爸是做什么的？",
  "How many people are in your family?": "你家有多少人？",
  "He is short but strong.": "他个子矮但很强壮。",
  "A little puppy.": "一只小狗。",
  "Welcome to my home!": "欢迎来我家！",
  "These are my parents.": "这是我的爸爸妈妈。",
  "My family has six people.": "我家有六个人。",
  "That's only five.": "那只有五个。",
  "Add three and four.": "三加四。",
  "Run on the playground.": "在操场上跑步。",
  "Read books in the library.": "在图书馆看书。",
  "Draw in the art room.": "在美术教室画画。",
  "We play in the computer room.": "我们在电脑房玩。",
  "Sing in the music room.": "在音乐教室唱歌。",
  "It's on the first floor.": "在一楼。",
  "The library is on the second floor.": "图书馆在二楼。",
  "Go to the teachers' office.": "去老师办公室。",
  "Welcome to our school!": "欢迎来到我们学校！",
  "This way, please.": "请这边走。",
  "Do you have a library?": "你们有图书馆吗？",
  "Yes, we do.": "是的，我们有。",
  "No, it isn't.": "不是的。",
  "What time is it now?": "现在几点了？",
  "It's 7 o'clock.": "七点了。",
  "It's time for English class.": "英语课时间到了。",
  "Time for music class.": "音乐课时间到了。",
  "I love PE class.": "我喜欢体育课。",
  "It's time for lunch.": "午饭时间到了。",
  "It's time to get up.": "该起床了。",
  "It's time to go to school.": "该去学校了。",
  "It's time to go home.": "该回家了。",
  "It's time to go to bed.": "睡觉时间到了。",
  "Just a minute, Mum.": "妈妈，等一下。",
  "The gym is over there.": "健身房在那边。",
  "School starts at 8 o'clock.": "学校8点开始上课。",
  "I get up at 6:30 am.": "我早上6:30起床。",
  "We go home at 4:30 pm.": "我们下午4:30回家。",
  "It's cold outside.": "外面很冷。",
  "Be careful! The soup is hot.": "小心！汤很烫。",
  "Watch the weather report.": "看看天气预报。",
  "What's the weather like today?": "今天天气怎么样？",
  "It's rainy today.": "今天下雨了。",
  "Not much.": "不多。",
  "How about Beijing?": "北京怎么样？",
  "It's 26 degrees.": "26度。",
  "The weather around the world.": "世界各地的天气。",
  "Red tomatoes.": "红番茄。",
  "Big potatoes.": "大土豆。",
  "Crispy green beans.": "脆绿豆。",
  "Rabbits love carrots.": "兔子喜欢胡萝卜。",
  "Animals on the farm.": "农场里的动物。",
  "These are tomatoes.": "这些是番茄。",
  "Those are carrots.": "那些是胡萝卜。",
  "Flowers in the garden.": "花园里的花。",
  "Eat up your vegetables.": "把蔬菜吃完。",
  "My clothes are new.": "我的衣服是新的。",
  "My pants are blue.": "我的裤子是蓝色的。",
  "Whose cap is this?": "这是谁的帽子？",
  "A red sock.": "一只红袜子。",
  "Whose coat is this?": "这件外套是谁的？",
  "It's mine, thank you.": "是我的，谢谢。",
  "They're my father's.": "它们是我爸爸的。",
  "Put away your clothes.": "把衣服收起来。",
  "Put on your sweater.": "穿上你的毛衣。",
  "Take off your shoes.": "脱掉你的鞋子。",
  "Hang up your dress.": "挂起你的裙子。",
  "Wash your hands.": "洗手。",
  "Take an umbrella.": "拿把伞。",
  "Cool sunglasses.": "酷酷的太阳镜。",
  "A red scarf.": "一条红围巾。",
  "Warm gloves.": "暖和的手套。",
  "How much is it?": "这个多少钱？",
  "It's pretty. I'll take it.": "挺好看的，我要了。",
  "Size 6, please.": "请给我6号。",
  "Of course you can.": "当然可以了。",
  "It's too big.": "太大了。",
  "One more, please.": "再来一个。",
  "The assistant is kind.": "服务员很和气。",
  "A young teacher.": "一个年轻的老师。",
  "A kind grandma.": "一个和蔼的奶奶。",
  "A strict teacher.": "一个严格的老师。",
  "Be polite to others.": "要对别人有礼貌。",
  "A hard-working pupil.": "一个勤奋的学生。",
  "A helpful boy.": "一个乐于助人的男孩。",
  "A clever girl.": "一个聪明的女孩。",
  "A shy rabbit.": "一只害羞的兔子。",
  "Ms Green is our teacher.": "格林老师是我们的老师。",
  "I will help you.": "我会帮你的。",
  "Sometimes I read at night.": "有时候我晚上会读书。",
  "This is our school.": "这是我们学校。",
  "Our head teacher is kind.": "我们校长很和善。",
  "He works very hard.": "他工作非常努力。",
  "Is he strict?": "他是不是很严格？",
  "He's very kind.": "他非常和善。",
  "We have PE on Monday.": "我们星期一上体育课。",
  "Music class is on Tuesday.": "音乐课在星期二。",
  "Wednesday is art day.": "星期三是美术日。",
  "Thursday is science day.": "星期四是科学日。",
  "Happy Friday!": "周五快乐！",
  "Play on Saturday.": "星期六去玩。",
  "Sunday is family day.": "星期天是家庭日。",
  "Enjoy the weekend.": "享受周末吧。",
  "I wash my clothes.": "我洗衣服。",
  "I do homework every day.": "我每天都做作业。",
  "I read books at night.": "我晚上读书。",
  "Let's play football.": "我们一起踢足球。",
  "I often play sports.": "我经常运动。",
  "Do you often read here?": "你经常在这里读书吗？",
  "I am tired today.": "我今天累了。",
  "Play a sport.": "玩个运动。",
  "You should sleep early.": "你应该早点睡觉。",
  "Read every day.": "每天都要读书。",
  "Look at my schedule.": "看看我的时间表。",
  "A ham sandwich.": "火腿三明治。",
  "Fruit salad is sweet.": "水果沙拉很甜。",
  "Vanilla ice cream.": "香草冰淇淋。",
  "Fresh vegetables.": "新鲜蔬菜。",
  "Healthy food is good.": "健康食品很好。",
  "What delicious food!": "什么好吃的！",
  "My favourite food is fish.": "我最喜欢的食物是鱼。",
  "What's your favourite food?": "你最喜欢的食物是什么？",
  "They're sweet.": "它们很甜。",
  "Beef noodles smell good.": "牛肉面闻起来很好吃。",
  "A fish sandwich, please.": "请给我一个鱼三明治。",
  "Tomato soup is healthy.": "番茄汤很健康。",
  "Mashed potatoes.": "土豆泥。",
  "Green cabbage.": "卷心菜。",
  "Hot green tea.": "热绿茶。",
  "I can sing English songs.": "我会唱英文歌。",
  "I can do kung fu.": "我会练功夫。",
  "She can play the pipa.": "她能弹琵琶。",
  "I can draw cartoons.": "我会画卡通。",
  "We play basketball together.": "我们一起打篮球。",
  "I play ping-pong well.": "我乒乓球打得很好。",
  "Can you speak English?": "你会说英语吗？",
  "What can you do at home?": "你在家能做什么？",
  "Chinese kung fu is cool.": "中国功夫很酷。",
  "In front of the house.": "在房子前面。",
  "Between two trees.": "在两棵树之间。",
  "The light is above me.": "灯光在我上方。",
  "Beside the door.": "在门旁边。",
  "Behind the sofa.": "在沙发后面。",
  "There is a big bed.": "有一张大床。",
  "There are two photos.": "有两张照片。",
  "In my room there is a bed.": "在我的房间里有一张床。",
  "My room is nice.": "我的房间很漂亮。",
  "My water bottle is blue.": "我的水壶是蓝色的。",
  "So many plants here!": "这里这么多植物！",
  "We move into a new house.": "我们搬进新房子。",
  "A green forest.": "一片绿森林。",
  "A clean river.": "一条干净的河。",
  "A high mountain.": "一座高山。",
  "An old bridge.": "一座老桥。",
  "A tall building.": "一座高楼。",
  "A small village.": "一个小村庄。",
  "My house is small.": "我的房子很小。",
  "Let's go boating.": "我们去划船吧。",
  "There aren't any lakes.": "这里没有湖。",
  "Let's go to the nature park.": "我们去公园吧。",
  "There is a house on the mountain.": "山上有一座房子。",
  "There is a dog under the tree.": "树下有一只狗。",
  "There are no people.": "这里没有人。",
  "The mountain is high.": "这座山很高。",
  "I do morning exercises at 7.": "我早上7点做运动。",
  "I eat breakfast at home.": "我在家吃早餐。",
  "We have class at 8.": "我们8点上课。",
  "I play sports at 4.": "我下午4点运动。",
  "We eat dinner at 6.": "我们6点吃晚饭。",
  "When do you get up?": "你什么时候起床？",
  "Exercise every day.": "每天锻炼。",
  "I usually go to school at 7.": "我通常7点去学校。",
  "I eat lunch at noon.": "我中午吃午饭。",
  "It's 6 o'clock.": "现在是6点。",
  "Why do you like spring?": "你为什么喜欢春天？",
  "Class starts at 8.": "8点上课。",
  "That sounds fun.": "那听起来很有趣。",
  "I take a dancing class.": "我上舞蹈课。",
  "Dancing makes me happy.": "跳舞让我开心。",
  "Last weekend was fun.": "上个周末很有趣。",
  "I also like music.": "我也喜欢音乐。",
  "I am busy today.": "我今天很忙。",
  "I need your help.": "我需要你的帮助。",
  "I play music with friends.": "我和朋友们一起玩音乐。",
  "I go for a walk after dinner.": "晚饭后我去散步。",
  "Let's go shopping.": "我们去购物吧。",
  "I clean my room on Saturday.": "我周六打扫房间。",
  "I take an art class.": "我上美术课。",
  "We pick apples in autumn.": "秋天我们摘苹果。",
  "I go swimming in summer.": "夏天我去游泳。",
  "Which season do you like?": "你喜欢哪个季节？",
  "I like spring best.": "我最喜欢春天。",
  "Because it's warm.": "因为天气暖和。",
  "Summer vacation is fun.": "暑假很有趣。",
  "A green leaf.": "一片绿色的叶子。",
  "Colourful leaves in autumn.": "秋天五彩斑斓的叶子。",
  "Colourful flowers.": "五彩缤纷的花朵。",
  "I paint a picture in autumn.": "我在秋天画了一幅画。",
  "Merry Christmas!": "圣诞快乐！",
  "Summer is here!": "夏天来了！",
  "January is the first month.": "一月是一月。",
  "February is short.": "二月很短。",
  "March brings spring.": "三月带来春天。",
  "April showers bring flowers.": "四月雨带来花朵。",
  "May is a warm month.": "五月是个温暖的月份。",
  "June 1st is Children's Day.": "六月一日是儿童节。",
  "July is hot.": "七月很热。",
  "August is my birthday month.": "八月是我的生日月。",
  "September 10th is Teachers' Day.": "九月十日是教师节。",
  "October 1st is our National Day.": "十月一日是我们的国庆节。",
  "November is cool.": "十一月很凉爽。",
  "December has snow.": "十二月有雪。",
  "A few apples.": "几个苹果。",
  "A fun thing to do.": "一件有趣的事情。",
  "Sports meet is in May.": "运动会是在五月。",
  "We have a Chinese test.": "我们有一个中文考试。",
  "The sports meet is fun.": "运动会很有趣。",
  "Easter is in April.": "复活节在四月。",
  "A school trip in autumn.": "秋天的一次学校旅行。",
  "Happy New Year!": "新年快乐！",
  "Which month is it?": "现在是几月？",
  "February is the second month.": "二月是二月。",
  "March is the third month.": "三月是三月。",
  "April is the fourth month.": "四月是四月。",
  "May is the fifth month.": "五月是五月。",
  "December is the twelfth month.": "十二月是十二月。",
  "My birthday is on the twentieth.": "我的生日在二十号。",
  "Today is October 21st.": "今天是十月二十一。",
  "April 30th is his birthday.": "四月三十日是他的生日。",
  "A special day.": "一个特别的日子。",
  "April Fools' Day is fun.": "愚人节很有趣。",
  "What's the date today?": "今天几号？",
  "I will have a birthday party.": "我要过生日了。",
  "The dog is playing.": "狗在玩。",
  "The rabbit is jumping.": "兔子在跳。",
  "The panda is eating bamboo.": "熊猫在吃竹子。",
  "The cat is drinking water.": "猫在喝水。",
  "The baby is sleeping.": "宝宝在睡觉。",
  "The horses are running.": "马在跑。",
  "The monkey is climbing.": "猴子在爬。",
  "The monkeys are swinging.": "猴子们在荡秋千。",
  "Stop fighting, boys!": "别打架了，男孩们！",
  "The dog is mine.": "这条狗是我的。",
  "Is this book yours?": "这本书是你的吗？",
  "The dress is hers.": "这条裙子是她的。",
  "The toys are theirs.": "这些玩具是他们的。",
  "The classroom is ours.": "教室是我们的。",
  "We help each other.": "我们互相帮助。",
  "Care for the animals.": "照顾动物。",
  "Look there! Monkeys!": "看那里！猴子！",
  "The elephant is drinking water.": "大象在喝水。",
  "The panda is so cute.": "熊猫好可爱。",
  "What are they doing?": "他们在做什么？",
  "We are having an English class.": "我们在上英语课。",
  "They are eating lunch.": "他们在吃午饭。",
  "She is reading a book.": "她在看书。",
  "He is listening to music.": "他在听音乐。",
  "Keep to the right, please.": "请靠右走。",
  "Keep your desk clean.": "请保持你的桌子干净。",
  "Talk quietly in the library.": "在图书馆里轻声说话。",
  "Take turns to play.": "轮流玩。",
  "Walk quietly.": "轻轻走。",
  "Show me your photo.": "给我看看你的照片。",
  "Anything else?": "还有别的吗？",
  "See the robot exhibition.": "看看机器人展览。",
  "Say no to bad habits.": "拒绝坏习惯。",
  "I'm looking for my cat.": "我在找我家的猫。",
  "Visit the science museum.": "去参观科学博物馆。",
  "Mail a letter at the post office.": "在邮局寄封信。",
  "Buy books in the bookstore.": "在书店买书。",
  "Turn left at the crossing.": "在十字路口左转。",
  "Turn left at the school.": "在学校左转。",
  "Turn right at the park.": "在公园那拐弯。",
  "Go straight for 5 minutes.": "直走5分钟。",
  "The zoo is next to the park.": "动物园在公园旁边。",
  "Is it far from here?": "离这里远吗？",
  "Tell me the way.": "告诉我怎么走。",
  "Use the GPS to find it.": "用GPS找找看。",
  "Follow me, please.": "请跟我来。",
  "The feature of the city.": "这个城市的特色。",
  "An Italian restaurant nearby.": "附近有一家意大利餐厅。",
  "How can we get there?": "我们怎么去那里？",
  "How do you get to school?": "你怎么去学校？",
  "I go on foot.": "我走路去。",
  "I go by bus.": "我坐公交车去。",
  "Go by taxi.": "坐出租车去。",
  "I go by subway.": "我坐地铁去。",
  "We go by train.": "我们坐火车去。",
  "Go by ship.": "坐船去。",
  "They go by plane.": "他们坐飞机去。",
  "I go by bike.": "我骑自行车去。",
  "Slow down and stop.": "慢点，停下。",
  "Stop and wait at a red light.": "红灯停下来等。",
  "Look at the traffic lights.": "看交通灯。",
  "Wear a helmet on a bike.": "骑自行车要戴头盔。",
  "You must stop.": "你必须停下。",
  "Wear your helmet.": "戴上你的头盔。",
  "Pay attention to the cars.": "注意车辆。",
  "Look out for the traffic.": "小心交通。",
  "Munich is in Germany.": "慕尼黑在德国。",
  "Some children are from Germany.": "有些孩子是德国的。",
  "It snows in Alaska.": "阿拉斯加会下雪。",
  "They go by sled.": "他们坐雪橇。",
  "Go by ferry.": "坐渡轮去。",
  "The ferry goes to Scotland.": "这艘渡轮去苏格兰。",
  "So many ways to go to school.": "去学校有这么多方法。",
  "They go to school on a sled.": "他们坐雪橇去学校。",
  "Visit my grandparents.": "去看望我的祖父母。",
  "See a film tonight.": "今晚看个电影。",
  "Let's see a film.": "咱们看个电影。",
  "Take a trip to Beijing.": "去北京旅行。",
  "This evening is free.": "今晚有空。",
  "What are you doing tonight?": "你今晚在干嘛？",
  "Tomorrow is Monday.": "明天是星期一。",
  "See you next week.": "下周见。",
  "A Chinese-English dictionary.": "一本中英字典。",
  "Read a comic book.": "读一本漫画。",
  "Write in my word book.": "在我的单词本上写。",
  "Send a postcard.": "寄张明信片。",
  "The Mid-Autumn Festival is coming.": "中秋节快到了。",
  "We eat mooncakes.": "我们吃月饼。",
  "Read a poem about the moon.": "读一首关于月亮的诗。",
  "We get together.": "我们一起玩。",
  "Family get together.": "家庭聚会。",
  "Do word puzzles.": "做单词谜题。",
  "Go hiking on Sunday.": "星期天去徒步。",
  "I have a pen pal.": "我有一个笔友。",
  "The jasmine flower smells nice.": "茉莉花闻起来很香。",
  "Good idea!": "好主意！",
  "My pen pal lives in Canberra.": "我的笔友住在堪培拉。",
  "That's amazing!": "太棒了！",
  "Shall we dance?": "我们跳舞吧？",
  "Kick a goal!": "踢进一个球！",
  "Join our club.": "加入我们的俱乐部。",
  "The football club.": "足球俱乐部。",
  "My aunt is a factory worker.": "我阿姨是工厂工人。",
  "The postman brings letters.": "邮递员送信。",
  "A rich businessman.": "一个富有的商人。",
  "The police officer helps us.": "警察帮助我们。",
  "The fisherman catches fish.": "渔夫捕鱼。",
  "The scientist works hard.": "科学家工作很努力。",
  "The pilot flies planes.": "飞行员开飞机。",
  "Our coach is strict.": "我们的教练很严格。",
  "A beautiful country.": "一个美丽的国家。",
  "The sea is blue.": "大海是蓝色的。",
  "Stay healthy every day.": "每天保持健康。",
  "My sister goes to university.": "我姐姐上大学。",
  "If you like it, do it.": "喜欢就做。",
  "Use the computer.": "用电脑。",
  "Type quickly.": "打字要快。",
  "Run quickly!": "快跑！",
  "Don't be angry.": "别生气。",
  "Don't be afraid.": "别害怕。",
  "Mum is worried about me.": "妈妈担心我。",
  "You should see a doctor.": "你应该去看医生。",
  "Wear warm clothes.": "穿上暖和的衣服。",
  "Take a deep breath.": "深呼吸。",
  "Count to ten and relax.": "数到十放松一下。",
  "The cat chases the mouse.": "猫追老鼠。",
  "The cat chases the mice.": "猫追老鼠们。",
  "Bad weather today.": "今天天气不好。",
  "My leg hurts.": "我的腿疼。",
  "I feel ill.": "我感觉不舒服。",
  "What's wrong?": "怎么了？",
  "How do you feel?": "你感觉怎么样？",
  "I don't feel well.": "我不舒服。",
  "Sit on the grass.": "坐在草地上。",
  "I hear a bird.": "我听到一只鸟。",
  "Everyone is happy.": "大家都开心。",
  "Don't play in the mud.": "别在泥里玩。",
  "Let's pull it out.": "我们把它拔出来。",
  "What's wrong, Mum?": "妈妈，怎么了？",
  "How does Dad feel now?": "爸爸现在感觉怎么样？",
  "He is not well.": "他身体不好。",
  "Not really.": "其实不是。",
  "The dog runs after the cat.": "狗追猫。",
  "Why do you look so sad?": "你怎么看起来这么伤心？",
  "My sister is younger.": "我妹妹比我小。",
  "My brother is older.": "我哥哥比我大。",
  "The tree is taller.": "这棵树更高。",
  "This ruler is shorter.": "这把尺子更短。",
  "The snake is longer.": "这条蛇更长。",
  "He is thinner than me.": "他比我瘦。",
  "The elephant is heavier.": "这头大象更重。",
  "A bigger apple.": "一个更大的苹果。",
  "A smaller box.": "一个更小的盒子。",
  "Dad is stronger.": "爸爸更强壮。",
  "A big dinosaur.": "一个大恐龙。",
  "The dinosaurs are in the hall.": "恐龙们在大厅里。",
  "It's 5 meters tall.": "它有5米高。",
  "I'm taller than you.": "我比你高。",
  "We both like sports.": "我们俩都喜欢运动。",
  "It weighs 100 kilograms.": "它重100公斤。",
  "My grandma lives in the countryside.": "我奶奶住在乡下。",
  "The sun is lower.": "太阳低低的。",
  "My shadow is long.": "我的影子好长。",
  "The dog is smarter.": "狗儿聪明。",
  "I want to become a pilot.": "我想当飞行员。",
  "I cleaned my room.": "我打扫了房间。",
  "I washed my clothes.": "我洗了衣服。",
  "I stayed at home.": "我待在家里。",
  "I watched TV yesterday.": "我昨天看了电视。",
  "Grandpa drank tea.": "爷爷喝了茶。",
  "I read a book last night.": "我昨晚读了一本书。",
  "We played last Monday.": "我们上周一玩了。",
  "I was busy yesterday.": "我昨天很忙。",
  "Wash your hands before dinner.": "饭前要洗手。",
  "We saw a film.": "我们看了电影。",
  "I had a cold.": "我感冒了。",
  "I slept all day.": "我整天都在睡觉。",
  "I did sports yesterday morning.": "我昨天早上做了运动。",
  "What did you do last night?": "你昨晚做什么了？",
  "I stayed at home and slept.": "我待在家里睡觉了。",
  "I cleaned the window.": "我擦了窗户。",
  "Mum washed the dishes.": "妈妈洗了碗。",
  "I went to the park.": "我去公园了。",
  "Went to a summer camp.": "去了夏令营。",
  "We went camping.": "我们去露营了。",
  "Dad went fishing.": "爸爸去钓鱼了。",
  "I rode a horse.": "我骑马了。",
  "I hurt my foot.": "我脚受伤了。",
  "I ate fresh food.": "我吃了新鲜的食物。",
  "We took pictures.": "我们拍照了。",
  "I bought gifts for friends.": "我给朋友买了礼物。",
  "Play on the beach.": "在沙滩上玩。",
  "A picnic basket.": "野餐篮。",
  "I played a part.": "我演了一个角色。",
  "The dog licked my hand.": "狗舔了我的手。",
  "We laughed happily.": "我们开心地笑了。",
  "Play till 5 o'clock.": "玩到五点。",
  "I couldn't swim then.": "那时候我不会游泳。",
  "We ate in the dining hall.": "我们在食堂吃饭。",
  "Play basketball in the gym.": "在体育馆打篮球。",
  "There was no gym ten years ago.": "十年前没有体育馆。",
  "Go cycling in the park.": "去公园骑自行车。",
  "I go cycling every day.": "我每天都骑自行车。",
  "I can ice-skate.": "我会滑冰。",
  "Play badminton.": "打羽毛球。",
  "It's easy for me.": "对我来说很容易。",
  "Look up the word.": "查查这个单词。",
  "Search on the internet.": "在网上搜索。",
  "A different world.": "一个不同的世界。",
  "An active boy.": "一个活泼的男孩。",
  "Win the race.": "赢得比赛。",
  "Nothing at all.": "什么都没有。",
  "I thought it was easy.": "我觉得很容易。",
  "I felt happy.": "我感到很高兴。",
  "The cheetah runs fast.": "猎豹跑得快。",
  "I woke up early.": "我早起。",
  "A sweet dream.": "一个甜美的梦。",
  "I was at home.": "我在家。",
  "We were happy.": "我们很开心。",
  "There will be a new gym.": "会有一座新的体育馆。",
  "There was a small house.": "有一座小房子。",
  "There were many trees.": "有很多树。",
  "I didn't like winter before.": "以前我不喜欢冬天。"
};
